# MIL-based span localization for inappropriateness

This notebook evaluates Multiple Instance Learning (MIL) as a weakly supervised span localization approach.

Unlike post-hoc methods such as Integrated Gradients or SHAP, MIL trains a new model. Each argument is treated as a bag and automatically generated candidate spans are treated as latent instances. The model assigns a score to each candidate span and aggregates the strongest span scores into an argument-level prediction.

To make the results comparable to post-hoc attribution methods, the selected MIL spans are evaluated with the same perturbation protocol:

1. Select top-ranked MIL spans.
2. Mask the selected spans in the original argument.
3. Run the Ziegenbein document-level classifier on the masked text.
4. Measure the probability drop for the inappropriate class.

Hyperparameters are selected on the validation split and the final configuration is then applied to train, validation, and test.

In [ ]:
!pip install --upgrade --force-reinstall \
    "torch==2.5.1" \
    "transformers==4.46.3" \
    "datasets==3.1.0" \
    "pyarrow==18.1.0" \
    "accelerate>=0.26.0" \
    "sentencepiece" \
    "protobuf" 

In [2]:
import os
import re
import gc
import json
import math
import time
import html
import random
import unicodedata
from pathlib import Path
from datetime import datetime
from itertools import product

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import torch
import torch.nn as nn

from datasets import load_dataset
from torch.utils.data import Dataset, DataLoader
from transformers import (
    AutoTokenizer,
    AutoModel,
    pipeline,
    get_linear_schedule_with_warmup,
)
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
)

from tqdm.auto import tqdm
from IPython.display import HTML, display

/opt/conda/lib/python3.11/site-packages/pandas/core/computation/expressions.py:23: UserWarning: Pandas requires version '2.10.2' or newer of 'numexpr' (version '2.10.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
/opt/conda/lib/python3.11/site-packages/transformers/data/metrics/__init__.py:19: UserWarning: A NumPy version >=1.23.5 and <2.3.0 is required for this version of SciPy (detected version 2.4.6)
  from scipy.stats import pearsonr, spearmanr


In [3]:
# Reproducibility
SEED = 42
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
torch.cuda.manual_seed_all(SEED)

# Dataset and model
DATASET_NAME = "timonziegenbein/appropriateness-corpus"
MODEL_NAME = "timonziegenbein/appropriateness-classifier-binary"

# Columns
TEXT_COL = "post_text"
TEXT_NORM_COL = "text_norm"
LABEL_COL = "Inappropriateness"
ID_COL = "post_id"

# Classifier labels
APPROPRIATE_LABEL = "LABEL_0"
INAPPROPRIATE_LABEL = "LABEL_1"

# Device settings
DEVICE = 0 if torch.cuda.is_available() else -1
TORCH_DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# General inference settings
CLASSIFIER_MAX_LENGTH = 512
CLASSIFIER_BATCH_SIZE = 32

# MIL input settings
MIL_MAX_LENGTH = 96
MIL_BATCH_SIZE = 2
ENCODER_CHUNK_SIZE = 4
ENCODER_DTYPE = torch.bfloat16

# Training settings
NUM_EPOCHS = 3
WARMUP_RATIO = 0.1
WEIGHT_DECAY = 0.01
GRAD_CLIP_NORM = 1.0

# Separate learning rates for encoder and new MIL head
ENCODER_LR = 5e-6
HEAD_LR = 1e-4
HEAD_LR_FROZEN_ENCODER = 1e-3

# Candidate span settings
MIN_WORDS = 2
MAX_CANDIDATES = 80

# MIL initialization
INITIAL_INSTANCE_PROB = 0.02

# Perturbation settings
MASKING_TOP_N_SPANS = 3
ABLATION_MODE = "mask"

# Validation grid.
# Keep this small at first. Expand only after the pipeline works.
POOLING_MODES = [
    "topk_noisy_or",
    "topk_mean",
    "max",
]

TOP_K_VALUES = [
    1,
    3,
    5,
]

SPAN_LENGTH_SETS = [
    (3, 5, 8),
    (5, 10, 15),
    (10, 15, 20),
]

STRIDE_VALUES = [
    2,
    4,
]

FREEZE_ENCODER_VALUES = [
    True,
    # False,  # Activate only after frozen runs look reasonable.
]

# Optional debug limits. Set to None for full runs.
DEBUG_MAX_TRAIN_BAGS = None
DEBUG_MAX_VAL_BAGS = None

print("Device:", TORCH_DEVICE)

Device: cuda


In [ ]:
RUN_NAME = datetime.now().strftime("mil_span_run_%Y%m%d_%H%M%S")
BASE_DIR = Path("results")
OUTPUT_DIR = BASE_DIR / "mil_results" / RUN_NAME
BASE_DIR.mkdir(parents=True, exist_ok=True)
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

print("Saving results to:", OUTPUT_DIR)

Saving results to: mil_results/mil_span_run_20260727_114312


In [5]:
ds = load_dataset(DATASET_NAME)

train_df_raw = ds["train"].to_pandas()
val_df_raw = ds["validation"].to_pandas()
test_df_raw = ds["test"].to_pandas()


def attach_split(df, split_name):
    """Add a split column before creating global IDs."""
    df = df.copy().reset_index(drop=True)
    df["split"] = split_name
    return df


df_all = pd.concat(
    [
        attach_split(train_df_raw, "train"),
        attach_split(val_df_raw, "validation"),
        attach_split(test_df_raw, "test"),
    ],
    ignore_index=True,
)

df_all["global_row_id"] = np.arange(len(df_all))

train_df = df_all[df_all["split"] == "train"].copy().reset_index(drop=True)
val_df = df_all[df_all["split"] == "validation"].copy().reset_index(drop=True)
test_df = df_all[df_all["split"] == "test"].copy().reset_index(drop=True)

print("Train:", train_df.shape)
print("Validation:", val_df.shape)
print("Test:", test_df.shape)

for name, df in [("train", train_df), ("validation", val_df), ("test", test_df)]:
    print(name)
    display(df[LABEL_COL].value_counts(normalize=True).sort_index())

Train: (1533, 21)
Validation: (220, 21)
Test: (438, 21)
train


Inappropriateness
0    0.456621
1    0.543379
Name: proportion, dtype: float64

validation


Inappropriateness
0    0.436364
1    0.563636
Name: proportion, dtype: float64

test


Inappropriateness
0    0.486301
1    0.513699
Name: proportion, dtype: float64

In [8]:
def normalize_text(text: str) -> str:
    """
    Apply minimal normalization only.
    
    This keeps stylistic signals such as capitalization and punctuation mostly intact,
    while normalizing Unicode and whitespace.
    """
    if text is None:
        return ""
    
    text = unicodedata.normalize("NFKC", str(text))
    text = re.sub(r"\s+", " ", text).strip()
    return text


for df in [train_df, val_df, test_df]:
    df[TEXT_NORM_COL] = df[TEXT_COL].apply(normalize_text)

display(train_df[[TEXT_COL, TEXT_NORM_COL]].head())

,post_text,text_norm
0,"people cant be forced to wear school uniforms,...","people cant be forced to wear school uniforms,..."
1,"That form of argument degrades this forum, and...","That form of argument degrades this forum, and..."
2,I wouldnt turn her in becuase she is my wife. ...,I wouldnt turn her in becuase she is my wife. ...
3,No I wouldn't turn in my spouse. Just because ...,No I wouldn't turn in my spouse. Just because ...
4,TV is terrible. Except for Spongebob maybe. Th...,TV is terrible. Except for Spongebob maybe. Th...


In [9]:
pipe = pipeline(
    "text-classification",
    model=MODEL_NAME,
    device=DEVICE,
    top_k=None,
    truncation=True,
    max_length=CLASSIFIER_MAX_LENGTH,
)

classifier_tokenizer = pipe.tokenizer
classifier_model = pipe.model
classifier_model.eval()

MASK_TOKEN = (
    classifier_tokenizer.mask_token
    if classifier_tokenizer.mask_token is not None
    else "[MASK]"
)

print("MASK_TOKEN:", MASK_TOKEN)
print("label2id:", classifier_model.config.label2id)
print("id2label:", classifier_model.config.id2label)

MASK_TOKEN: [MASK]
label2id: {'LABEL_0': 0, 'LABEL_1': 1}
id2label: {0: 'LABEL_0', 1: 'LABEL_1'}


In [10]:
def predict_with_pipeline(texts, batch_size=CLASSIFIER_BATCH_SIZE):
    """
    Predict class probabilities and labels with the Hugging Face pipeline.
    
    Returns one row per input text with:
    - p_inappropriate_original
    - predicted_label
    - predicted_score
    """
    rows = []
    
    for start in tqdm(range(0, len(texts), batch_size), desc="Classifier inference"):
        batch_texts = texts[start:start + batch_size]
        outputs = pipe(batch_texts, batch_size=batch_size)
        
        for output in outputs:
            label_scores = {item["label"]: float(item["score"]) for item in output}
            
            p_inappropriate = label_scores.get(INAPPROPRIATE_LABEL, np.nan)
            best = max(output, key=lambda item: item["score"])
            
            rows.append({
                "p_inappropriate_original": p_inappropriate,
                "predicted_label": best["label"],
                "predicted_score": float(best["score"]),
            })
    
    return pd.DataFrame(rows)


def get_confusion_type(row):
    """Compute confusion type based on gold label and pipeline-predicted label."""
    gold = int(row[LABEL_COL])
    pred_inappropriate = row["predicted_label"] == INAPPROPRIATE_LABEL
    
    if gold == 1 and pred_inappropriate:
        return "TP"
    if gold == 1 and not pred_inappropriate:
        return "FN"
    if gold == 0 and pred_inappropriate:
        return "FP"
    if gold == 0 and not pred_inappropriate:
        return "TN"
    
    return "UNKNOWN"


def add_classifier_predictions(df):
    """Add original Ziegenbein pipeline predictions and confusion flags."""
    df = df.copy()
    pred_df = predict_with_pipeline(df[TEXT_NORM_COL].tolist())
    
    df = pd.concat(
        [df.reset_index(drop=True), pred_df.reset_index(drop=True)],
        axis=1,
    )
    
    df["confusion_type"] = df.apply(get_confusion_type, axis=1)
    df["is_true_positive"] = df["confusion_type"] == "TP"
    df["is_false_negative"] = df["confusion_type"] == "FN"
    df["is_false_positive"] = df["confusion_type"] == "FP"
    df["is_true_negative"] = df["confusion_type"] == "TN"
    
    return df


train_df = add_classifier_predictions(train_df)
val_df = add_classifier_predictions(val_df)
test_df = add_classifier_predictions(test_df)

display(train_df.head())
display(val_df["confusion_type"].value_counts())
display(test_df["confusion_type"].value_counts())

Classifier inference:   0%|          | 0/48 [00:00<?, ?it/s]

You seem to be using the pipelines sequentially on GPU. In order to maximize efficiency please use a dataset


Classifier inference:   0%|          | 0/7 [00:00<?, ?it/s]

Classifier inference:   0%|          | 0/14 [00:00<?, ?it/s]

,post_id,source_dataset,issue,post_text,Inappropriateness,Toxic Emotions,Excessive Intensity,Emotional Deception,Missing Commitment,Missing Seriousness,...,global_row_id,text_norm,p_inappropriate_original,predicted_label,predicted_score,confusion_type,is_true_positive,is_false_negative,is_false_positive,is_true_negative
0,1,0,Is the school uniform a good or bad idea:,"people cant be forced to wear school uniforms,...",1,0,0,0,1,0,...,0,"people cant be forced to wear school uniforms,...",0.997032,LABEL_1,0.997032,TP,True,False,False,False
1,2,0,Firefox vs internet explorer:,"That form of argument degrades this forum, and...",1,1,0,1,1,1,...,1,"That form of argument degrades this forum, and...",0.998218,LABEL_1,0.998218,TP,True,False,False,False
2,3,0,If your spouse committed murder and he or she ...,I wouldnt turn her in becuase she is my wife. ...,0,0,0,0,0,0,...,2,I wouldnt turn her in becuase she is my wife. ...,0.030317,LABEL_0,0.969683,TN,False,False,False,True
3,4,0,If your spouse committed murder and he or she ...,No I wouldn't turn in my spouse. Just because ...,1,0,0,0,1,0,...,3,No I wouldn't turn in my spouse. Just because ...,0.998705,LABEL_1,0.998705,TP,True,False,False,False
4,5,0,Tv is better than books:,TV is terrible. Except for Spongebob maybe. Th...,1,1,1,0,1,0,...,4,TV is terrible. Except for Spongebob maybe. Th...,0.998405,LABEL_1,0.998405,TP,True,False,False,False


confusion_type
TP    88
TN    66
FN    36
FP    30
Name: count, dtype: int64

confusion_type
TP    186
TN    142
FP     71
FN     39
Name: count, dtype: int64

## Candidate span generation

MIL needs candidate spans before training.  
Each argument is treated as a bag and the generated spans are treated as latent instances.

The parameter `span_lengths` controls the word-window lengths used to generate candidate spans.  

The parameter `stride` controls how densely candidate spans are generated.

In [11]:
def whitespace_token_offsets(text):
    """
    Return whitespace-based tokens with character offsets.
    
    This is intentionally simple and stable for character-level span extraction.
    """
    return [
        {
            "word_index": i,
            "text": match.group(),
            "char_start": int(match.start()),
            "char_end": int(match.end()),
        }
        for i, match in enumerate(re.finditer(r"\S+", str(text)))
    ]


def trim_char_span(text, start, end):
    """Trim whitespace from a character span."""
    while start < end and text[start].isspace():
        start += 1
    while end > start and text[end - 1].isspace():
        end -= 1
    return start, end


def evenly_limit_candidates(candidates, max_candidates):
    """
    Limit candidates while preserving coverage across the full argument.
    
    This avoids keeping only early spans, which would bias localization toward
    the beginning of the argument.
    """
    if max_candidates is None or len(candidates) <= max_candidates:
        return candidates
    
    indices = np.linspace(0, len(candidates) - 1, max_candidates).round().astype(int)
    indices = sorted(set(indices.tolist()))
    return [candidates[i] for i in indices]


def make_candidate_spans(
    text,
    span_lengths=(5, 10, 15),
    stride=4,
    min_words=MIN_WORDS,
    max_candidates=MAX_CANDIDATES,
):
    """
    Create multi-length candidate spans for MIL.
    
    Each candidate span stores:
    - character offsets,
    - whitespace-word offsets,
    - candidate length,
    - text span.
    """
    text = str(text)
    words = whitespace_token_offsets(text)
    
    if len(words) == 0:
        return []
    
    spans = []
    seen = set()
    
    for span_length in span_lengths:
        for word_start_idx in range(0, len(words), stride):
            word_end_exclusive = min(word_start_idx + span_length, len(words))
            window = words[word_start_idx:word_end_exclusive]
            
            if len(window) < min_words:
                continue
            
            char_start = window[0]["char_start"]
            char_end = window[-1]["char_end"]
            char_start, char_end = trim_char_span(text, char_start, char_end)
            
            if char_end <= char_start:
                continue
            
            key = (char_start, char_end)
            if key in seen:
                continue
            
            seen.add(key)
            
            spans.append({
                "span_text": text[char_start:char_end],
                "char_start": int(char_start),
                "char_end": int(char_end),
                "word_start_idx": int(word_start_idx),
                "word_end_idx": int(word_end_exclusive - 1),
                "span_len_words": int(word_end_exclusive - word_start_idx),
                "span_len_chars": int(char_end - char_start),
                "candidate_span_length": int(span_length),
            })
            
            if word_end_exclusive == len(words):
                break
    
    spans = evenly_limit_candidates(spans, max_candidates=max_candidates)
    return spans


example = train_df.iloc[0]
example_spans = make_candidate_spans(
    example[TEXT_NORM_COL],
    span_lengths=(5, 10, 15),
    stride=4,
)

print("Example text:", example[TEXT_NORM_COL])
print("Number of spans:", len(example_spans))
display(pd.DataFrame(example_spans).head())

Example text: people cant be forced to wear school uniforms, i mean each person has theri own wish whether they want to or dont want to wear school uniforms. I think each principal should think once again regarding the uniforms
Number of spans: 25


,span_text,char_start,char_end,word_start_idx,word_end_idx,span_len_words,span_len_chars,candidate_span_length
0,people cant be forced to,0,24,0,4,5,24,5
1,"to wear school uniforms, i",22,48,4,8,5,26,5
2,i mean each person has,47,69,8,12,5,22,5
3,has theri own wish whether,66,92,12,16,5,26,5
4,whether they want to or,85,108,16,20,5,23,5


In [12]:
class AppropriatenessMILDataset(Dataset):
    """
    Dataset for MIL span localization.
    
    One item corresponds to one argument-level bag.
    Candidate spans are latent instances within the bag.
    """
    def __init__(
        self,
        df,
        span_lengths=(5, 10, 15),
        stride=4,
        label_col=LABEL_COL,
        text_col=TEXT_NORM_COL,
        max_candidates=MAX_CANDIDATES,
    ):
        self.rows = []
        self.span_lengths = tuple(span_lengths)
        self.stride = int(stride)
        
        for _, row in df.iterrows():
            text = str(row[text_col])
            issue = str(row["issue"])
            label = int(row[label_col])
            
            candidates = make_candidate_spans(
                text=text,
                span_lengths=self.span_lengths,
                stride=self.stride,
                max_candidates=max_candidates,
            )
            
            if len(candidates) == 0:
                continue
            
            self.rows.append({
                "global_row_id": int(row["global_row_id"]),
                "post_id": row[ID_COL],
                "split": row["split"],
                "issue": issue,
                "text": text,
                "label": label,
                "p_inappropriate_original": float(row["p_inappropriate_original"]),
                "predicted_label_original": row["predicted_label"],
                "predicted_score_original": float(row["predicted_score"]),
                "confusion_type": row["confusion_type"],
                "is_true_positive": bool(row["is_true_positive"]),
                "is_false_negative": bool(row["is_false_negative"]),
                "is_false_positive": bool(row["is_false_positive"]),
                "is_true_negative": bool(row["is_true_negative"]),
                "candidates": candidates,
            })
    
    def __len__(self):
        return len(self.rows)
    
    def __getitem__(self, idx):
        return self.rows[idx]

In [13]:
mil_tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

def mil_collate_fn(batch, max_length=MIL_MAX_LENGTH):
    """
    Flatten all candidate spans in a batch into one list of encoder inputs.
    
    `bag_ids` stores which flattened span belongs to which original argument.
    """
    flat_inputs = []
    bag_ids = []
    span_metadata = []
    labels = []
    
    bag_metadata = []
    
    for bag_idx, item in enumerate(batch):
        labels.append(item["label"])
        
        bag_metadata.append({
            "global_row_id": item["global_row_id"],
            "post_id": item["post_id"],
            "split": item["split"],
            "issue": item["issue"],
            "text": item["text"],
            "label": item["label"],
            "p_inappropriate_original": item["p_inappropriate_original"],
            "predicted_label_original": item["predicted_label_original"],
            "predicted_score_original": item["predicted_score_original"],
            "confusion_type": item["confusion_type"],
            "is_true_positive": item["is_true_positive"],
            "is_false_negative": item["is_false_negative"],
            "is_false_positive": item["is_false_positive"],
            "is_true_negative": item["is_true_negative"],
            "num_candidate_spans": len(item["candidates"]),
        })
        
        for cand in item["candidates"]:
            # The issue is included because relevance-related inappropriateness
            # can be impossible to judge from a span alone.
            model_input = (
                f"Issue: {item['issue']}\n"
                f"Span: {cand['span_text']}"
            )
            
            flat_inputs.append(model_input)
            bag_ids.append(bag_idx)
            span_metadata.append(cand)
    
    encoded = mil_tokenizer(
        flat_inputs,
        padding=True,
        truncation=True,
        max_length=max_length,
        return_tensors="pt",
    )
    
    return {
        "input_ids": encoded["input_ids"],
        "attention_mask": encoded["attention_mask"],
        "bag_ids": torch.tensor(bag_ids, dtype=torch.long),
        "labels": torch.tensor(labels, dtype=torch.float),
        "span_metadata": span_metadata,
        "bag_metadata": bag_metadata,
        "num_bags": len(batch),
    }

In [14]:
class MILPoolingModel(nn.Module):
    """
    MIL model with configurable pooling.
    
    Supported pooling modes:
    - topk_noisy_or: bag is positive if at least one of the top-k spans is positive
    - topk_mean: mean logit over top-k spans
    - max: max-pooling over span logits
    """
    def __init__(
        self,
        model_name,
        pooling_mode="topk_noisy_or",
        top_k=5,
        initial_instance_prob=0.02,
        encoder_chunk_size=4,
        encoder_dtype=torch.bfloat16,
        freeze_encoder=True,
    ):
        super().__init__()
        
        if pooling_mode not in {"topk_noisy_or", "topk_mean", "max"}:
            raise ValueError(f"Unknown pooling mode: {pooling_mode}")
        
        self.encoder = AutoModel.from_pretrained(
            model_name,
            torch_dtype=encoder_dtype,
        )
        
        self.freeze_encoder = bool(freeze_encoder)
        
        if self.freeze_encoder:
            for param in self.encoder.parameters():
                param.requires_grad = False
        else:
            # Useful for memory-saving when fine-tuning.
            self.encoder.gradient_checkpointing_enable()
        
        hidden_size = self.encoder.config.hidden_size
        
        self.instance_classifier = nn.Linear(hidden_size, 1)
        self.pooling_mode = pooling_mode
        self.top_k = int(top_k)
        self.encoder_chunk_size = int(encoder_chunk_size)
        
        initial_bias = math.log(
            initial_instance_prob / (1.0 - initial_instance_prob)
        )
        
        # Small random initialization avoids identical span scores at the beginning.
        nn.init.normal_(self.instance_classifier.weight, mean=0.0, std=0.01)
        nn.init.constant_(self.instance_classifier.bias, initial_bias)
    
    def encode_in_chunks(self, input_ids, attention_mask):
        """
        Encode flattened candidate spans in chunks.
        
        When the encoder is frozen, no gradients are stored for the encoder,
        which substantially speeds up and reduces memory use.
        """
        cls_outputs = []
        
        context = torch.no_grad() if self.freeze_encoder else torch.enable_grad()
        
        with context:
            for start in range(0, input_ids.size(0), self.encoder_chunk_size):
                end = min(start + self.encoder_chunk_size, input_ids.size(0))
                
                outputs = self.encoder(
                    input_ids=input_ids[start:end],
                    attention_mask=attention_mask[start:end],
                    output_hidden_states=False,
                    output_attentions=False,
                    return_dict=True,
                )
                
                cls_outputs.append(outputs.last_hidden_state[:, 0].float())
        
        return torch.cat(cls_outputs, dim=0)
    
    def pool_logits(self, logits):
        """
        Aggregate instance logits into one bag logit.
        
        The output is a logit so that BCEWithLogitsLoss can be used.
        """
        if logits.numel() == 0:
            raise ValueError("Cannot pool an empty set of instance logits.")
        
        if self.pooling_mode == "max":
            return logits.max()
        
        k = min(self.top_k, logits.numel())
        logits_topk, _ = torch.topk(logits, k=k)
        
        if self.pooling_mode == "topk_mean":
            return logits_topk.mean()
        
        if self.pooling_mode == "topk_noisy_or":
            # Stable version of:
            # p_bag = 1 - product_j(1 - sigmoid(logit_j))
            log_p_negative = torch.sum(torch.nn.functional.logsigmoid(-logits_topk))
            log_p_negative = torch.clamp(log_p_negative, max=-1e-6)
            
            log_p_positive = torch.log(-torch.expm1(log_p_negative))
            bag_logit = log_p_positive - log_p_negative
            return bag_logit
        
        raise ValueError(f"Unknown pooling mode: {self.pooling_mode}")
    
    def forward(self, input_ids, attention_mask, bag_ids, num_bags):
        cls = self.encode_in_chunks(input_ids, attention_mask)
        
        instance_logits = self.instance_classifier(cls).squeeze(-1)
        instance_probs = torch.sigmoid(instance_logits)
        
        bag_logits = []
        bag_probs = []
        
        for bag_idx in range(num_bags):
            logits = instance_logits[bag_ids == bag_idx]
            bag_logit = self.pool_logits(logits)
            bag_prob = torch.sigmoid(bag_logit)
            
            bag_logits.append(bag_logit)
            bag_probs.append(bag_prob)
        
        return {
            "bag_logits": torch.stack(bag_logits),
            "bag_probs": torch.stack(bag_probs),
            "instance_logits": instance_logits,
            "instance_probs": instance_probs,
        }

In [15]:
def make_dataloaders(
    train_dataset,
    val_dataset,
    test_dataset=None,
    batch_size=MIL_BATCH_SIZE,
):
    """Create MIL dataloaders."""
    train_loader = DataLoader(
        train_dataset,
        batch_size=batch_size,
        shuffle=True,
        collate_fn=mil_collate_fn,
    )
    
    val_loader = DataLoader(
        val_dataset,
        batch_size=batch_size,
        shuffle=False,
        collate_fn=mil_collate_fn,
    )
    
    if test_dataset is None:
        return train_loader, val_loader
    
    test_loader = DataLoader(
        test_dataset,
        batch_size=batch_size,
        shuffle=False,
        collate_fn=mil_collate_fn,
    )
    
    return train_loader, val_loader, test_loader


def evaluate_bag_level(model, dataloader, threshold=0.5):
    """
    Evaluate MIL bag-level predictions against document-level labels.
    
    These metrics do not evaluate span correctness directly.
    """
    model.eval()
    
    all_labels = []
    all_probs = []
    
    with torch.no_grad():
        for batch in dataloader:
            outputs = model(
                input_ids=batch["input_ids"].to(TORCH_DEVICE),
                attention_mask=batch["attention_mask"].to(TORCH_DEVICE),
                bag_ids=batch["bag_ids"].to(TORCH_DEVICE),
                num_bags=batch["num_bags"],
            )
            
            all_labels.extend(batch["labels"].cpu().numpy().tolist())
            all_probs.extend(outputs["bag_probs"].detach().cpu().numpy().tolist())
    
    all_labels = np.array(all_labels, dtype=int)
    all_probs = np.array(all_probs, dtype=float)
    preds = (all_probs >= threshold).astype(int)
    
    metrics = {
        "accuracy": accuracy_score(all_labels, preds),
        "precision": precision_score(all_labels, preds, zero_division=0),
        "recall": recall_score(all_labels, preds, zero_division=0),
        "f1": f1_score(all_labels, preds, zero_division=0),
    }
    
    if len(np.unique(all_labels)) > 1:
        metrics["roc_auc"] = roc_auc_score(all_labels, all_probs)
    else:
        metrics["roc_auc"] = np.nan
    
    metrics["mean_predicted_probability"] = float(np.mean(all_probs))
    metrics["std_predicted_probability"] = float(np.std(all_probs))
    metrics["positive_prediction_rate"] = float(np.mean(preds))
    
    return metrics

In [16]:
def build_optimizer(model, freeze_encoder):
    """Build optimizer with separate learning rates for encoder and MIL head."""
    if freeze_encoder:
        return torch.optim.AdamW(
            model.instance_classifier.parameters(),
            lr=HEAD_LR_FROZEN_ENCODER,
            weight_decay=WEIGHT_DECAY,
        )
    
    return torch.optim.AdamW(
        [
            {"params": model.encoder.parameters(), "lr": ENCODER_LR},
            {"params": model.instance_classifier.parameters(), "lr": HEAD_LR},
        ],
        weight_decay=WEIGHT_DECAY,
    )


def train_one_mil_model(
    config,
    train_dataset,
    val_dataset,
    output_dir,
):
    """
    Train one MIL configuration and return the trained model plus logs.
    
    Hyperparameters are supplied through config.
    """
    train_loader, val_loader = make_dataloaders(
        train_dataset=train_dataset,
        val_dataset=val_dataset,
        batch_size=MIL_BATCH_SIZE,
    )
    
    model = MILPoolingModel(
        model_name=MODEL_NAME,
        pooling_mode=config["pooling_mode"],
        top_k=config["top_k"],
        initial_instance_prob=INITIAL_INSTANCE_PROB,
        encoder_chunk_size=ENCODER_CHUNK_SIZE,
        encoder_dtype=ENCODER_DTYPE,
        freeze_encoder=config["freeze_encoder"],
    ).to(TORCH_DEVICE)
    
    optimizer = build_optimizer(model, freeze_encoder=config["freeze_encoder"])
    
    num_training_steps = NUM_EPOCHS * len(train_loader)
    num_warmup_steps = int(WARMUP_RATIO * num_training_steps)
    
    scheduler = get_linear_schedule_with_warmup(
        optimizer,
        num_warmup_steps=num_warmup_steps,
        num_training_steps=num_training_steps,
    )
    
    criterion = nn.BCEWithLogitsLoss()
    training_history = []
    best_val_f1 = -1.0
    best_state_dict = None
    
    start_time = time.time()
    
    for epoch in range(NUM_EPOCHS):
        model.train()
        epoch_start = time.time()
        total_loss = 0.0
        
        for step, batch in enumerate(train_loader):
            optimizer.zero_grad(set_to_none=True)
            
            outputs = model(
                input_ids=batch["input_ids"].to(TORCH_DEVICE),
                attention_mask=batch["attention_mask"].to(TORCH_DEVICE),
                bag_ids=batch["bag_ids"].to(TORCH_DEVICE),
                num_bags=batch["num_bags"],
            )
            
            labels = batch["labels"].to(TORCH_DEVICE).float()
            loss = criterion(outputs["bag_logits"], labels)
            
            loss.backward()
            torch.nn.utils.clip_grad_norm_(model.parameters(), GRAD_CLIP_NORM)
            
            optimizer.step()
            scheduler.step()
            
            total_loss += float(loss.item())
            
            if step % 50 == 0:
                print(
                    f"Epoch {epoch + 1}/{NUM_EPOCHS} | "
                    f"Step {step}/{len(train_loader)} | "
                    f"Loss {loss.item():.4f}"
                )
        
        avg_loss = total_loss / max(len(train_loader), 1)
        val_metrics = evaluate_bag_level(model, val_loader)
        epoch_time = (time.time() - epoch_start) / 60
        
        row = {
            "epoch": epoch + 1,
            "train_loss": avg_loss,
            "epoch_time_minutes": epoch_time,
            **{f"val_{k}": v for k, v in val_metrics.items()},
        }
        
        training_history.append(row)
        
        print(
            f"Epoch {epoch + 1}/{NUM_EPOCHS} finished | "
            f"loss={avg_loss:.4f} | "
            f"val_f1={val_metrics['f1']:.4f} | "
            f"val_auc={val_metrics['roc_auc']:.4f} | "
            f"time={epoch_time:.2f} min"
        )
        
        if val_metrics["f1"] > best_val_f1:
            best_val_f1 = val_metrics["f1"]
            best_state_dict = {
                k: v.detach().cpu().clone()
                for k, v in model.state_dict().items()
            }
    
    if best_state_dict is not None:
        model.load_state_dict(best_state_dict)
    
    total_time = (time.time() - start_time) / 60
    
    train_metrics = evaluate_bag_level(model, train_loader)
    val_metrics = evaluate_bag_level(model, val_loader)
    
    result = {
        **config,
        "train_time_minutes": total_time,
        **{f"train_{k}": v for k, v in train_metrics.items()},
        **{f"val_{k}": v for k, v in val_metrics.items()},
    }
    
    history_df = pd.DataFrame(training_history)
    
    return model, result, history_df

In [17]:
def collect_mil_outputs(model, dataset, config, threshold=0.5):
    """
    Collect bag-level predictions and span-level scores from a trained MIL model.
    
    Returns:
    - argument_df: one row per argument
    - span_df: one row per candidate span
    """
    model.eval()
    
    argument_rows = []
    span_rows = []
    
    for item_idx, item in enumerate(tqdm(dataset, desc="Collecting MIL outputs")):
        batch = mil_collate_fn([item])
        
        with torch.no_grad():
            outputs = model(
                input_ids=batch["input_ids"].to(TORCH_DEVICE),
                attention_mask=batch["attention_mask"].to(TORCH_DEVICE),
                bag_ids=batch["bag_ids"].to(TORCH_DEVICE),
                num_bags=batch["num_bags"],
            )
        
        bag_prob = float(outputs["bag_probs"].detach().cpu().item())
        pred_label = int(bag_prob >= threshold)
        instance_probs = outputs["instance_probs"].detach().cpu().numpy()
        instance_logits = outputs["instance_logits"].detach().cpu().numpy()
        
        meta = batch["bag_metadata"][0]
        
        argument_rows.append({
            **meta,
            "mil_probability": bag_prob,
            "mil_predicted_label": pred_label,
            "mil_correct": int(pred_label == meta["label"]),
            "mil_confusion_type": (
                "TP" if meta["label"] == 1 and pred_label == 1 else
                "FN" if meta["label"] == 1 and pred_label == 0 else
                "FP" if meta["label"] == 0 and pred_label == 1 else
                "TN"
            ),
            **config,
        })
        
        for prob, logit, span in zip(
            instance_probs,
            instance_logits,
            batch["span_metadata"],
        ):
            span_rows.append({
                "global_row_id": meta["global_row_id"],
                "post_id": meta["post_id"],
                "split": meta["split"],
                "issue": meta["issue"],
                "label": meta["label"],
                "confusion_type": meta["confusion_type"],
                "mil_probability": bag_prob,
                "mil_predicted_label": pred_label,
                "span_score": float(prob),
                "span_logit": float(logit),
                "span_text": span["span_text"],
                "char_start": span["char_start"],
                "char_end": span["char_end"],
                "word_start_idx": span["word_start_idx"],
                "word_end_idx": span["word_end_idx"],
                "span_len_words": span["span_len_words"],
                "span_len_chars": span["span_len_chars"],
                "candidate_span_length": span["candidate_span_length"],
                "text": meta["text"],
                **config,
            })
    
    argument_df = pd.DataFrame(argument_rows)
    span_df = pd.DataFrame(span_rows)
    
    span_df["span_rank"] = (
        span_df
        .groupby(["global_row_id"])["span_score"]
        .rank(method="first", ascending=False)
        .astype(int)
    )
    
    return argument_df, span_df

In [18]:
def merge_overlapping_spans(spans):
    """
    Merge overlapping or directly adjacent character spans.
    
    This prevents repeated masking and produces cleaner span lists.
    """
    if not spans:
        return []
    
    spans = sorted(spans, key=lambda x: (x["char_start"], x["char_end"]))
    merged = [dict(spans[0])]
    
    for span in spans[1:]:
        last = merged[-1]
        
        if int(span["char_start"]) <= int(last["char_end"]):
            last["char_end"] = max(int(last["char_end"]), int(span["char_end"]))
            last["span_text"] = last["text"][last["char_start"]:last["char_end"]] if "text" in last else last["span_text"]
        else:
            merged.append(dict(span))
    
    return merged


def mask_spans_in_text(text, spans, mask_token=MASK_TOKEN):
    """Mask multiple character spans in a text."""
    text = str(text)
    
    if not spans:
        return text
    
    spans = sorted(spans, key=lambda x: int(x["char_start"]))
    
    parts = []
    last_end = 0
    
    for span in spans:
        start = int(span["char_start"])
        end = int(span["char_end"])
        
        if start < last_end:
            continue
        
        parts.append(text[last_end:start])
        parts.append(mask_token)
        last_end = end
    
    parts.append(text[last_end:])
    
    return "".join(parts)


def predict_masked_texts(texts, batch_size=CLASSIFIER_BATCH_SIZE):
    """Predict inappropriate probabilities for masked texts."""
    pred_df = predict_with_pipeline(texts, batch_size=batch_size)
    return pred_df["p_inappropriate_original"].tolist()


def add_mil_perturbation_scores(
    argument_df,
    span_df,
    top_n_spans=MASKING_TOP_N_SPANS,
    mask_token=MASK_TOKEN,
):
    """
    Select top-N MIL spans per argument, mask them, and score the masked text.
    
    The probability drop is computed with the original Ziegenbein classifier,
    making this comparable to IG/SHAP perturbation evaluation.
    """
    argument_df = argument_df.copy()
    span_df = span_df.copy()
    
    top_span_df = (
        span_df
        .sort_values(["global_row_id", "span_score"], ascending=[True, False])
        .groupby("global_row_id")
        .head(top_n_spans)
        .copy()
    )
    
    masked_texts = []
    selected_spans_json = []
    selected_span_texts = []
    selected_char_starts = []
    selected_char_ends = []
    selected_word_starts = []
    selected_word_ends = []
    total_masked_chars = []
    total_masked_words = []
    n_selected_spans = []
    
    for _, row in argument_df.iterrows():
        gid = row["global_row_id"]
        text = row["text"]
        
        spans = top_span_df[top_span_df["global_row_id"] == gid].copy()
        
        span_records = []
        
        for _, span in spans.iterrows():
            span_records.append({
                "span_text": span["span_text"],
                "char_start": int(span["char_start"]),
                "char_end": int(span["char_end"]),
                "word_start_idx": int(span["word_start_idx"]),
                "word_end_idx": int(span["word_end_idx"]),
                "span_len_words": int(span["span_len_words"]),
                "span_len_chars": int(span["span_len_chars"]),
                "span_score": float(span["span_score"]),
                "span_rank": int(span["span_rank"]),
                "candidate_span_length": int(span["candidate_span_length"]),
            })
        
        masked_text = mask_spans_in_text(
            text=text,
            spans=span_records,
            mask_token=mask_token,
        )
        
        masked_texts.append(masked_text)
        selected_spans_json.append(json.dumps(span_records, ensure_ascii=False))
        selected_span_texts.append([s["span_text"] for s in span_records])
        selected_char_starts.append([s["char_start"] for s in span_records])
        selected_char_ends.append([s["char_end"] for s in span_records])
        selected_word_starts.append([s["word_start_idx"] for s in span_records])
        selected_word_ends.append([s["word_end_idx"] for s in span_records])
        total_masked_chars.append(sum(s["span_len_chars"] for s in span_records))
        total_masked_words.append(sum(s["span_len_words"] for s in span_records))
        n_selected_spans.append(len(span_records))
    
    p_masked = predict_masked_texts(masked_texts)
    
    argument_df["attribution_method"] = "mil"
    argument_df["ablation_mode"] = ABLATION_MODE
    argument_df["top_n_masked_spans"] = top_n_spans
    argument_df["masked_text"] = masked_texts
    argument_df["p_inappropriate_masked"] = p_masked
    argument_df["prob_drop"] = (
        argument_df["p_inappropriate_original"] -
        argument_df["p_inappropriate_masked"]
    )
    
    argument_df["selected_spans_json"] = selected_spans_json
    argument_df["selected_span_texts"] = selected_span_texts
    argument_df["selected_span_char_start_indices"] = selected_char_starts
    argument_df["selected_span_char_end_indices"] = selected_char_ends
    argument_df["selected_span_word_start_indices"] = selected_word_starts
    argument_df["selected_span_word_end_indices"] = selected_word_ends
    argument_df["n_selected_spans"] = n_selected_spans
    argument_df["total_masked_chars"] = total_masked_chars
    argument_df["total_masked_words"] = total_masked_words
    
    argument_df["n_words"] = argument_df["text"].apply(lambda x: len(whitespace_token_offsets(x)))
    argument_df["masked_word_ratio"] = (
        argument_df["total_masked_words"] /
        argument_df["n_words"].replace(0, np.nan)
    )
    
    return argument_df, top_span_df

In [19]:
def build_config_id(config):
    """Create a readable config ID for filenames and tables."""
    span_label = "-".join(map(str, config["span_lengths"]))
    return (
        f"pool={config['pooling_mode']}"
        f"__topk={config['top_k']}"
        f"__spans={span_label}"
        f"__stride={config['stride']}"
        f"__freeze={config['freeze_encoder']}"
    )


def subset_dataset(dataset, max_items):
    """Optionally limit a dataset for debugging."""
    if max_items is None:
        return dataset
    
    dataset.rows = dataset.rows[:max_items]
    return dataset


def run_single_validation_config(config):
    """
    Train and evaluate one MIL configuration.
    
    The model is trained on train and evaluated on validation.
    Perturbation is computed on validation true positives from the original
    Ziegenbein classifier to stay comparable with IG/SHAP.
    """
    config = dict(config)
    config["config_id"] = build_config_id(config)
    
    print("\n" + "=" * 100)
    print("Running config:", config["config_id"])
    print("=" * 100)
    
    config_dir = OUTPUT_DIR / "validation_grid" / config["config_id"]
    config_dir.mkdir(parents=True, exist_ok=True)
    
    train_dataset = AppropriatenessMILDataset(
        train_df,
        span_lengths=config["span_lengths"],
        stride=config["stride"],
    )
    
    val_dataset = AppropriatenessMILDataset(
        val_df,
        span_lengths=config["span_lengths"],
        stride=config["stride"],
    )
    
    train_dataset = subset_dataset(train_dataset, DEBUG_MAX_TRAIN_BAGS)
    val_dataset = subset_dataset(val_dataset, DEBUG_MAX_VAL_BAGS)
    
    model, metrics_row, history_df = train_one_mil_model(
        config=config,
        train_dataset=train_dataset,
        val_dataset=val_dataset,
        output_dir=config_dir,
    )
    
    val_argument_df, val_span_df = collect_mil_outputs(
        model=model,
        dataset=val_dataset,
        config=config,
    )
    
    # Perturbation on validation TPs based on the original Ziegenbein classifier.
    val_tp_argument_df = val_argument_df[
        val_argument_df["confusion_type"] == "TP"
    ].copy()
    
    val_tp_span_df = val_span_df[
        val_span_df["global_row_id"].isin(val_tp_argument_df["global_row_id"])
    ].copy()
    
    if len(val_tp_argument_df) > 0:
        val_tp_argument_df, val_top_span_df = add_mil_perturbation_scores(
            argument_df=val_tp_argument_df,
            span_df=val_tp_span_df,
            top_n_spans=MASKING_TOP_N_SPANS,
        )
        
        perturbation_summary = {
            "val_tp_n_arguments": int(val_tp_argument_df["global_row_id"].nunique()),
            "val_tp_mean_prob_drop": float(val_tp_argument_df["prob_drop"].mean()),
            "val_tp_median_prob_drop": float(val_tp_argument_df["prob_drop"].median()),
            "val_tp_positive_drop_rate": float((val_tp_argument_df["prob_drop"] > 0).mean()),
            "val_tp_strong_drop_rate_001": float((val_tp_argument_df["prob_drop"] > 0.01).mean()),
            "val_tp_strong_drop_rate_005": float((val_tp_argument_df["prob_drop"] > 0.05).mean()),
            "val_tp_mean_masked_word_ratio": float(val_tp_argument_df["masked_word_ratio"].mean()),
            "val_tp_mean_total_masked_words": float(val_tp_argument_df["total_masked_words"].mean()),
        }
    else:
        val_top_span_df = pd.DataFrame()
        perturbation_summary = {
            "val_tp_n_arguments": 0,
            "val_tp_mean_prob_drop": np.nan,
            "val_tp_median_prob_drop": np.nan,
            "val_tp_positive_drop_rate": np.nan,
            "val_tp_strong_drop_rate_001": np.nan,
            "val_tp_strong_drop_rate_005": np.nan,
            "val_tp_mean_masked_word_ratio": np.nan,
            "val_tp_mean_total_masked_words": np.nan,
        }
    
    final_row = {
        **metrics_row,
        **perturbation_summary,
    }
    
    history_df.to_csv(config_dir / "training_history.csv", index=False)
    val_argument_df.to_csv(config_dir / "validation_argument_predictions.csv", index=False)
    val_span_df.to_csv(config_dir / "validation_span_scores.csv", index=False)
    val_tp_argument_df.to_csv(config_dir / "validation_tp_perturbation.csv", index=False)
    val_top_span_df.to_csv(config_dir / "validation_tp_top_spans.csv", index=False)
    
    torch.save(
        {
            "model_state_dict": model.state_dict(),
            "config": config,
            "metrics": final_row,
        },
        config_dir / "model_checkpoint.pt",
    )
    
    # Free memory between configs.
    model_cpu_state = {
        k: v.cpu()
        for k, v in model.state_dict().items()
    }
    
    del model
    gc.collect()
    torch.cuda.empty_cache()
    
    return final_row, model_cpu_state

# Load existing Summary to slect config

In [20]:
val_config_summary = pd.read_csv("mil_results/mil_span_run_20260724_091019/mil_validation_config_summary.csv")

display(val_config_summary)

,pooling_mode,top_k,span_lengths,span_lengths_label,stride,freeze_encoder,config_id,train_time_minutes,train_accuracy,train_precision,...,val_std_predicted_probability,val_positive_prediction_rate,val_tp_n_arguments,val_tp_mean_prob_drop,val_tp_median_prob_drop,val_tp_positive_drop_rate,val_tp_strong_drop_rate_001,val_tp_strong_drop_rate_005,val_tp_mean_masked_word_ratio,val_tp_mean_total_masked_words
0,topk_noisy_or,1,"(3, 5, 8)",3-5-8,2,True,pool=topk_noisy_or__topk=1__spans=3-5-8__strid...,39.369830,0.705153,0.830156,...,0.299365,0.340909,88,0.031947,0.000112,0.556818,0.147727,0.068182,0.437449,19.784091
1,topk_noisy_or,3,"(3, 5, 8)",3-5-8,2,True,pool=topk_noisy_or__topk=3__spans=3-5-8__strid...,39.617171,0.669928,0.879350,...,0.321084,0.245455,88,0.056294,0.000105,0.590909,0.204545,0.125000,0.412257,18.988636
2,topk_noisy_or,5,"(3, 5, 8)",3-5-8,2,True,pool=topk_noisy_or__topk=5__spans=3-5-8__strid...,39.556878,0.709067,0.860335,...,0.363772,0.336364,88,0.049984,0.000118,0.602273,0.204545,0.125000,0.410166,18.943182
3,topk_noisy_or,1,"(3, 5, 8)",3-5-8,4,True,pool=topk_noisy_or__topk=1__spans=3-5-8__strid...,31.115266,0.713633,0.705637,...,0.321613,0.559091,88,0.057901,0.000021,0.522727,0.193182,0.136364,0.391577,17.920455
4,topk_noisy_or,3,"(3, 5, 8)",3-5-8,4,True,pool=topk_noisy_or__topk=3__spans=3-5-8__strid...,31.118815,0.711024,0.822848,...,0.356458,0.390909,88,0.042025,0.000080,0.545455,0.193182,0.125000,0.396521,18.272727
5,topk_noisy_or,5,"(3, 5, 8)",3-5-8,4,True,pool=topk_noisy_or__topk=5__spans=3-5-8__strid...,31.132370,0.702544,0.821124,...,0.356559,0.381818,88,0.047337,0.000006,0.511364,0.181818,0.125000,0.396439,18.204545
6,topk_noisy_or,1,"(5, 10, 15)",5-10-15,2,True,pool=topk_noisy_or__topk=1__spans=5-10-15__str...,38.325160,0.706458,0.867562,...,0.324253,0.295455,88,0.083566,0.000267,0.625000,0.204545,0.170455,0.667694,32.500000
7,topk_noisy_or,3,"(5, 10, 15)",5-10-15,2,True,pool=topk_noisy_or__topk=3__spans=5-10-15__str...,38.376781,0.742335,0.847619,...,0.354260,0.377273,88,0.101466,0.000150,0.636364,0.204545,0.181818,0.653329,32.022727
8,topk_noisy_or,5,"(5, 10, 15)",5-10-15,2,True,pool=topk_noisy_or__topk=5__spans=5-10-15__str...,38.363592,0.736464,0.865417,...,0.350296,0.331818,88,0.070183,0.000150,0.613636,0.193182,0.147727,0.661820,32.522727
9,topk_noisy_or,1,"(5, 10, 15)",5-10-15,4,True,pool=topk_noisy_or__topk=1__spans=5-10-15__str...,30.460005,0.748858,0.819088,...,0.368203,0.427273,88,0.074936,0.000246,0.590909,0.204545,0.147727,0.639059,31.659091


Epoch 2/3 | Step 700/767 | Loss 0.4289


Epoch 2/3 | Step 750/767 | Loss 0.9937


Epoch 2/3 finished | loss=0.7492 | val_f1=0.6571 | val_auc=0.7552 | time=10.37 min


Epoch 3/3 | Step 0/767 | Loss 0.0296


Epoch 3/3 | Step 50/767 | Loss 0.0482


Epoch 3/3 | Step 100/767 | Loss 0.3855


Epoch 3/3 | Step 150/767 | Loss 0.0320


Epoch 3/3 | Step 200/767 | Loss 0.2776


Epoch 3/3 | Step 250/767 | Loss 1.2699


Epoch 3/3 | Step 300/767 | Loss 0.0229


Epoch 3/3 | Step 350/767 | Loss 1.4630


Epoch 3/3 | Step 400/767 | Loss 0.4242


Epoch 3/3 | Step 450/767 | Loss 0.0243


Epoch 3/3 | Step 500/767 | Loss 0.9909


Epoch 3/3 | Step 550/767 | Loss 1.6168


Epoch 3/3 | Step 600/767 | Loss 0.5789


Epoch 3/3 | Step 650/767 | Loss 1.2695


Epoch 3/3 | Step 700/767 | Loss 1.0439


Epoch 3/3 | Step 750/767 | Loss 0.6101


Epoch 3/3 finished | loss=0.6895 | val_f1=0.5654 | val_auc=0.7570 | time=10.36 min


Classifier inference:   0%|          | 0/3 [00:00<?, ?it/s]


Running config: pool=topk_noisy_or__topk=5__spans=3-5-8__stride=4__freeze=True


Epoch 1/3 | Step 0/767 | Loss 1.8675


Epoch 1/3 | Step 50/767 | Loss 0.7280


Epoch 1/3 | Step 100/767 | Loss 0.4699


Epoch 1/3 | Step 150/767 | Loss 0.7082


Epoch 1/3 | Step 200/767 | Loss 0.4125


Epoch 1/3 | Step 250/767 | Loss 1.2579


Epoch 1/3 | Step 300/767 | Loss 0.3680


Epoch 1/3 | Step 350/767 | Loss 0.9418


Epoch 1/3 | Step 400/767 | Loss 1.8162


Epoch 1/3 | Step 450/767 | Loss 0.1235


Epoch 1/3 | Step 500/767 | Loss 0.0218


Epoch 1/3 | Step 550/767 | Loss 0.1438


Epoch 1/3 | Step 600/767 | Loss 0.8031


Epoch 1/3 | Step 650/767 | Loss 0.4187


Epoch 1/3 | Step 700/767 | Loss 0.8852


Epoch 1/3 | Step 750/767 | Loss 0.2612


Epoch 1/3 finished | loss=0.8368 | val_f1=0.6537 | val_auc=0.7544 | time=10.38 min


Epoch 2/3 | Step 0/767 | Loss 0.2418


Epoch 2/3 | Step 50/767 | Loss 1.2673


Epoch 2/3 | Step 100/767 | Loss 1.1469


Epoch 2/3 | Step 150/767 | Loss 0.9427


Epoch 2/3 | Step 200/767 | Loss 0.2723


Epoch 2/3 | Step 250/767 | Loss 1.7298


Epoch 2/3 | Step 300/767 | Loss 0.1832


Epoch 2/3 | Step 350/767 | Loss 0.4943


Epoch 2/3 | Step 400/767 | Loss 0.0066


Epoch 2/3 | Step 450/767 | Loss 1.0528


Epoch 2/3 | Step 500/767 | Loss 1.2556


Epoch 2/3 | Step 550/767 | Loss 0.3866


Epoch 2/3 | Step 600/767 | Loss 2.4308


Epoch 2/3 | Step 650/767 | Loss 0.0067


Epoch 2/3 | Step 700/767 | Loss 0.4754


Epoch 2/3 | Step 750/767 | Loss 0.5612


Epoch 2/3 finished | loss=0.7998 | val_f1=0.6538 | val_auc=0.7591 | time=10.37 min


Epoch 3/3 | Step 0/767 | Loss 0.0020


Epoch 3/3 | Step 50/767 | Loss 0.3504


Epoch 3/3 | Step 100/767 | Loss 0.9462


Epoch 3/3 | Step 150/767 | Loss 0.0263


Epoch 3/3 | Step 200/767 | Loss 0.1576


Epoch 3/3 | Step 250/767 | Loss 0.0098


Epoch 3/3 | Step 300/767 | Loss 0.6541


Epoch 3/3 | Step 350/767 | Loss 0.3640


Epoch 3/3 | Step 400/767 | Loss 0.2147


Epoch 3/3 | Step 450/767 | Loss 0.1981


Epoch 3/3 | Step 500/767 | Loss 2.1363


Epoch 3/3 | Step 550/767 | Loss 0.2620


Epoch 3/3 | Step 600/767 | Loss 1.3600


Epoch 3/3 | Step 650/767 | Loss 0.3491


Epoch 3/3 | Step 700/767 | Loss 0.4187


Epoch 3/3 | Step 750/767 | Loss 0.1179


Epoch 3/3 finished | loss=0.7399 | val_f1=0.5608 | val_auc=0.7604 | time=10.36 min


Classifier inference:   0%|          | 0/3 [00:00<?, ?it/s]


Running config: pool=topk_noisy_or__topk=1__spans=5-10-15__stride=2__freeze=True


Epoch 1/3 | Step 0/767 | Loss 0.0278


Epoch 1/3 | Step 50/767 | Loss 0.9385


Epoch 1/3 | Step 100/767 | Loss 1.1929


Epoch 1/3 | Step 150/767 | Loss 0.6484


Epoch 1/3 | Step 200/767 | Loss 0.9204


Epoch 1/3 | Step 250/767 | Loss 0.9500


Epoch 1/3 | Step 300/767 | Loss 1.4095


Epoch 1/3 | Step 350/767 | Loss 0.2169


Epoch 1/3 | Step 400/767 | Loss 0.0832


Epoch 1/3 | Step 450/767 | Loss 0.3698


Epoch 1/3 | Step 500/767 | Loss 0.2486


Epoch 1/3 | Step 550/767 | Loss 0.3810


Epoch 1/3 | Step 600/767 | Loss 1.1136


Epoch 1/3 | Step 650/767 | Loss 0.0984


Epoch 1/3 | Step 700/767 | Loss 0.1376


Epoch 1/3 | Step 750/767 | Loss 0.1157


Epoch 1/3 finished | loss=0.7452 | val_f1=0.2222 | val_auc=0.7471 | time=12.77 min


Epoch 2/3 | Step 0/767 | Loss 0.3083


Epoch 2/3 | Step 50/767 | Loss 0.2272


Epoch 2/3 | Step 100/767 | Loss 1.6595


Epoch 2/3 | Step 150/767 | Loss 0.0743


Epoch 2/3 | Step 200/767 | Loss 0.3906


Epoch 2/3 | Step 250/767 | Loss 0.9278


Epoch 2/3 | Step 300/767 | Loss 1.8446


Epoch 2/3 | Step 350/767 | Loss 2.0810


Epoch 2/3 | Step 400/767 | Loss 0.2969


Epoch 2/3 | Step 450/767 | Loss 0.3425


Epoch 2/3 | Step 500/767 | Loss 0.0864


Epoch 2/3 | Step 550/767 | Loss 0.0977


Epoch 2/3 | Step 600/767 | Loss 0.2464


Epoch 2/3 | Step 650/767 | Loss 0.1223


Epoch 2/3 | Step 700/767 | Loss 0.5742


Epoch 2/3 | Step 750/767 | Loss 0.6987


Epoch 2/3 finished | loss=0.6956 | val_f1=0.5608 | val_auc=0.7581 | time=12.77 min


Epoch 3/3 | Step 0/767 | Loss 1.2385


Epoch 3/3 | Step 50/767 | Loss 0.7650


Epoch 3/3 | Step 100/767 | Loss 0.0543


Epoch 3/3 | Step 150/767 | Loss 0.5822


Epoch 3/3 | Step 200/767 | Loss 0.6544


Epoch 3/3 | Step 250/767 | Loss 2.6569


Epoch 3/3 | Step 300/767 | Loss 0.2081


Epoch 3/3 | Step 350/767 | Loss 1.5859


Epoch 3/3 | Step 400/767 | Loss 0.0571


Epoch 3/3 | Step 450/767 | Loss 0.0531


Epoch 3/3 | Step 500/767 | Loss 0.2184


Epoch 3/3 | Step 550/767 | Loss 0.0468


Epoch 3/3 | Step 600/767 | Loss 0.4646


Epoch 3/3 | Step 650/767 | Loss 0.4140


Epoch 3/3 | Step 700/767 | Loss 0.9203


Epoch 3/3 | Step 750/767 | Loss 1.0019


Epoch 3/3 finished | loss=0.6716 | val_f1=0.5326 | val_auc=0.7559 | time=12.77 min


Classifier inference:   0%|          | 0/3 [00:00<?, ?it/s]


Running config: pool=topk_noisy_or__topk=3__spans=5-10-15__stride=2__freeze=True


Epoch 1/3 | Step 0/767 | Loss 2.1349


Epoch 1/3 | Step 50/767 | Loss 0.6632


Epoch 1/3 | Step 100/767 | Loss 0.3761


Epoch 1/3 | Step 150/767 | Loss 0.1178


Epoch 1/3 | Step 200/767 | Loss 0.5322


Epoch 1/3 | Step 250/767 | Loss 0.2445


Epoch 1/3 | Step 300/767 | Loss 0.4893


Epoch 1/3 | Step 350/767 | Loss 0.2121


Epoch 1/3 | Step 400/767 | Loss 0.9310


Epoch 1/3 | Step 450/767 | Loss 0.4602


Epoch 1/3 | Step 500/767 | Loss 0.7254


Epoch 1/3 | Step 550/767 | Loss 0.6904


Epoch 1/3 | Step 600/767 | Loss 1.0938


Epoch 1/3 | Step 650/767 | Loss 0.0956


Epoch 1/3 | Step 700/767 | Loss 0.4036


Epoch 1/3 | Step 750/767 | Loss 0.4223


Epoch 1/3 finished | loss=0.7215 | val_f1=0.6473 | val_auc=0.7692 | time=12.77 min


Epoch 2/3 | Step 0/767 | Loss 1.2198


Epoch 2/3 | Step 50/767 | Loss 0.1667


Epoch 2/3 | Step 100/767 | Loss 0.4534


Epoch 2/3 | Step 150/767 | Loss 0.0242


Epoch 2/3 | Step 200/767 | Loss 0.4232


Epoch 2/3 | Step 250/767 | Loss 1.6795


Epoch 2/3 | Step 300/767 | Loss 0.4054


Epoch 2/3 | Step 350/767 | Loss 0.4103


Epoch 2/3 | Step 400/767 | Loss 0.0810


Epoch 2/3 | Step 450/767 | Loss 0.8527


Epoch 2/3 | Step 500/767 | Loss 0.8450


Epoch 2/3 | Step 550/767 | Loss 0.4545


Epoch 2/3 | Step 600/767 | Loss 1.0080


Epoch 2/3 | Step 650/767 | Loss 0.9706


Epoch 2/3 | Step 700/767 | Loss 0.0920


Epoch 2/3 | Step 750/767 | Loss 0.5736


Epoch 2/3 finished | loss=0.6945 | val_f1=0.6100 | val_auc=0.7744 | time=12.80 min


Epoch 3/3 | Step 0/767 | Loss 0.9628


Epoch 3/3 | Step 50/767 | Loss 0.0102


Epoch 3/3 | Step 100/767 | Loss 0.0066


Epoch 3/3 | Step 150/767 | Loss 1.0344


Epoch 3/3 | Step 200/767 | Loss 1.2308


Epoch 3/3 | Step 250/767 | Loss 0.0034


Epoch 3/3 | Step 300/767 | Loss 0.9784


Epoch 3/3 | Step 350/767 | Loss 1.1268


Epoch 3/3 | Step 400/767 | Loss 0.0625


Epoch 3/3 | Step 450/767 | Loss 2.0824


Epoch 3/3 | Step 500/767 | Loss 0.1373


Epoch 3/3 | Step 550/767 | Loss 4.3263


Epoch 3/3 | Step 600/767 | Loss 1.3280


Epoch 3/3 | Step 650/767 | Loss 1.0924


Epoch 3/3 | Step 700/767 | Loss 0.1800


Epoch 3/3 | Step 750/767 | Loss 0.4375


Epoch 3/3 finished | loss=0.6633 | val_f1=0.6042 | val_auc=0.7732 | time=12.79 min


Classifier inference:   0%|          | 0/3 [00:00<?, ?it/s]


Running config: pool=topk_noisy_or__topk=5__spans=5-10-15__stride=2__freeze=True


Epoch 1/3 | Step 0/767 | Loss 1.1126


Epoch 1/3 | Step 50/767 | Loss 1.0870


Epoch 1/3 | Step 100/767 | Loss 0.5422


Epoch 1/3 | Step 150/767 | Loss 1.2743


Epoch 1/3 | Step 200/767 | Loss 0.9206


Epoch 1/3 | Step 250/767 | Loss 0.1660


Epoch 1/3 | Step 300/767 | Loss 0.5411


Epoch 1/3 | Step 350/767 | Loss 0.0111


Epoch 1/3 | Step 400/767 | Loss 0.9154


Epoch 1/3 | Step 450/767 | Loss 1.3436


Epoch 1/3 | Step 500/767 | Loss 0.0181


Epoch 1/3 | Step 550/767 | Loss 2.0158


Epoch 1/3 | Step 600/767 | Loss 0.1131


Epoch 1/3 | Step 650/767 | Loss 1.0524


Epoch 1/3 | Step 700/767 | Loss 0.0651


Epoch 1/3 | Step 750/767 | Loss 0.0159


Epoch 1/3 finished | loss=0.7713 | val_f1=0.6193 | val_auc=0.7658 | time=12.79 min


Epoch 2/3 | Step 0/767 | Loss 1.1235


Epoch 2/3 | Step 50/767 | Loss 0.4821


Epoch 2/3 | Step 100/767 | Loss 0.0724


Epoch 2/3 | Step 150/767 | Loss 0.7640


Epoch 2/3 | Step 200/767 | Loss 0.1050


Epoch 2/3 | Step 250/767 | Loss 0.0080


Epoch 2/3 | Step 300/767 | Loss 0.0171


Epoch 2/3 | Step 350/767 | Loss 0.0943


Epoch 2/3 | Step 400/767 | Loss 0.1524


Epoch 2/3 | Step 450/767 | Loss 0.0720


Epoch 2/3 | Step 500/767 | Loss 3.7378


Epoch 2/3 | Step 550/767 | Loss 0.5878


Epoch 2/3 | Step 600/767 | Loss 0.2328


Epoch 2/3 | Step 650/767 | Loss 3.1735


Epoch 2/3 | Step 700/767 | Loss 0.1095


Epoch 2/3 | Step 750/767 | Loss 1.5923


Epoch 2/3 finished | loss=0.7635 | val_f1=0.5926 | val_auc=0.7651 | time=12.78 min


Epoch 3/3 | Step 0/767 | Loss 0.5266


Epoch 3/3 | Step 50/767 | Loss 0.5647


Epoch 3/3 | Step 100/767 | Loss 0.0944


Epoch 3/3 | Step 150/767 | Loss 3.2247


Epoch 3/3 | Step 200/767 | Loss 2.9405


Epoch 3/3 | Step 250/767 | Loss 0.9029


Epoch 3/3 | Step 300/767 | Loss 0.3877


Epoch 3/3 | Step 350/767 | Loss 0.7175


Epoch 3/3 | Step 400/767 | Loss 0.1688


Epoch 3/3 | Step 450/767 | Loss 0.2970


Epoch 3/3 | Step 500/767 | Loss 0.0243


Epoch 3/3 | Step 550/767 | Loss 0.0350


Epoch 3/3 | Step 600/767 | Loss 0.1622


Epoch 3/3 | Step 650/767 | Loss 0.1832


Epoch 3/3 | Step 700/767 | Loss 0.5286


Epoch 3/3 | Step 750/767 | Loss 1.9883


Epoch 3/3 finished | loss=0.6811 | val_f1=0.6114 | val_auc=0.7673 | time=12.79 min


Classifier inference:   0%|          | 0/3 [00:00<?, ?it/s]


Running config: pool=topk_noisy_or__topk=1__spans=5-10-15__stride=4__freeze=True


Epoch 1/3 | Step 0/767 | Loss 3.2204


Epoch 1/3 | Step 50/767 | Loss 0.9080


Epoch 1/3 | Step 100/767 | Loss 0.6915


Epoch 1/3 | Step 150/767 | Loss 0.9403


Epoch 1/3 | Step 200/767 | Loss 0.1765


Epoch 1/3 | Step 250/767 | Loss 0.1503


Epoch 1/3 | Step 300/767 | Loss 0.3878


Epoch 1/3 | Step 350/767 | Loss 1.3261


Epoch 1/3 | Step 400/767 | Loss 0.2052


Epoch 1/3 | Step 450/767 | Loss 0.1364


Epoch 1/3 | Step 500/767 | Loss 0.3668


Epoch 1/3 | Step 550/767 | Loss 0.6333


Epoch 1/3 | Step 600/767 | Loss 0.1257


Epoch 1/3 | Step 650/767 | Loss 1.6071


Epoch 1/3 | Step 700/767 | Loss 1.3634


Epoch 1/3 | Step 750/767 | Loss 0.9664


Epoch 1/3 finished | loss=0.7284 | val_f1=0.4740 | val_auc=0.7586 | time=10.15 min


Epoch 2/3 | Step 0/767 | Loss 0.0505


Epoch 2/3 | Step 50/767 | Loss 0.2303


Epoch 2/3 | Step 100/767 | Loss 0.9587


Epoch 2/3 | Step 150/767 | Loss 0.1920


Epoch 2/3 | Step 200/767 | Loss 1.1665


Epoch 2/3 | Step 250/767 | Loss 0.2461


Epoch 2/3 | Step 300/767 | Loss 0.0375


Epoch 2/3 | Step 350/767 | Loss 0.0130


Epoch 2/3 | Step 400/767 | Loss 0.0462


Epoch 2/3 | Step 450/767 | Loss 0.0735


Epoch 2/3 | Step 500/767 | Loss 0.5006


Epoch 2/3 | Step 550/767 | Loss 0.3672


Epoch 2/3 | Step 600/767 | Loss 1.3186


Epoch 2/3 | Step 650/767 | Loss 0.0169


Epoch 2/3 | Step 700/767 | Loss 0.6783


Epoch 2/3 | Step 750/767 | Loss 0.1106


Epoch 2/3 finished | loss=0.6894 | val_f1=0.6373 | val_auc=0.7668 | time=10.21 min


Epoch 3/3 | Step 0/767 | Loss 1.2748


Epoch 3/3 | Step 50/767 | Loss 0.0629


Epoch 3/3 | Step 100/767 | Loss 1.0342


Epoch 3/3 | Step 150/767 | Loss 1.5128


Epoch 3/3 | Step 200/767 | Loss 0.3784


Epoch 3/3 | Step 250/767 | Loss 1.4649


Epoch 3/3 | Step 300/767 | Loss 0.4863


Epoch 3/3 | Step 350/767 | Loss 1.7317


Epoch 3/3 | Step 400/767 | Loss 1.9738


Epoch 3/3 | Step 450/767 | Loss 0.0232


Epoch 3/3 | Step 500/767 | Loss 2.0317


Epoch 3/3 | Step 550/767 | Loss 0.0772


Epoch 3/3 | Step 600/767 | Loss 0.0351


Epoch 3/3 | Step 650/767 | Loss 0.4934


Epoch 3/3 | Step 700/767 | Loss 0.5244


Epoch 3/3 | Step 750/767 | Loss 0.2305


Epoch 3/3 finished | loss=0.7067 | val_f1=0.7064 | val_auc=0.7667 | time=10.09 min


Classifier inference:   0%|          | 0/3 [00:00<?, ?it/s]


Running config: pool=topk_noisy_or__topk=3__spans=5-10-15__stride=4__freeze=True


Epoch 1/3 | Step 0/767 | Loss 2.7567


Epoch 1/3 | Step 50/767 | Loss 1.4010


Epoch 1/3 | Step 100/767 | Loss 0.1181


Epoch 1/3 | Step 150/767 | Loss 0.2133


Epoch 1/3 | Step 200/767 | Loss 1.5948


Epoch 1/3 | Step 250/767 | Loss 0.5368


Epoch 1/3 | Step 300/767 | Loss 2.2430


Epoch 1/3 | Step 350/767 | Loss 1.1877


Epoch 1/3 | Step 400/767 | Loss 1.4687


Epoch 1/3 | Step 450/767 | Loss 0.5039


Epoch 1/3 | Step 500/767 | Loss 0.0922


Epoch 1/3 | Step 550/767 | Loss 0.3450


Epoch 1/3 | Step 600/767 | Loss 1.0071


Epoch 1/3 | Step 650/767 | Loss 1.2389


Epoch 1/3 | Step 700/767 | Loss 0.2128


Epoch 1/3 | Step 750/767 | Loss 1.1103


Epoch 1/3 finished | loss=0.7908 | val_f1=0.4588 | val_auc=0.7695 | time=10.10 min


Epoch 2/3 | Step 0/767 | Loss 0.2123


Epoch 2/3 | Step 50/767 | Loss 0.1890


Epoch 2/3 | Step 100/767 | Loss 0.1818


Epoch 2/3 | Step 150/767 | Loss 1.2652


Epoch 2/3 | Step 200/767 | Loss 1.3836


Epoch 2/3 | Step 250/767 | Loss 0.5844


Epoch 2/3 | Step 300/767 | Loss 0.1428


Epoch 2/3 | Step 350/767 | Loss 0.0611


Epoch 2/3 | Step 400/767 | Loss 1.0822


Epoch 2/3 | Step 450/767 | Loss 0.3592


Epoch 2/3 | Step 500/767 | Loss 0.9993


Epoch 2/3 | Step 550/767 | Loss 2.3489


Epoch 2/3 | Step 600/767 | Loss 2.3674


Epoch 2/3 | Step 650/767 | Loss 0.4230


Epoch 2/3 | Step 700/767 | Loss 0.0412


Epoch 2/3 | Step 750/767 | Loss 0.5152


Epoch 2/3 finished | loss=0.7191 | val_f1=0.5938 | val_auc=0.7740 | time=10.18 min


Epoch 3/3 | Step 0/767 | Loss 0.1154


Epoch 3/3 | Step 50/767 | Loss 0.2398


Epoch 3/3 | Step 100/767 | Loss 0.0025


Epoch 3/3 | Step 150/767 | Loss 0.1222


Epoch 3/3 | Step 200/767 | Loss 0.4426


Epoch 3/3 | Step 250/767 | Loss 0.1331


Epoch 3/3 | Step 300/767 | Loss 0.0084


Epoch 3/3 | Step 350/767 | Loss 1.0216


Epoch 3/3 | Step 400/767 | Loss 0.0479


Epoch 3/3 | Step 450/767 | Loss 0.3478


Epoch 3/3 | Step 500/767 | Loss 0.0021


Epoch 3/3 | Step 550/767 | Loss 0.0708


Epoch 3/3 | Step 600/767 | Loss 0.4863


Epoch 3/3 | Step 650/767 | Loss 0.2658


Epoch 3/3 | Step 700/767 | Loss 0.3253


Epoch 3/3 | Step 750/767 | Loss 0.5415


Epoch 3/3 finished | loss=0.6648 | val_f1=0.6162 | val_auc=0.7748 | time=10.09 min


Classifier inference:   0%|          | 0/3 [00:00<?, ?it/s]


Running config: pool=topk_noisy_or__topk=5__spans=5-10-15__stride=4__freeze=True


Epoch 1/3 | Step 0/767 | Loss 1.1203


Epoch 1/3 | Step 50/767 | Loss 0.5401


Epoch 1/3 | Step 100/767 | Loss 0.4797


Epoch 1/3 | Step 150/767 | Loss 0.4708


Epoch 1/3 | Step 200/767 | Loss 0.2530


Epoch 1/3 | Step 250/767 | Loss 0.1501


Epoch 1/3 | Step 300/767 | Loss 0.0560


Epoch 1/3 | Step 350/767 | Loss 0.0771


Epoch 1/3 | Step 400/767 | Loss 0.1028


Epoch 1/3 | Step 450/767 | Loss 0.2724


Epoch 1/3 | Step 500/767 | Loss 1.7590


Epoch 1/3 | Step 550/767 | Loss 1.8569


Epoch 1/3 | Step 600/767 | Loss 1.4609


Epoch 1/3 | Step 650/767 | Loss 0.0375


Epoch 1/3 | Step 700/767 | Loss 0.1533


Epoch 1/3 | Step 750/767 | Loss 0.3637


Epoch 1/3 finished | loss=0.7807 | val_f1=0.5745 | val_auc=0.7699 | time=10.10 min


Epoch 2/3 | Step 0/767 | Loss 0.0405


Epoch 2/3 | Step 50/767 | Loss 0.3246


Epoch 2/3 | Step 100/767 | Loss 1.6267


Epoch 2/3 | Step 150/767 | Loss 1.4057


Epoch 2/3 | Step 200/767 | Loss 0.2803


Epoch 2/3 | Step 250/767 | Loss 0.1321


Epoch 2/3 | Step 300/767 | Loss 2.2633


Epoch 2/3 | Step 350/767 | Loss 0.2157


Epoch 2/3 | Step 400/767 | Loss 0.6371


Epoch 2/3 | Step 450/767 | Loss 0.2162


Epoch 2/3 | Step 500/767 | Loss 0.0980


Epoch 2/3 | Step 550/767 | Loss 0.0113


Epoch 2/3 | Step 600/767 | Loss 0.0000


Epoch 2/3 | Step 650/767 | Loss 0.0720


Epoch 2/3 | Step 700/767 | Loss 0.1853


Epoch 2/3 | Step 750/767 | Loss 0.0024


Epoch 2/3 finished | loss=0.7478 | val_f1=0.6502 | val_auc=0.7735 | time=10.07 min


Epoch 3/3 | Step 0/767 | Loss 0.4931


Epoch 3/3 | Step 50/767 | Loss 0.0517


Epoch 3/3 | Step 100/767 | Loss 0.4937


Epoch 3/3 | Step 150/767 | Loss 0.3880


Epoch 3/3 | Step 200/767 | Loss 0.0375


Epoch 3/3 | Step 250/767 | Loss 0.4404


Epoch 3/3 | Step 300/767 | Loss 0.0870


Epoch 3/3 | Step 350/767 | Loss 0.9819


Epoch 3/3 | Step 400/767 | Loss 0.0985


Epoch 3/3 | Step 450/767 | Loss 0.3448


Epoch 3/3 | Step 500/767 | Loss 0.1775


Epoch 3/3 | Step 550/767 | Loss 0.1824


Epoch 3/3 | Step 600/767 | Loss 0.3139


Epoch 3/3 | Step 650/767 | Loss 0.0690


Epoch 3/3 | Step 700/767 | Loss 0.2691


Epoch 3/3 | Step 750/767 | Loss 0.0875


Epoch 3/3 finished | loss=0.6739 | val_f1=0.6368 | val_auc=0.7767 | time=10.25 min


Classifier inference:   0%|          | 0/3 [00:00<?, ?it/s]


Running config: pool=topk_noisy_or__topk=1__spans=10-15-20__stride=2__freeze=True


Epoch 1/3 | Step 0/767 | Loss 3.1883


Epoch 1/3 | Step 50/767 | Loss 1.3190


Epoch 1/3 | Step 100/767 | Loss 0.4939


Epoch 1/3 | Step 150/767 | Loss 0.8209


Epoch 1/3 | Step 200/767 | Loss 0.8072


Epoch 1/3 | Step 250/767 | Loss 0.3976


Epoch 1/3 | Step 300/767 | Loss 1.0747


Epoch 1/3 | Step 350/767 | Loss 3.1996


Epoch 1/3 | Step 400/767 | Loss 0.5454


Epoch 1/3 | Step 450/767 | Loss 0.6477


Epoch 1/3 | Step 500/767 | Loss 0.2904


Epoch 1/3 | Step 550/767 | Loss 0.5166


Epoch 1/3 | Step 600/767 | Loss 1.2286


Epoch 1/3 | Step 650/767 | Loss 0.0656


Epoch 1/3 | Step 700/767 | Loss 1.1820


Epoch 1/3 | Step 750/767 | Loss 0.7520


Epoch 1/3 finished | loss=0.6966 | val_f1=0.7531 | val_auc=0.7840 | time=12.45 min


Epoch 2/3 | Step 0/767 | Loss 0.7836


Epoch 2/3 | Step 50/767 | Loss 1.8363


Epoch 2/3 | Step 100/767 | Loss 0.4312


Epoch 2/3 | Step 150/767 | Loss 0.9788


Epoch 2/3 | Step 200/767 | Loss 1.3756


Epoch 2/3 | Step 250/767 | Loss 0.2866


Epoch 2/3 | Step 300/767 | Loss 0.8572


Epoch 2/3 | Step 350/767 | Loss 0.0387


Epoch 2/3 | Step 400/767 | Loss 0.0537


Epoch 2/3 | Step 450/767 | Loss 0.3357


Epoch 2/3 | Step 500/767 | Loss 0.0809


Epoch 2/3 | Step 550/767 | Loss 0.9285


Epoch 2/3 | Step 600/767 | Loss 0.0256


Epoch 2/3 | Step 650/767 | Loss 0.3039


Epoch 2/3 | Step 700/767 | Loss 0.1356


Epoch 2/3 | Step 750/767 | Loss 0.8639


Epoch 2/3 finished | loss=0.6796 | val_f1=0.6218 | val_auc=0.7702 | time=12.64 min


Epoch 3/3 | Step 0/767 | Loss 1.3621


Epoch 3/3 | Step 50/767 | Loss 1.6715


Epoch 3/3 | Step 100/767 | Loss 0.1263


Epoch 3/3 | Step 150/767 | Loss 0.0100


Epoch 3/3 | Step 200/767 | Loss 2.2649


Epoch 3/3 | Step 250/767 | Loss 0.2134


Epoch 3/3 | Step 300/767 | Loss 0.1727


Epoch 3/3 | Step 350/767 | Loss 0.4791


Epoch 3/3 | Step 400/767 | Loss 0.3027


Epoch 3/3 | Step 450/767 | Loss 1.0412


Epoch 3/3 | Step 500/767 | Loss 0.0271


Epoch 3/3 | Step 550/767 | Loss 2.7744


Epoch 3/3 | Step 600/767 | Loss 1.3531


Epoch 3/3 | Step 650/767 | Loss 0.2112


Epoch 3/3 | Step 700/767 | Loss 0.9146


Epoch 3/3 | Step 750/767 | Loss 0.8467


Epoch 3/3 finished | loss=0.6737 | val_f1=0.6766 | val_auc=0.7791 | time=12.60 min


Classifier inference:   0%|          | 0/3 [00:00<?, ?it/s]


Running config: pool=topk_noisy_or__topk=3__spans=10-15-20__stride=2__freeze=True


Epoch 1/3 | Step 0/767 | Loss 2.8439


Epoch 1/3 | Step 50/767 | Loss 0.6311


Epoch 1/3 | Step 100/767 | Loss 0.5330


Epoch 1/3 | Step 150/767 | Loss 1.0939


Epoch 1/3 | Step 200/767 | Loss 0.3875


Epoch 1/3 | Step 250/767 | Loss 2.0143


Epoch 1/3 | Step 300/767 | Loss 1.8531


Epoch 1/3 | Step 350/767 | Loss 0.2298


Epoch 1/3 | Step 400/767 | Loss 0.4825


Epoch 1/3 | Step 450/767 | Loss 0.0006


Epoch 1/3 | Step 500/767 | Loss 0.0132


Epoch 1/3 | Step 550/767 | Loss 2.3560


Epoch 1/3 | Step 600/767 | Loss 0.0712


Epoch 1/3 | Step 650/767 | Loss 2.3691


Epoch 1/3 | Step 700/767 | Loss 0.9120


Epoch 1/3 | Step 750/767 | Loss 0.3485


Epoch 1/3 finished | loss=0.7127 | val_f1=0.5116 | val_auc=0.7712 | time=12.57 min


Epoch 2/3 | Step 0/767 | Loss 0.0461


Epoch 2/3 | Step 50/767 | Loss 3.0132


Epoch 2/3 | Step 100/767 | Loss 0.9697


Epoch 2/3 | Step 150/767 | Loss 2.7156


Epoch 2/3 | Step 200/767 | Loss 0.2740


Epoch 2/3 | Step 250/767 | Loss 0.0658


Epoch 2/3 | Step 300/767 | Loss 0.0329


Epoch 2/3 | Step 350/767 | Loss 0.0274


Epoch 2/3 | Step 400/767 | Loss 1.3634


Epoch 2/3 | Step 450/767 | Loss 0.4849


Epoch 2/3 | Step 500/767 | Loss 0.9790


Epoch 2/3 | Step 550/767 | Loss 0.3603


Epoch 2/3 | Step 600/767 | Loss 0.8104


Epoch 2/3 | Step 650/767 | Loss 0.0750


Epoch 2/3 | Step 700/767 | Loss 0.2561


Epoch 2/3 | Step 750/767 | Loss 0.2030


Epoch 2/3 finished | loss=0.6980 | val_f1=0.5882 | val_auc=0.7789 | time=12.35 min


Epoch 3/3 | Step 0/767 | Loss 1.7878


Epoch 3/3 | Step 50/767 | Loss 0.0592


Epoch 3/3 | Step 100/767 | Loss 0.6326


Epoch 3/3 | Step 150/767 | Loss 0.0220


Epoch 3/3 | Step 200/767 | Loss 2.6235


Epoch 3/3 | Step 250/767 | Loss 0.4833


Epoch 3/3 | Step 300/767 | Loss 2.4499


Epoch 3/3 | Step 350/767 | Loss 0.1880


Epoch 3/3 | Step 400/767 | Loss 0.2094


Epoch 3/3 | Step 450/767 | Loss 0.8902


Epoch 3/3 | Step 500/767 | Loss 0.0118


Epoch 3/3 | Step 550/767 | Loss 0.5290


Epoch 3/3 | Step 600/767 | Loss 0.0148


Epoch 3/3 | Step 650/767 | Loss 0.4988


Epoch 3/3 | Step 700/767 | Loss 0.0880


Epoch 3/3 | Step 750/767 | Loss 0.3972


Epoch 3/3 finished | loss=0.6622 | val_f1=0.5882 | val_auc=0.7783 | time=12.31 min


Classifier inference:   0%|          | 0/3 [00:00<?, ?it/s]


Running config: pool=topk_noisy_or__topk=5__spans=10-15-20__stride=2__freeze=True


Epoch 1/3 | Step 0/767 | Loss 0.9563


Epoch 1/3 | Step 50/767 | Loss 0.9291


Epoch 1/3 | Step 100/767 | Loss 0.2006


Epoch 1/3 | Step 150/767 | Loss 0.3177


Epoch 1/3 | Step 200/767 | Loss 0.0251


Epoch 1/3 | Step 250/767 | Loss 0.3179


Epoch 1/3 | Step 300/767 | Loss 0.0028


Epoch 1/3 | Step 350/767 | Loss 0.2072


Epoch 1/3 | Step 400/767 | Loss 0.0139


Epoch 1/3 | Step 450/767 | Loss 0.0128


Epoch 1/3 | Step 500/767 | Loss 0.0000


Epoch 1/3 | Step 550/767 | Loss 0.1850


Epoch 1/3 | Step 600/767 | Loss 0.5560


Epoch 1/3 | Step 650/767 | Loss 0.5673


Epoch 1/3 | Step 700/767 | Loss 0.1068


Epoch 1/3 | Step 750/767 | Loss 0.0052


Epoch 1/3 finished | loss=0.7346 | val_f1=0.6535 | val_auc=0.7749 | time=12.33 min


Epoch 2/3 | Step 0/767 | Loss 0.5769


Epoch 2/3 | Step 50/767 | Loss 1.0997


Epoch 2/3 | Step 100/767 | Loss 2.1584


Epoch 2/3 | Step 150/767 | Loss 0.3406


Epoch 2/3 | Step 200/767 | Loss 0.1159


Epoch 2/3 | Step 250/767 | Loss 0.0367


Epoch 2/3 | Step 300/767 | Loss 0.1061


Epoch 2/3 | Step 350/767 | Loss 0.0388


Epoch 2/3 | Step 400/767 | Loss 0.0927


Epoch 2/3 | Step 450/767 | Loss 0.4783


Epoch 2/3 | Step 500/767 | Loss 0.4682


Epoch 2/3 | Step 550/767 | Loss 0.6035


Epoch 2/3 | Step 600/767 | Loss 0.2974


Epoch 2/3 | Step 650/767 | Loss 2.7709


Epoch 2/3 | Step 700/767 | Loss 0.5405


Epoch 2/3 | Step 750/767 | Loss 1.6752


Epoch 2/3 finished | loss=0.7438 | val_f1=0.7511 | val_auc=0.7806 | time=12.33 min


Epoch 3/3 | Step 0/767 | Loss 0.3312


Epoch 3/3 | Step 50/767 | Loss 0.6733


Epoch 3/3 | Step 100/767 | Loss 3.5509


Epoch 3/3 | Step 150/767 | Loss 0.0244


Epoch 3/3 | Step 200/767 | Loss 0.0335


Epoch 3/3 | Step 250/767 | Loss 0.1870


Epoch 3/3 | Step 300/767 | Loss 0.4556


Epoch 3/3 | Step 350/767 | Loss 0.3443


Epoch 3/3 | Step 400/767 | Loss 1.0018


Epoch 3/3 | Step 450/767 | Loss 0.0781


Epoch 3/3 | Step 500/767 | Loss 0.3201


Epoch 3/3 | Step 550/767 | Loss 0.4239


Epoch 3/3 | Step 600/767 | Loss 1.8126


Epoch 3/3 | Step 650/767 | Loss 0.3324


Epoch 3/3 | Step 700/767 | Loss 1.7916


Epoch 3/3 | Step 750/767 | Loss 0.0380


Epoch 3/3 finished | loss=0.6881 | val_f1=0.6178 | val_auc=0.7749 | time=12.32 min


Classifier inference:   0%|          | 0/3 [00:00<?, ?it/s]


Running config: pool=topk_noisy_or__topk=1__spans=10-15-20__stride=4__freeze=True


Epoch 1/3 | Step 0/767 | Loss 1.7394


Epoch 1/3 | Step 50/767 | Loss 1.6736


Epoch 1/3 | Step 100/767 | Loss 0.8291


Epoch 1/3 | Step 150/767 | Loss 0.3725


Epoch 1/3 | Step 200/767 | Loss 0.4857


Epoch 1/3 | Step 250/767 | Loss 2.2542


Epoch 1/3 | Step 300/767 | Loss 0.5571


Epoch 1/3 | Step 350/767 | Loss 0.1262


Epoch 1/3 | Step 400/767 | Loss 0.3602


Epoch 1/3 | Step 450/767 | Loss 2.1546


Epoch 1/3 | Step 500/767 | Loss 1.0375


Epoch 1/3 | Step 550/767 | Loss 2.2628


Epoch 1/3 | Step 600/767 | Loss 0.4109


Epoch 1/3 | Step 650/767 | Loss 1.9178


Epoch 1/3 | Step 700/767 | Loss 1.9122


Epoch 1/3 | Step 750/767 | Loss 0.0278


Epoch 1/3 finished | loss=0.7157 | val_f1=0.7313 | val_auc=0.7839 | time=9.57 min


Epoch 2/3 | Step 0/767 | Loss 0.6796


Epoch 2/3 | Step 50/767 | Loss 0.8491


Epoch 2/3 | Step 100/767 | Loss 0.1928


Epoch 2/3 | Step 150/767 | Loss 0.0741


Epoch 2/3 | Step 200/767 | Loss 0.0085


Epoch 2/3 | Step 250/767 | Loss 0.3241


Epoch 2/3 | Step 300/767 | Loss 0.1779


Epoch 2/3 | Step 350/767 | Loss 0.0072


Epoch 2/3 | Step 400/767 | Loss 1.3226


Epoch 2/3 | Step 450/767 | Loss 0.5526


Epoch 2/3 | Step 500/767 | Loss 0.6104


Epoch 2/3 | Step 550/767 | Loss 0.0574


Epoch 2/3 | Step 600/767 | Loss 2.1019


Epoch 2/3 | Step 650/767 | Loss 0.4231


Epoch 2/3 | Step 700/767 | Loss 0.2719


Epoch 2/3 | Step 750/767 | Loss 0.0863


Epoch 2/3 finished | loss=0.6916 | val_f1=0.5444 | val_auc=0.7659 | time=9.56 min


Epoch 3/3 | Step 0/767 | Loss 1.4440


Epoch 3/3 | Step 50/767 | Loss 0.6817


Epoch 3/3 | Step 100/767 | Loss 0.0420


Epoch 3/3 | Step 150/767 | Loss 1.5508


Epoch 3/3 | Step 200/767 | Loss 1.1899


Epoch 3/3 | Step 250/767 | Loss 1.6611


Epoch 3/3 | Step 300/767 | Loss 1.6596


Epoch 3/3 | Step 350/767 | Loss 1.4761


Epoch 3/3 | Step 400/767 | Loss 0.0131


Epoch 3/3 | Step 450/767 | Loss 1.6511


Epoch 3/3 | Step 500/767 | Loss 0.0420


Epoch 3/3 | Step 550/767 | Loss 0.2832


Epoch 3/3 | Step 600/767 | Loss 2.0166


Epoch 3/3 | Step 650/767 | Loss 0.1647


Epoch 3/3 | Step 700/767 | Loss 0.5190


Epoch 3/3 | Step 750/767 | Loss 0.0981


Epoch 3/3 finished | loss=0.6636 | val_f1=0.6667 | val_auc=0.7742 | time=9.57 min


Classifier inference:   0%|          | 0/3 [00:00<?, ?it/s]


Running config: pool=topk_noisy_or__topk=3__spans=10-15-20__stride=4__freeze=True


Epoch 1/3 | Step 0/767 | Loss 2.4344


Epoch 1/3 | Step 50/767 | Loss 0.7462


Epoch 1/3 | Step 100/767 | Loss 0.4872


Epoch 1/3 | Step 150/767 | Loss 0.6832


Epoch 1/3 | Step 200/767 | Loss 0.3341


Epoch 1/3 | Step 250/767 | Loss 0.2289


Epoch 1/3 | Step 300/767 | Loss 0.9675


Epoch 1/3 | Step 350/767 | Loss 0.2002


Epoch 1/3 | Step 400/767 | Loss 0.8580


Epoch 1/3 | Step 450/767 | Loss 0.1957


Epoch 1/3 | Step 500/767 | Loss 0.8372


Epoch 1/3 | Step 550/767 | Loss 2.5325


Epoch 1/3 | Step 600/767 | Loss 4.9723


Epoch 1/3 | Step 650/767 | Loss 0.0073


Epoch 1/3 | Step 700/767 | Loss 0.1050


Epoch 1/3 | Step 750/767 | Loss 0.7333


Epoch 1/3 finished | loss=0.7151 | val_f1=0.5222 | val_auc=0.7770 | time=9.58 min


Epoch 2/3 | Step 0/767 | Loss 0.7909


Epoch 2/3 | Step 50/767 | Loss 0.2531


Epoch 2/3 | Step 100/767 | Loss 1.9133


Epoch 2/3 | Step 150/767 | Loss 2.3969


Epoch 2/3 | Step 200/767 | Loss 0.1677


Epoch 2/3 | Step 250/767 | Loss 0.0025


Epoch 2/3 | Step 300/767 | Loss 0.0242


Epoch 2/3 | Step 350/767 | Loss 0.2419


Epoch 2/3 | Step 400/767 | Loss 2.0743


Epoch 2/3 | Step 450/767 | Loss 0.0012


Epoch 2/3 | Step 500/767 | Loss 0.0010


Epoch 2/3 | Step 550/767 | Loss 1.0751


Epoch 2/3 | Step 600/767 | Loss 0.3234


Epoch 2/3 | Step 650/767 | Loss 0.3932


Epoch 2/3 | Step 700/767 | Loss 0.3324


Epoch 2/3 | Step 750/767 | Loss 0.5111


Epoch 2/3 finished | loss=0.7390 | val_f1=0.7097 | val_auc=0.7844 | time=9.55 min


Epoch 3/3 | Step 0/767 | Loss 0.7067


Epoch 3/3 | Step 50/767 | Loss 0.2618


Epoch 3/3 | Step 100/767 | Loss 0.4494


Epoch 3/3 | Step 150/767 | Loss 0.1711


Epoch 3/3 | Step 200/767 | Loss 0.6262


Epoch 3/3 | Step 250/767 | Loss 0.8374


Epoch 3/3 | Step 300/767 | Loss 0.4034


Epoch 3/3 | Step 350/767 | Loss 1.5263


Epoch 3/3 | Step 400/767 | Loss 3.1204


Epoch 3/3 | Step 450/767 | Loss 0.0012


Epoch 3/3 | Step 500/767 | Loss 2.2720


Epoch 3/3 | Step 550/767 | Loss 1.0129


Epoch 3/3 | Step 600/767 | Loss 0.0134


Epoch 3/3 | Step 650/767 | Loss 1.3052


Epoch 3/3 | Step 700/767 | Loss 0.0022


Epoch 3/3 | Step 750/767 | Loss 1.0551


Epoch 3/3 finished | loss=0.6917 | val_f1=0.7109 | val_auc=0.7819 | time=9.56 min


Classifier inference:   0%|          | 0/3 [00:00<?, ?it/s]


Running config: pool=topk_noisy_or__topk=5__spans=10-15-20__stride=4__freeze=True


Epoch 1/3 | Step 0/767 | Loss 1.9298


Epoch 1/3 | Step 50/767 | Loss 0.9895


Epoch 1/3 | Step 100/767 | Loss 0.3500


Epoch 1/3 | Step 150/767 | Loss 0.9621


Epoch 1/3 | Step 200/767 | Loss 0.5334


Epoch 1/3 | Step 250/767 | Loss 0.0036


Epoch 1/3 | Step 300/767 | Loss 0.0411


Epoch 1/3 | Step 350/767 | Loss 0.3023


Epoch 1/3 | Step 400/767 | Loss 0.0134


Epoch 1/3 | Step 450/767 | Loss 0.8548


Epoch 1/3 | Step 500/767 | Loss 3.3910


Epoch 1/3 | Step 550/767 | Loss 0.0352


Epoch 1/3 | Step 600/767 | Loss 1.6268


Epoch 1/3 | Step 650/767 | Loss 0.0669


Epoch 1/3 | Step 700/767 | Loss 1.2985


Epoch 1/3 | Step 750/767 | Loss 0.0054


Epoch 1/3 finished | loss=0.7207 | val_f1=0.7376 | val_auc=0.7799 | time=9.58 min


Epoch 2/3 | Step 0/767 | Loss 8.0340


Epoch 2/3 | Step 50/767 | Loss 1.2139


Epoch 2/3 | Step 100/767 | Loss 0.0373


Epoch 2/3 | Step 150/767 | Loss 2.6150


Epoch 2/3 | Step 200/767 | Loss 0.0291


Epoch 2/3 | Step 250/767 | Loss 0.0020


Epoch 2/3 | Step 300/767 | Loss 1.0159


Epoch 2/3 | Step 350/767 | Loss 3.3280


Epoch 2/3 | Step 400/767 | Loss 0.4693


Epoch 2/3 | Step 450/767 | Loss 0.0137


Epoch 2/3 | Step 500/767 | Loss 4.0780


Epoch 2/3 | Step 550/767 | Loss 0.3716


Epoch 2/3 | Step 600/767 | Loss 0.0856


Epoch 2/3 | Step 650/767 | Loss 1.2126


Epoch 2/3 | Step 700/767 | Loss 0.0703


Epoch 2/3 | Step 750/767 | Loss 0.6010


Epoch 2/3 finished | loss=0.7711 | val_f1=0.5730 | val_auc=0.7725 | time=9.57 min


Epoch 3/3 | Step 0/767 | Loss 0.3344


Epoch 3/3 | Step 50/767 | Loss 0.2534


Epoch 3/3 | Step 100/767 | Loss 0.4585


Epoch 3/3 | Step 150/767 | Loss 0.1006


Epoch 3/3 | Step 200/767 | Loss 0.0111


Epoch 3/3 | Step 250/767 | Loss 5.4334


Epoch 3/3 | Step 300/767 | Loss 0.3967


Epoch 3/3 | Step 350/767 | Loss 1.9215


Epoch 3/3 | Step 400/767 | Loss 0.0068


Epoch 3/3 | Step 450/767 | Loss 0.4003


Epoch 3/3 | Step 500/767 | Loss 0.5422


Epoch 3/3 | Step 550/767 | Loss 1.2538


Epoch 3/3 | Step 600/767 | Loss 0.0177


Epoch 3/3 | Step 650/767 | Loss 5.1375


Epoch 3/3 | Step 700/767 | Loss 1.0334


Epoch 3/3 | Step 750/767 | Loss 1.4991


Epoch 3/3 finished | loss=0.6732 | val_f1=0.6860 | val_auc=0.7814 | time=9.58 min


Classifier inference:   0%|          | 0/3 [00:00<?, ?it/s]


Running config: pool=topk_mean__topk=1__spans=3-5-8__stride=2__freeze=True


Epoch 1/3 | Step 0/767 | Loss 3.3574


Epoch 1/3 | Step 50/767 | Loss 0.1766


Epoch 1/3 | Step 100/767 | Loss 1.1693


Epoch 1/3 | Step 150/767 | Loss 0.8171


Epoch 1/3 | Step 200/767 | Loss 1.3980


Epoch 1/3 | Step 250/767 | Loss 0.1741


Epoch 1/3 | Step 300/767 | Loss 0.5030


Epoch 1/3 | Step 350/767 | Loss 1.5776


Epoch 1/3 | Step 400/767 | Loss 0.8774


Epoch 1/3 | Step 450/767 | Loss 0.6126


Epoch 1/3 | Step 500/767 | Loss 0.3220


Epoch 1/3 | Step 550/767 | Loss 0.8934


Epoch 1/3 | Step 600/767 | Loss 0.0477


Epoch 1/3 | Step 650/767 | Loss 0.3093


Epoch 1/3 | Step 700/767 | Loss 0.5214


Epoch 1/3 | Step 750/767 | Loss 0.4561


Epoch 1/3 finished | loss=0.7891 | val_f1=0.7048 | val_auc=0.7386 | time=13.18 min


Epoch 2/3 | Step 0/767 | Loss 0.1128


Epoch 2/3 | Step 50/767 | Loss 0.0516


Epoch 2/3 | Step 100/767 | Loss 0.4525


Epoch 2/3 | Step 150/767 | Loss 0.3126


Epoch 2/3 | Step 200/767 | Loss 0.4442


Epoch 2/3 | Step 250/767 | Loss 0.7339


Epoch 2/3 | Step 300/767 | Loss 0.5066


Epoch 2/3 | Step 350/767 | Loss 0.7911


Epoch 2/3 | Step 400/767 | Loss 2.3350


Epoch 2/3 | Step 450/767 | Loss 0.0648


Epoch 2/3 | Step 500/767 | Loss 1.1523


Epoch 2/3 | Step 550/767 | Loss 1.7814


Epoch 2/3 | Step 600/767 | Loss 0.7400


Epoch 2/3 | Step 650/767 | Loss 0.1632


Epoch 2/3 | Step 700/767 | Loss 0.9226


Epoch 2/3 | Step 750/767 | Loss 0.2819


Epoch 2/3 finished | loss=0.7032 | val_f1=0.5567 | val_auc=0.7376 | time=13.17 min


Epoch 3/3 | Step 0/767 | Loss 0.6837


Epoch 3/3 | Step 50/767 | Loss 0.2540


Epoch 3/3 | Step 100/767 | Loss 0.0414


Epoch 3/3 | Step 150/767 | Loss 0.5329


Epoch 3/3 | Step 200/767 | Loss 1.3125


Epoch 3/3 | Step 250/767 | Loss 0.8617


Epoch 3/3 | Step 300/767 | Loss 0.1053


Epoch 3/3 | Step 350/767 | Loss 0.2120


Epoch 3/3 | Step 400/767 | Loss 0.0375


Epoch 3/3 | Step 450/767 | Loss 0.1436


Epoch 3/3 | Step 500/767 | Loss 0.1281


Epoch 3/3 | Step 550/767 | Loss 1.8113


Epoch 3/3 | Step 600/767 | Loss 1.6594


Epoch 3/3 | Step 650/767 | Loss 0.3812


Epoch 3/3 | Step 700/767 | Loss 1.6819


Epoch 3/3 | Step 750/767 | Loss 0.1285


Epoch 3/3 finished | loss=0.6891 | val_f1=0.5426 | val_auc=0.7391 | time=13.17 min


Classifier inference:   0%|          | 0/3 [00:00<?, ?it/s]


Running config: pool=topk_mean__topk=3__spans=3-5-8__stride=2__freeze=True


Epoch 1/3 | Step 0/767 | Loss 1.8314


Epoch 1/3 | Step 50/767 | Loss 2.1593


Epoch 1/3 | Step 100/767 | Loss 0.7930


Epoch 1/3 | Step 150/767 | Loss 1.2100


Epoch 1/3 | Step 200/767 | Loss 0.5460


Epoch 1/3 | Step 250/767 | Loss 1.3097


Epoch 1/3 | Step 300/767 | Loss 0.7741


Epoch 1/3 | Step 350/767 | Loss 1.0442


Epoch 1/3 | Step 400/767 | Loss 1.1540


Epoch 1/3 | Step 450/767 | Loss 0.0542


Epoch 1/3 | Step 500/767 | Loss 0.8773


Epoch 1/3 | Step 550/767 | Loss 0.2352


Epoch 1/3 | Step 600/767 | Loss 1.0553


Epoch 1/3 | Step 650/767 | Loss 0.4563


Epoch 1/3 | Step 700/767 | Loss 0.2910


Epoch 1/3 | Step 750/767 | Loss 0.2104


Epoch 1/3 finished | loss=0.7566 | val_f1=0.6698 | val_auc=0.7461 | time=13.20 min


Epoch 2/3 | Step 0/767 | Loss 1.7349


Epoch 2/3 | Step 50/767 | Loss 0.1928


Epoch 2/3 | Step 100/767 | Loss 1.0272


Epoch 2/3 | Step 150/767 | Loss 0.3916


Epoch 2/3 | Step 200/767 | Loss 1.2677


Epoch 2/3 | Step 250/767 | Loss 0.3276


Epoch 2/3 | Step 300/767 | Loss 0.4445


Epoch 2/3 | Step 350/767 | Loss 2.3459


Epoch 2/3 | Step 400/767 | Loss 0.1920


Epoch 2/3 | Step 450/767 | Loss 2.0441


Epoch 2/3 | Step 500/767 | Loss 2.9574


Epoch 2/3 | Step 550/767 | Loss 1.3572


Epoch 2/3 | Step 600/767 | Loss 0.7093


Epoch 2/3 | Step 650/767 | Loss 1.7438


Epoch 2/3 | Step 700/767 | Loss 0.7547


Epoch 2/3 | Step 750/767 | Loss 0.4307


Epoch 2/3 finished | loss=0.6985 | val_f1=0.5000 | val_auc=0.7426 | time=13.21 min


Epoch 3/3 | Step 0/767 | Loss 0.5357


Epoch 3/3 | Step 50/767 | Loss 0.0250


Epoch 3/3 | Step 100/767 | Loss 0.7282


Epoch 3/3 | Step 150/767 | Loss 1.6982


Epoch 3/3 | Step 200/767 | Loss 0.1371


Epoch 3/3 | Step 250/767 | Loss 0.0811


Epoch 3/3 | Step 300/767 | Loss 0.2288


Epoch 3/3 | Step 350/767 | Loss 0.1720


Epoch 3/3 | Step 400/767 | Loss 0.1304


Epoch 3/3 | Step 450/767 | Loss 0.4558


Epoch 3/3 | Step 500/767 | Loss 0.1380


Epoch 3/3 | Step 550/767 | Loss 0.4608


Epoch 3/3 | Step 600/767 | Loss 1.8307


Epoch 3/3 | Step 650/767 | Loss 0.0184


Epoch 3/3 | Step 700/767 | Loss 0.0525


Epoch 3/3 | Step 750/767 | Loss 0.0714


Epoch 3/3 finished | loss=0.6745 | val_f1=0.5729 | val_auc=0.7454 | time=13.20 min


Classifier inference:   0%|          | 0/3 [00:00<?, ?it/s]


Running config: pool=topk_mean__topk=5__spans=3-5-8__stride=2__freeze=True


Epoch 1/3 | Step 0/767 | Loss 1.8341


Epoch 1/3 | Step 50/767 | Loss 1.0149


Epoch 1/3 | Step 100/767 | Loss 0.4634


Epoch 1/3 | Step 150/767 | Loss 0.6830


Epoch 1/3 | Step 200/767 | Loss 0.8357


Epoch 1/3 | Step 250/767 | Loss 1.7012


Epoch 1/3 | Step 300/767 | Loss 2.0225


Epoch 1/3 | Step 350/767 | Loss 0.1790


Epoch 1/3 | Step 400/767 | Loss 0.0226


Epoch 1/3 | Step 450/767 | Loss 0.2495


Epoch 1/3 | Step 500/767 | Loss 0.2221


Epoch 1/3 | Step 550/767 | Loss 0.0477


Epoch 1/3 | Step 600/767 | Loss 0.9628


Epoch 1/3 | Step 650/767 | Loss 1.3203


Epoch 1/3 | Step 700/767 | Loss 0.0678


Epoch 1/3 | Step 750/767 | Loss 0.8948


Epoch 1/3 finished | loss=0.7717 | val_f1=0.5246 | val_auc=0.7483 | time=13.24 min


Epoch 2/3 | Step 0/767 | Loss 0.0817


Epoch 2/3 | Step 50/767 | Loss 0.0480


Epoch 2/3 | Step 100/767 | Loss 0.4201


Epoch 2/3 | Step 150/767 | Loss 0.0166


Epoch 2/3 | Step 200/767 | Loss 0.1743


Epoch 2/3 | Step 250/767 | Loss 0.1705


Epoch 2/3 | Step 300/767 | Loss 0.6516


Epoch 2/3 | Step 350/767 | Loss 1.1671


Epoch 2/3 | Step 400/767 | Loss 0.7097


Epoch 2/3 | Step 450/767 | Loss 0.6362


Epoch 2/3 | Step 500/767 | Loss 1.6470


Epoch 2/3 | Step 550/767 | Loss 0.5948


Epoch 2/3 | Step 600/767 | Loss 0.0716


Epoch 2/3 | Step 650/767 | Loss 1.9708


Epoch 2/3 | Step 700/767 | Loss 1.3758


Epoch 2/3 | Step 750/767 | Loss 0.0885


Epoch 2/3 finished | loss=0.7204 | val_f1=0.6818 | val_auc=0.7500 | time=13.16 min


Epoch 3/3 | Step 0/767 | Loss 1.0761


Epoch 3/3 | Step 50/767 | Loss 0.7268


Epoch 3/3 | Step 100/767 | Loss 0.2550


Epoch 3/3 | Step 150/767 | Loss 0.7158


Epoch 3/3 | Step 200/767 | Loss 0.2052


Epoch 3/3 | Step 250/767 | Loss 0.1328


Epoch 3/3 | Step 300/767 | Loss 1.3387


Epoch 3/3 | Step 350/767 | Loss 0.0135


Epoch 3/3 | Step 400/767 | Loss 0.8946


Epoch 3/3 | Step 450/767 | Loss 2.7508


Epoch 3/3 | Step 500/767 | Loss 0.1288


Epoch 3/3 | Step 550/767 | Loss 2.7814


Epoch 3/3 | Step 600/767 | Loss 0.1007


Epoch 3/3 | Step 650/767 | Loss 0.0721


Epoch 3/3 | Step 700/767 | Loss 0.0407


Epoch 3/3 | Step 750/767 | Loss 1.3390


Epoch 3/3 finished | loss=0.6662 | val_f1=0.5949 | val_auc=0.7474 | time=13.22 min


Classifier inference:   0%|          | 0/3 [00:00<?, ?it/s]


Running config: pool=topk_mean__topk=1__spans=3-5-8__stride=4__freeze=True


Epoch 1/3 | Step 0/767 | Loss 1.6707


Epoch 1/3 | Step 50/767 | Loss 0.1463


Epoch 1/3 | Step 100/767 | Loss 0.3954


Epoch 1/3 | Step 150/767 | Loss 0.7987


Epoch 1/3 | Step 200/767 | Loss 0.4834


Epoch 1/3 | Step 250/767 | Loss 0.3966


Epoch 1/3 | Step 300/767 | Loss 2.4793


Epoch 1/3 | Step 350/767 | Loss 0.2295


Epoch 1/3 | Step 400/767 | Loss 0.8036


Epoch 1/3 | Step 450/767 | Loss 1.2206


Epoch 1/3 | Step 500/767 | Loss 0.0512


Epoch 1/3 | Step 550/767 | Loss 0.2702


Epoch 1/3 | Step 600/767 | Loss 0.5382


Epoch 1/3 | Step 650/767 | Loss 1.8907


Epoch 1/3 | Step 700/767 | Loss 0.2478


Epoch 1/3 | Step 750/767 | Loss 0.8470


Epoch 1/3 finished | loss=0.7713 | val_f1=0.3902 | val_auc=0.7429 | time=10.40 min


Epoch 2/3 | Step 0/767 | Loss 0.1678


Epoch 2/3 | Step 50/767 | Loss 0.1143


Epoch 2/3 | Step 100/767 | Loss 1.3941


Epoch 2/3 | Step 150/767 | Loss 0.0274


Epoch 2/3 | Step 200/767 | Loss 0.6847


Epoch 2/3 | Step 250/767 | Loss 0.8560


Epoch 2/3 | Step 300/767 | Loss 0.8844


Epoch 2/3 | Step 350/767 | Loss 0.4245


Epoch 2/3 | Step 400/767 | Loss 0.1617


Epoch 2/3 | Step 450/767 | Loss 0.6519


Epoch 2/3 | Step 500/767 | Loss 0.4571


Epoch 2/3 | Step 550/767 | Loss 1.7979


Epoch 2/3 | Step 600/767 | Loss 0.0453


Epoch 2/3 | Step 650/767 | Loss 1.4096


Epoch 2/3 | Step 700/767 | Loss 0.9882


Epoch 2/3 | Step 750/767 | Loss 0.3896


Epoch 2/3 finished | loss=0.7266 | val_f1=0.5275 | val_auc=0.7396 | time=10.40 min


Epoch 3/3 | Step 0/767 | Loss 0.3922


Epoch 3/3 | Step 50/767 | Loss 0.2851


Epoch 3/3 | Step 100/767 | Loss 0.0426


Epoch 3/3 | Step 150/767 | Loss 1.4664


Epoch 3/3 | Step 200/767 | Loss 0.0656


Epoch 3/3 | Step 250/767 | Loss 0.1144


Epoch 3/3 | Step 300/767 | Loss 1.5002


Epoch 3/3 | Step 350/767 | Loss 2.1484


Epoch 3/3 | Step 400/767 | Loss 0.1076


Epoch 3/3 | Step 450/767 | Loss 0.1084


Epoch 3/3 | Step 500/767 | Loss 1.7032


Epoch 3/3 | Step 550/767 | Loss 0.2145


Epoch 3/3 | Step 600/767 | Loss 0.7179


Epoch 3/3 | Step 650/767 | Loss 0.6443


Epoch 3/3 | Step 700/767 | Loss 1.3757


Epoch 3/3 | Step 750/767 | Loss 0.0812


Epoch 3/3 finished | loss=0.6815 | val_f1=0.5608 | val_auc=0.7457 | time=10.37 min


Classifier inference:   0%|          | 0/3 [00:00<?, ?it/s]


Running config: pool=topk_mean__topk=3__spans=3-5-8__stride=4__freeze=True


Epoch 1/3 | Step 0/767 | Loss 1.6515


Epoch 1/3 | Step 50/767 | Loss 0.7305


Epoch 1/3 | Step 100/767 | Loss 0.7569


Epoch 1/3 | Step 150/767 | Loss 0.5136


Epoch 1/3 | Step 200/767 | Loss 0.7667


Epoch 1/3 | Step 250/767 | Loss 1.5151


Epoch 1/3 | Step 300/767 | Loss 0.4512


Epoch 1/3 | Step 350/767 | Loss 0.6557


Epoch 1/3 | Step 400/767 | Loss 0.4628


Epoch 1/3 | Step 450/767 | Loss 0.3176


Epoch 1/3 | Step 500/767 | Loss 0.0481


Epoch 1/3 | Step 550/767 | Loss 0.5745


Epoch 1/3 | Step 600/767 | Loss 1.2099


Epoch 1/3 | Step 650/767 | Loss 1.6153


Epoch 1/3 | Step 700/767 | Loss 0.3907


Epoch 1/3 | Step 750/767 | Loss 0.6744


Epoch 1/3 finished | loss=0.7012 | val_f1=0.4889 | val_auc=0.7545 | time=10.35 min


Epoch 2/3 | Step 0/767 | Loss 0.0854


Epoch 2/3 | Step 50/767 | Loss 0.3394


Epoch 2/3 | Step 100/767 | Loss 1.2128


Epoch 2/3 | Step 150/767 | Loss 0.3927


Epoch 2/3 | Step 200/767 | Loss 0.1766


Epoch 2/3 | Step 250/767 | Loss 0.2819


Epoch 2/3 | Step 300/767 | Loss 0.0409


Epoch 2/3 | Step 350/767 | Loss 0.0369


Epoch 2/3 | Step 400/767 | Loss 0.4887


Epoch 2/3 | Step 450/767 | Loss 0.7193


Epoch 2/3 | Step 500/767 | Loss 0.5978


Epoch 2/3 | Step 550/767 | Loss 1.3909


Epoch 2/3 | Step 600/767 | Loss 0.4256


Epoch 2/3 | Step 650/767 | Loss 3.3460


Epoch 2/3 | Step 700/767 | Loss 0.1114


Epoch 2/3 | Step 750/767 | Loss 0.0821


Epoch 2/3 finished | loss=0.6840 | val_f1=0.3333 | val_auc=0.7525 | time=10.35 min


Epoch 3/3 | Step 0/767 | Loss 0.7214


Epoch 3/3 | Step 50/767 | Loss 0.1514


Epoch 3/3 | Step 100/767 | Loss 0.0600


Epoch 3/3 | Step 150/767 | Loss 0.6818


Epoch 3/3 | Step 200/767 | Loss 0.1258


Epoch 3/3 | Step 250/767 | Loss 0.8520


Epoch 3/3 | Step 300/767 | Loss 1.0746


Epoch 3/3 | Step 350/767 | Loss 1.3553


Epoch 3/3 | Step 400/767 | Loss 0.2804


Epoch 3/3 | Step 450/767 | Loss 0.1531


Epoch 3/3 | Step 500/767 | Loss 0.0815


Epoch 3/3 | Step 550/767 | Loss 1.0378


Epoch 3/3 | Step 600/767 | Loss 0.1884


Epoch 3/3 | Step 650/767 | Loss 0.1780


Epoch 3/3 | Step 700/767 | Loss 0.4116


Epoch 3/3 | Step 750/767 | Loss 0.4304


Epoch 3/3 finished | loss=0.6724 | val_f1=0.6571 | val_auc=0.7576 | time=10.35 min


Classifier inference:   0%|          | 0/3 [00:00<?, ?it/s]


Running config: pool=topk_mean__topk=5__spans=3-5-8__stride=4__freeze=True


Epoch 1/3 | Step 0/767 | Loss 3.9935


Epoch 1/3 | Step 50/767 | Loss 0.1024


Epoch 1/3 | Step 100/767 | Loss 0.6817


Epoch 1/3 | Step 150/767 | Loss 0.1046


Epoch 1/3 | Step 200/767 | Loss 0.9449


Epoch 1/3 | Step 250/767 | Loss 0.9714


Epoch 1/3 | Step 300/767 | Loss 0.6782


Epoch 1/3 | Step 350/767 | Loss 0.5368


Epoch 1/3 | Step 400/767 | Loss 0.3169


Epoch 1/3 | Step 450/767 | Loss 0.2497


Epoch 1/3 | Step 500/767 | Loss 0.4662


Epoch 1/3 | Step 550/767 | Loss 0.7997


Epoch 1/3 | Step 600/767 | Loss 0.9631


Epoch 1/3 | Step 650/767 | Loss 0.1002


Epoch 1/3 | Step 700/767 | Loss 0.1097


Epoch 1/3 | Step 750/767 | Loss 0.3749


Epoch 1/3 finished | loss=0.7575 | val_f1=0.6636 | val_auc=0.7518 | time=10.34 min


Epoch 2/3 | Step 0/767 | Loss 0.2652


Epoch 2/3 | Step 50/767 | Loss 2.5441


Epoch 2/3 | Step 100/767 | Loss 0.0443


Epoch 2/3 | Step 150/767 | Loss 0.3260


Epoch 2/3 | Step 200/767 | Loss 1.3753


Epoch 2/3 | Step 250/767 | Loss 0.1150


Epoch 2/3 | Step 300/767 | Loss 1.5099


Epoch 2/3 | Step 350/767 | Loss 0.6945


Epoch 2/3 | Step 400/767 | Loss 0.0503


Epoch 2/3 | Step 450/767 | Loss 0.1886


Epoch 2/3 | Step 500/767 | Loss 2.1737


Epoch 2/3 | Step 550/767 | Loss 0.6681


Epoch 2/3 | Step 600/767 | Loss 0.1231


Epoch 2/3 | Step 650/767 | Loss 0.0752


Epoch 2/3 | Step 700/767 | Loss 0.3352


Epoch 2/3 | Step 750/767 | Loss 0.0396


Epoch 2/3 finished | loss=0.7021 | val_f1=0.6100 | val_auc=0.7551 | time=10.35 min


Epoch 3/3 | Step 0/767 | Loss 0.2896


Epoch 3/3 | Step 50/767 | Loss 1.2662


Epoch 3/3 | Step 100/767 | Loss 0.0345


Epoch 3/3 | Step 150/767 | Loss 0.9767


Epoch 3/3 | Step 200/767 | Loss 1.9364


Epoch 3/3 | Step 250/767 | Loss 0.1655


Epoch 3/3 | Step 300/767 | Loss 0.0730


Epoch 3/3 | Step 350/767 | Loss 1.1075


Epoch 3/3 | Step 400/767 | Loss 0.8268


Epoch 3/3 | Step 450/767 | Loss 0.5867


Epoch 3/3 | Step 500/767 | Loss 1.2995


Epoch 3/3 | Step 550/767 | Loss 0.4719


Epoch 3/3 | Step 600/767 | Loss 0.6111


Epoch 3/3 | Step 650/767 | Loss 0.0761


Epoch 3/3 | Step 700/767 | Loss 0.0688


Epoch 3/3 | Step 750/767 | Loss 0.0420


Epoch 3/3 finished | loss=0.6538 | val_f1=0.6698 | val_auc=0.7567 | time=10.35 min


Classifier inference:   0%|          | 0/3 [00:00<?, ?it/s]


Running config: pool=topk_mean__topk=1__spans=5-10-15__stride=2__freeze=True


Epoch 1/3 | Step 0/767 | Loss 0.0293


Epoch 1/3 | Step 50/767 | Loss 1.6649


Epoch 1/3 | Step 100/767 | Loss 0.8313


Epoch 1/3 | Step 150/767 | Loss 0.8065


Epoch 1/3 | Step 200/767 | Loss 0.7313


Epoch 1/3 | Step 250/767 | Loss 0.5203


Epoch 1/3 | Step 300/767 | Loss 0.5842


Epoch 1/3 | Step 350/767 | Loss 0.2431


Epoch 1/3 | Step 400/767 | Loss 2.0659


Epoch 1/3 | Step 450/767 | Loss 0.7969


Epoch 1/3 | Step 500/767 | Loss 0.0408


Epoch 1/3 | Step 550/767 | Loss 0.5743


Epoch 1/3 | Step 600/767 | Loss 0.7587


Epoch 1/3 | Step 650/767 | Loss 0.1625


Epoch 1/3 | Step 700/767 | Loss 0.0119


Epoch 1/3 | Step 750/767 | Loss 0.9670


Epoch 1/3 finished | loss=0.7495 | val_f1=0.6977 | val_auc=0.7635 | time=12.76 min


Epoch 2/3 | Step 0/767 | Loss 0.3377


Epoch 2/3 | Step 50/767 | Loss 1.1470


Epoch 2/3 | Step 100/767 | Loss 0.2855


Epoch 2/3 | Step 150/767 | Loss 1.6200


Epoch 2/3 | Step 200/767 | Loss 0.0277


Epoch 2/3 | Step 250/767 | Loss 0.2723


Epoch 2/3 | Step 300/767 | Loss 0.5942


Epoch 2/3 | Step 350/767 | Loss 0.1314


Epoch 2/3 | Step 400/767 | Loss 0.0872


Epoch 2/3 | Step 450/767 | Loss 0.6866


Epoch 2/3 | Step 500/767 | Loss 1.2914


Epoch 2/3 | Step 550/767 | Loss 0.3468


Epoch 2/3 | Step 600/767 | Loss 0.0039


Epoch 2/3 | Step 650/767 | Loss 1.4603


Epoch 2/3 | Step 700/767 | Loss 0.7073


Epoch 2/3 | Step 750/767 | Loss 1.4057


Epoch 2/3 finished | loss=0.6777 | val_f1=0.4471 | val_auc=0.7532 | time=12.73 min


Epoch 3/3 | Step 0/767 | Loss 0.0217


Epoch 3/3 | Step 50/767 | Loss 0.0631


Epoch 3/3 | Step 100/767 | Loss 1.3152


Epoch 3/3 | Step 150/767 | Loss 1.5323


Epoch 3/3 | Step 200/767 | Loss 1.0675


Epoch 3/3 | Step 250/767 | Loss 2.0742


Epoch 3/3 | Step 300/767 | Loss 0.1049


Epoch 3/3 | Step 350/767 | Loss 1.1575


Epoch 3/3 | Step 400/767 | Loss 0.0689


Epoch 3/3 | Step 450/767 | Loss 0.2857


Epoch 3/3 | Step 500/767 | Loss 2.6610


Epoch 3/3 | Step 550/767 | Loss 0.0358


Epoch 3/3 | Step 600/767 | Loss 0.0096


Epoch 3/3 | Step 650/767 | Loss 2.2883


Epoch 3/3 | Step 700/767 | Loss 0.1144


Epoch 3/3 | Step 750/767 | Loss 0.0824


Epoch 3/3 finished | loss=0.6793 | val_f1=0.5591 | val_auc=0.7600 | time=12.76 min


Classifier inference:   0%|          | 0/3 [00:00<?, ?it/s]


Running config: pool=topk_mean__topk=3__spans=5-10-15__stride=2__freeze=True


Epoch 1/3 | Step 0/767 | Loss 3.3631


Epoch 1/3 | Step 50/767 | Loss 1.0521


Epoch 1/3 | Step 100/767 | Loss 0.6708


Epoch 1/3 | Step 150/767 | Loss 0.3912


Epoch 1/3 | Step 200/767 | Loss 1.4061


Epoch 1/3 | Step 250/767 | Loss 0.0701


Epoch 1/3 | Step 300/767 | Loss 0.2356


Epoch 1/3 | Step 350/767 | Loss 0.2306


Epoch 1/3 | Step 400/767 | Loss 1.6901


Epoch 1/3 | Step 450/767 | Loss 0.1279


Epoch 1/3 | Step 500/767 | Loss 0.1314


Epoch 1/3 | Step 550/767 | Loss 0.1728


Epoch 1/3 | Step 600/767 | Loss 0.0068


Epoch 1/3 | Step 650/767 | Loss 0.0177


Epoch 1/3 | Step 700/767 | Loss 2.8747


Epoch 1/3 | Step 750/767 | Loss 0.1879


Epoch 1/3 finished | loss=0.7122 | val_f1=0.6977 | val_auc=0.7689 | time=12.77 min


Epoch 2/3 | Step 0/767 | Loss 0.0042


Epoch 2/3 | Step 50/767 | Loss 0.3549


Epoch 2/3 | Step 100/767 | Loss 0.0387


Epoch 2/3 | Step 150/767 | Loss 0.1514


Epoch 2/3 | Step 200/767 | Loss 0.4722


Epoch 2/3 | Step 250/767 | Loss 0.3774


Epoch 2/3 | Step 300/767 | Loss 0.0449


Epoch 2/3 | Step 350/767 | Loss 1.0874


Epoch 2/3 | Step 400/767 | Loss 2.2480


Epoch 2/3 | Step 450/767 | Loss 3.0571


Epoch 2/3 | Step 500/767 | Loss 0.1893


Epoch 2/3 | Step 550/767 | Loss 2.7312


Epoch 2/3 | Step 600/767 | Loss 0.2090


Epoch 2/3 | Step 650/767 | Loss 1.2679


Epoch 2/3 | Step 700/767 | Loss 0.2580


Epoch 2/3 | Step 750/767 | Loss 0.1117


Epoch 2/3 finished | loss=0.6702 | val_f1=0.6502 | val_auc=0.7660 | time=12.79 min


Epoch 3/3 | Step 0/767 | Loss 0.0648


Epoch 3/3 | Step 50/767 | Loss 1.7810


Epoch 3/3 | Step 100/767 | Loss 0.0201


Epoch 3/3 | Step 150/767 | Loss 0.6667


Epoch 3/3 | Step 200/767 | Loss 0.2847


Epoch 3/3 | Step 250/767 | Loss 0.0311


Epoch 3/3 | Step 300/767 | Loss 1.6529


Epoch 3/3 | Step 350/767 | Loss 0.2306


Epoch 3/3 | Step 400/767 | Loss 0.2631


Epoch 3/3 | Step 450/767 | Loss 0.0055


Epoch 3/3 | Step 500/767 | Loss 0.1309


Epoch 3/3 | Step 550/767 | Loss 3.1438


Epoch 3/3 | Step 600/767 | Loss 0.8792


Epoch 3/3 | Step 650/767 | Loss 0.0126


Epoch 3/3 | Step 700/767 | Loss 0.9854


Epoch 3/3 | Step 750/767 | Loss 0.6937


Epoch 3/3 finished | loss=0.6543 | val_f1=0.6122 | val_auc=0.7695 | time=12.77 min


Classifier inference:   0%|          | 0/3 [00:00<?, ?it/s]


Running config: pool=topk_mean__topk=5__spans=5-10-15__stride=2__freeze=True


Epoch 1/3 | Step 0/767 | Loss 1.8228


Epoch 1/3 | Step 50/767 | Loss 1.0493


Epoch 1/3 | Step 100/767 | Loss 1.0935


Epoch 1/3 | Step 150/767 | Loss 0.3204


Epoch 1/3 | Step 200/767 | Loss 0.5501


Epoch 1/3 | Step 250/767 | Loss 0.1974


Epoch 1/3 | Step 300/767 | Loss 0.0340


Epoch 1/3 | Step 350/767 | Loss 0.2035


Epoch 1/3 | Step 400/767 | Loss 0.2556


Epoch 1/3 | Step 450/767 | Loss 2.4032


Epoch 1/3 | Step 500/767 | Loss 1.1631


Epoch 1/3 | Step 550/767 | Loss 1.7819


Epoch 1/3 | Step 600/767 | Loss 0.6595


Epoch 1/3 | Step 650/767 | Loss 1.2473


Epoch 1/3 | Step 700/767 | Loss 0.3829


Epoch 1/3 | Step 750/767 | Loss 1.5399


Epoch 1/3 finished | loss=0.7212 | val_f1=0.6400 | val_auc=0.7607 | time=12.79 min


Epoch 2/3 | Step 0/767 | Loss 1.7841


Epoch 2/3 | Step 50/767 | Loss 0.4367


Epoch 2/3 | Step 100/767 | Loss 1.0178


Epoch 2/3 | Step 150/767 | Loss 2.0427


Epoch 2/3 | Step 200/767 | Loss 0.0282


Epoch 2/3 | Step 250/767 | Loss 0.5925


Epoch 2/3 | Step 300/767 | Loss 0.7925


Epoch 2/3 | Step 350/767 | Loss 0.4674


Epoch 2/3 | Step 400/767 | Loss 0.0367


Epoch 2/3 | Step 450/767 | Loss 1.0121


Epoch 2/3 | Step 500/767 | Loss 0.0188


Epoch 2/3 | Step 550/767 | Loss 0.0029


Epoch 2/3 | Step 600/767 | Loss 0.0326


Epoch 2/3 | Step 650/767 | Loss 0.0373


Epoch 2/3 | Step 700/767 | Loss 0.5039


Epoch 2/3 | Step 750/767 | Loss 1.4599


Epoch 2/3 finished | loss=0.6596 | val_f1=0.6300 | val_auc=0.7684 | time=12.79 min


Epoch 3/3 | Step 0/767 | Loss 0.0207


Epoch 3/3 | Step 50/767 | Loss 0.6668


Epoch 3/3 | Step 100/767 | Loss 0.6743


Epoch 3/3 | Step 150/767 | Loss 2.1392


Epoch 3/3 | Step 200/767 | Loss 0.4238


Epoch 3/3 | Step 250/767 | Loss 0.0207


Epoch 3/3 | Step 300/767 | Loss 0.1309


Epoch 3/3 | Step 350/767 | Loss 0.1191


Epoch 3/3 | Step 400/767 | Loss 0.5359


Epoch 3/3 | Step 450/767 | Loss 0.0142


Epoch 3/3 | Step 500/767 | Loss 0.3265


Epoch 3/3 | Step 550/767 | Loss 0.0572


Epoch 3/3 | Step 600/767 | Loss 0.4800


Epoch 3/3 | Step 650/767 | Loss 0.6749


Epoch 3/3 | Step 700/767 | Loss 2.2177


Epoch 3/3 | Step 750/767 | Loss 0.0123


Epoch 3/3 finished | loss=0.6309 | val_f1=0.6916 | val_auc=0.7705 | time=12.78 min


Classifier inference:   0%|          | 0/3 [00:00<?, ?it/s]


Running config: pool=topk_mean__topk=1__spans=5-10-15__stride=4__freeze=True


Epoch 1/3 | Step 0/767 | Loss 2.9401


Epoch 1/3 | Step 50/767 | Loss 1.6815


Epoch 1/3 | Step 100/767 | Loss 0.7891


Epoch 1/3 | Step 150/767 | Loss 0.5048


Epoch 1/3 | Step 200/767 | Loss 0.1634


Epoch 1/3 | Step 250/767 | Loss 1.9884


Epoch 1/3 | Step 300/767 | Loss 0.5326


Epoch 1/3 | Step 350/767 | Loss 0.5576


Epoch 1/3 | Step 400/767 | Loss 1.0631


Epoch 1/3 | Step 450/767 | Loss 0.1803


Epoch 1/3 | Step 500/767 | Loss 3.4111


Epoch 1/3 | Step 550/767 | Loss 0.3131


Epoch 1/3 | Step 600/767 | Loss 0.0489


Epoch 1/3 | Step 650/767 | Loss 0.8968


Epoch 1/3 | Step 700/767 | Loss 0.1119


Epoch 1/3 | Step 750/767 | Loss 0.0110


Epoch 1/3 finished | loss=0.7154 | val_f1=0.7319 | val_auc=0.7669 | time=10.07 min


Epoch 2/3 | Step 0/767 | Loss 1.2608


Epoch 2/3 | Step 50/767 | Loss 0.2697


Epoch 2/3 | Step 100/767 | Loss 2.4046


Epoch 2/3 | Step 150/767 | Loss 0.1513


Epoch 2/3 | Step 200/767 | Loss 0.1705


Epoch 2/3 | Step 250/767 | Loss 0.2227


Epoch 2/3 | Step 300/767 | Loss 1.0723


Epoch 2/3 | Step 350/767 | Loss 0.5922


Epoch 2/3 | Step 400/767 | Loss 0.7222


Epoch 2/3 | Step 450/767 | Loss 0.7641


Epoch 2/3 | Step 500/767 | Loss 0.8676


Epoch 2/3 | Step 550/767 | Loss 0.2464


Epoch 2/3 | Step 600/767 | Loss 0.0504


Epoch 2/3 | Step 650/767 | Loss 0.7190


Epoch 2/3 | Step 700/767 | Loss 0.5055


Epoch 2/3 | Step 750/767 | Loss 1.4751


Epoch 2/3 finished | loss=0.6815 | val_f1=0.6698 | val_auc=0.7664 | time=10.07 min


Epoch 3/3 | Step 0/767 | Loss 0.3533


Epoch 3/3 | Step 50/767 | Loss 0.1307


Epoch 3/3 | Step 100/767 | Loss 0.2247


Epoch 3/3 | Step 150/767 | Loss 1.1727


Epoch 3/3 | Step 200/767 | Loss 0.1276


Epoch 3/3 | Step 250/767 | Loss 0.1111


Epoch 3/3 | Step 300/767 | Loss 0.0331


Epoch 3/3 | Step 350/767 | Loss 0.0946


Epoch 3/3 | Step 400/767 | Loss 0.0095


Epoch 3/3 | Step 450/767 | Loss 0.1833


Epoch 3/3 | Step 500/767 | Loss 3.9827


Epoch 3/3 | Step 550/767 | Loss 1.3537


Epoch 3/3 | Step 600/767 | Loss 0.3197


Epoch 3/3 | Step 650/767 | Loss 0.8366


Epoch 3/3 | Step 700/767 | Loss 0.1819


Epoch 3/3 | Step 750/767 | Loss 2.2368


Epoch 3/3 finished | loss=0.6619 | val_f1=0.6570 | val_auc=0.7676 | time=10.07 min


Classifier inference:   0%|          | 0/3 [00:00<?, ?it/s]


Running config: pool=topk_mean__topk=3__spans=5-10-15__stride=4__freeze=True


Epoch 1/3 | Step 0/767 | Loss 1.9651


Epoch 1/3 | Step 50/767 | Loss 1.0394


Epoch 1/3 | Step 100/767 | Loss 0.4611


Epoch 1/3 | Step 150/767 | Loss 0.7646


Epoch 1/3 | Step 200/767 | Loss 2.1242


Epoch 1/3 | Step 250/767 | Loss 0.2009


Epoch 1/3 | Step 300/767 | Loss 0.4392


Epoch 1/3 | Step 350/767 | Loss 1.7647


Epoch 1/3 | Step 400/767 | Loss 0.9757


Epoch 1/3 | Step 450/767 | Loss 0.0671


Epoch 1/3 | Step 500/767 | Loss 0.4403


Epoch 1/3 | Step 550/767 | Loss 2.0684


Epoch 1/3 | Step 600/767 | Loss 0.9858


Epoch 1/3 | Step 650/767 | Loss 0.2840


Epoch 1/3 | Step 700/767 | Loss 0.3009


Epoch 1/3 | Step 750/767 | Loss 0.3564


Epoch 1/3 finished | loss=0.7733 | val_f1=0.7500 | val_auc=0.7716 | time=10.07 min


Epoch 2/3 | Step 0/767 | Loss 0.3345


Epoch 2/3 | Step 50/767 | Loss 0.7640


Epoch 2/3 | Step 100/767 | Loss 0.2201


Epoch 2/3 | Step 150/767 | Loss 0.1654


Epoch 2/3 | Step 200/767 | Loss 0.6504


Epoch 2/3 | Step 250/767 | Loss 0.0121


Epoch 2/3 | Step 300/767 | Loss 1.9593


Epoch 2/3 | Step 350/767 | Loss 0.5740


Epoch 2/3 | Step 400/767 | Loss 0.6459


Epoch 2/3 | Step 450/767 | Loss 1.6472


Epoch 2/3 | Step 500/767 | Loss 0.4277


Epoch 2/3 | Step 550/767 | Loss 0.0323


Epoch 2/3 | Step 600/767 | Loss 1.6644


Epoch 2/3 | Step 650/767 | Loss 1.6722


Epoch 2/3 | Step 700/767 | Loss 0.5146


Epoch 2/3 | Step 750/767 | Loss 0.6482


Epoch 2/3 finished | loss=0.6996 | val_f1=0.7241 | val_auc=0.7740 | time=10.06 min


Epoch 3/3 | Step 0/767 | Loss 0.0054


Epoch 3/3 | Step 50/767 | Loss 0.0759


Epoch 3/3 | Step 100/767 | Loss 1.3838


Epoch 3/3 | Step 150/767 | Loss 0.0377


Epoch 3/3 | Step 200/767 | Loss 0.0940


Epoch 3/3 | Step 250/767 | Loss 3.4765


Epoch 3/3 | Step 300/767 | Loss 0.6807


Epoch 3/3 | Step 350/767 | Loss 0.6098


Epoch 3/3 | Step 400/767 | Loss 0.4850


Epoch 3/3 | Step 450/767 | Loss 0.2754


Epoch 3/3 | Step 500/767 | Loss 0.0609


Epoch 3/3 | Step 550/767 | Loss 1.6611


Epoch 3/3 | Step 600/767 | Loss 4.6057


Epoch 3/3 | Step 650/767 | Loss 1.4367


Epoch 3/3 | Step 700/767 | Loss 0.1634


Epoch 3/3 | Step 750/767 | Loss 0.0264


Epoch 3/3 finished | loss=0.6584 | val_f1=0.7032 | val_auc=0.7753 | time=10.06 min


Classifier inference:   0%|          | 0/3 [00:00<?, ?it/s]


Running config: pool=topk_mean__topk=5__spans=5-10-15__stride=4__freeze=True


Epoch 1/3 | Step 0/767 | Loss 1.7754


Epoch 1/3 | Step 50/767 | Loss 0.1635


Epoch 1/3 | Step 100/767 | Loss 0.6696


Epoch 1/3 | Step 150/767 | Loss 0.6535


Epoch 1/3 | Step 200/767 | Loss 0.6513


Epoch 1/3 | Step 250/767 | Loss 0.6088


Epoch 1/3 | Step 300/767 | Loss 2.0198


Epoch 1/3 | Step 350/767 | Loss 0.5280


Epoch 1/3 | Step 400/767 | Loss 0.7505


Epoch 1/3 | Step 450/767 | Loss 0.2920


Epoch 1/3 | Step 500/767 | Loss 0.0286


Epoch 1/3 | Step 550/767 | Loss 1.4707


Epoch 1/3 | Step 600/767 | Loss 0.9308


Epoch 1/3 | Step 650/767 | Loss 0.2285


Epoch 1/3 | Step 700/767 | Loss 0.8036


Epoch 1/3 | Step 750/767 | Loss 1.6390


Epoch 1/3 finished | loss=0.7541 | val_f1=0.7143 | val_auc=0.7753 | time=10.09 min


Epoch 2/3 | Step 0/767 | Loss 0.1000


Epoch 2/3 | Step 50/767 | Loss 0.6693


Epoch 2/3 | Step 100/767 | Loss 0.1511


Epoch 2/3 | Step 150/767 | Loss 0.9074


Epoch 2/3 | Step 200/767 | Loss 0.7274


Epoch 2/3 | Step 250/767 | Loss 0.6394


Epoch 2/3 | Step 300/767 | Loss 0.5559


Epoch 2/3 | Step 350/767 | Loss 0.2383


Epoch 2/3 | Step 400/767 | Loss 0.0192


Epoch 2/3 | Step 450/767 | Loss 0.6466


Epoch 2/3 | Step 500/767 | Loss 0.0392


Epoch 2/3 | Step 550/767 | Loss 1.1042


Epoch 2/3 | Step 600/767 | Loss 0.2256


Epoch 2/3 | Step 650/767 | Loss 1.5906


Epoch 2/3 | Step 700/767 | Loss 0.0645


Epoch 2/3 | Step 750/767 | Loss 0.7057


Epoch 2/3 finished | loss=0.6757 | val_f1=0.7654 | val_auc=0.7798 | time=10.05 min


Epoch 3/3 | Step 0/767 | Loss 0.1638


Epoch 3/3 | Step 50/767 | Loss 0.4260


Epoch 3/3 | Step 100/767 | Loss 0.3566


Epoch 3/3 | Step 150/767 | Loss 0.0645


Epoch 3/3 | Step 200/767 | Loss 0.5956


Epoch 3/3 | Step 250/767 | Loss 2.3881


Epoch 3/3 | Step 300/767 | Loss 0.3108


Epoch 3/3 | Step 350/767 | Loss 0.0224


Epoch 3/3 | Step 400/767 | Loss 0.1447


Epoch 3/3 | Step 450/767 | Loss 0.0288


Epoch 3/3 | Step 500/767 | Loss 0.1575


Epoch 3/3 | Step 550/767 | Loss 0.1985


Epoch 3/3 | Step 600/767 | Loss 0.5066


Epoch 3/3 | Step 650/767 | Loss 0.1024


Epoch 3/3 | Step 700/767 | Loss 0.3068


Epoch 3/3 | Step 750/767 | Loss 1.3310


Epoch 3/3 finished | loss=0.6289 | val_f1=0.6919 | val_auc=0.7789 | time=10.07 min


Classifier inference:   0%|          | 0/3 [00:00<?, ?it/s]


Running config: pool=topk_mean__topk=1__spans=10-15-20__stride=2__freeze=True


Epoch 1/3 | Step 0/767 | Loss 1.4667


Epoch 1/3 | Step 50/767 | Loss 0.2496


Epoch 1/3 | Step 100/767 | Loss 1.2535


Epoch 1/3 | Step 150/767 | Loss 0.2947


Epoch 1/3 | Step 200/767 | Loss 0.8300


Epoch 1/3 | Step 250/767 | Loss 1.8381


Epoch 1/3 | Step 300/767 | Loss 1.9178


Epoch 1/3 | Step 350/767 | Loss 0.5619


Epoch 1/3 | Step 400/767 | Loss 0.1069


Epoch 1/3 | Step 450/767 | Loss 0.9192


Epoch 1/3 | Step 500/767 | Loss 0.6888


Epoch 1/3 | Step 550/767 | Loss 0.0376


Epoch 1/3 | Step 600/767 | Loss 0.2426


Epoch 1/3 | Step 650/767 | Loss 0.2978


Epoch 1/3 | Step 700/767 | Loss 0.1483


Epoch 1/3 | Step 750/767 | Loss 0.0110


Epoch 1/3 finished | loss=0.7028 | val_f1=0.5851 | val_auc=0.7792 | time=12.33 min


Epoch 2/3 | Step 0/767 | Loss 0.6666


Epoch 2/3 | Step 50/767 | Loss 0.5167


Epoch 2/3 | Step 100/767 | Loss 0.3974


Epoch 2/3 | Step 150/767 | Loss 2.6348


Epoch 2/3 | Step 200/767 | Loss 0.0478


Epoch 2/3 | Step 250/767 | Loss 0.0180


Epoch 2/3 | Step 300/767 | Loss 0.6999


Epoch 2/3 | Step 350/767 | Loss 0.2092


Epoch 2/3 | Step 400/767 | Loss 0.5197


Epoch 2/3 | Step 450/767 | Loss 0.0884


Epoch 2/3 | Step 500/767 | Loss 0.0151


Epoch 2/3 | Step 550/767 | Loss 0.0110


Epoch 2/3 | Step 600/767 | Loss 0.1003


Epoch 2/3 | Step 650/767 | Loss 0.0163


Epoch 2/3 | Step 700/767 | Loss 0.0183


Epoch 2/3 | Step 750/767 | Loss 2.2071


Epoch 2/3 finished | loss=0.6607 | val_f1=0.5525 | val_auc=0.7728 | time=12.28 min


Epoch 3/3 | Step 0/767 | Loss 1.3181


Epoch 3/3 | Step 50/767 | Loss 1.0938


Epoch 3/3 | Step 100/767 | Loss 0.1994


Epoch 3/3 | Step 150/767 | Loss 0.0232


Epoch 3/3 | Step 200/767 | Loss 0.0652


Epoch 3/3 | Step 250/767 | Loss 1.3921


Epoch 3/3 | Step 300/767 | Loss 1.9250


Epoch 3/3 | Step 350/767 | Loss 0.0056


Epoch 3/3 | Step 400/767 | Loss 0.5416


Epoch 3/3 | Step 450/767 | Loss 0.3883


Epoch 3/3 | Step 500/767 | Loss 1.5073


Epoch 3/3 | Step 550/767 | Loss 0.1033


Epoch 3/3 | Step 600/767 | Loss 0.5919


Epoch 3/3 | Step 650/767 | Loss 0.9222


Epoch 3/3 | Step 700/767 | Loss 0.3379


Epoch 3/3 | Step 750/767 | Loss 0.4416


Epoch 3/3 finished | loss=0.6572 | val_f1=0.6429 | val_auc=0.7760 | time=12.29 min


Classifier inference:   0%|          | 0/3 [00:00<?, ?it/s]


Running config: pool=topk_mean__topk=3__spans=10-15-20__stride=2__freeze=True


Epoch 1/3 | Step 0/767 | Loss 0.0307


Epoch 1/3 | Step 50/767 | Loss 1.5111


Epoch 1/3 | Step 100/767 | Loss 0.5476


Epoch 1/3 | Step 150/767 | Loss 0.2469


Epoch 1/3 | Step 200/767 | Loss 0.3486


Epoch 1/3 | Step 250/767 | Loss 0.2832


Epoch 1/3 | Step 300/767 | Loss 0.0961


Epoch 1/3 | Step 350/767 | Loss 1.8562


Epoch 1/3 | Step 400/767 | Loss 1.6552


Epoch 1/3 | Step 450/767 | Loss 2.2178


Epoch 1/3 | Step 500/767 | Loss 0.6858


Epoch 1/3 | Step 550/767 | Loss 1.8284


Epoch 1/3 | Step 600/767 | Loss 0.1220


Epoch 1/3 | Step 650/767 | Loss 0.2587


Epoch 1/3 | Step 700/767 | Loss 1.6503


Epoch 1/3 | Step 750/767 | Loss 0.0096


Epoch 1/3 finished | loss=0.7007 | val_f1=0.7123 | val_auc=0.7782 | time=12.31 min


Epoch 2/3 | Step 0/767 | Loss 0.0043


Epoch 2/3 | Step 50/767 | Loss 0.6431


Epoch 2/3 | Step 100/767 | Loss 0.9308


Epoch 2/3 | Step 150/767 | Loss 0.1174


Epoch 2/3 | Step 200/767 | Loss 0.3178


Epoch 2/3 | Step 250/767 | Loss 0.0477


Epoch 2/3 | Step 300/767 | Loss 1.1833


Epoch 2/3 | Step 350/767 | Loss 2.3440


Epoch 2/3 | Step 400/767 | Loss 1.2751


Epoch 2/3 | Step 450/767 | Loss 1.6565


Epoch 2/3 | Step 500/767 | Loss 0.0110


Epoch 2/3 | Step 550/767 | Loss 0.0259


Epoch 2/3 | Step 600/767 | Loss 3.0231


Epoch 2/3 | Step 650/767 | Loss 0.4235


Epoch 2/3 | Step 700/767 | Loss 0.4868


Epoch 2/3 | Step 750/767 | Loss 0.0106


Epoch 2/3 finished | loss=0.6477 | val_f1=0.6000 | val_auc=0.7703 | time=12.28 min


Epoch 3/3 | Step 0/767 | Loss 0.0062


Epoch 3/3 | Step 50/767 | Loss 0.1498


Epoch 3/3 | Step 100/767 | Loss 0.0093


Epoch 3/3 | Step 150/767 | Loss 0.8110


Epoch 3/3 | Step 200/767 | Loss 0.0721


Epoch 3/3 | Step 250/767 | Loss 0.0396


Epoch 3/3 | Step 300/767 | Loss 1.5083


Epoch 3/3 | Step 350/767 | Loss 1.9981


Epoch 3/3 | Step 400/767 | Loss 0.5724


Epoch 3/3 | Step 450/767 | Loss 0.7835


Epoch 3/3 | Step 500/767 | Loss 0.0247


Epoch 3/3 | Step 550/767 | Loss 0.5962


Epoch 3/3 | Step 600/767 | Loss 2.5355


Epoch 3/3 | Step 650/767 | Loss 0.0223


Epoch 3/3 | Step 700/767 | Loss 0.1227


Epoch 3/3 | Step 750/767 | Loss 0.2323


Epoch 3/3 finished | loss=0.6256 | val_f1=0.6890 | val_auc=0.7773 | time=12.30 min


Classifier inference:   0%|          | 0/3 [00:00<?, ?it/s]


Running config: pool=topk_mean__topk=5__spans=10-15-20__stride=2__freeze=True


Epoch 1/3 | Step 0/767 | Loss 3.7023


Epoch 1/3 | Step 50/767 | Loss 0.9574


Epoch 1/3 | Step 100/767 | Loss 0.2242


Epoch 1/3 | Step 150/767 | Loss 0.4446


Epoch 1/3 | Step 200/767 | Loss 0.9703


Epoch 1/3 | Step 250/767 | Loss 1.2203


Epoch 1/3 | Step 300/767 | Loss 2.4802


Epoch 1/3 | Step 350/767 | Loss 0.9634


Epoch 1/3 | Step 400/767 | Loss 0.3316


Epoch 1/3 | Step 450/767 | Loss 2.8676


Epoch 1/3 | Step 500/767 | Loss 0.0425


Epoch 1/3 | Step 550/767 | Loss 2.0537


Epoch 1/3 | Step 600/767 | Loss 0.9062


Epoch 1/3 | Step 650/767 | Loss 1.0036


Epoch 1/3 | Step 700/767 | Loss 0.1036


Epoch 1/3 | Step 750/767 | Loss 0.2889


Epoch 1/3 finished | loss=0.7420 | val_f1=0.7373 | val_auc=0.7757 | time=12.29 min


Epoch 2/3 | Step 0/767 | Loss 1.2038


Epoch 2/3 | Step 50/767 | Loss 0.0114


Epoch 2/3 | Step 100/767 | Loss 1.3192


Epoch 2/3 | Step 150/767 | Loss 0.4477


Epoch 2/3 | Step 200/767 | Loss 0.3109


Epoch 2/3 | Step 250/767 | Loss 0.6750


Epoch 2/3 | Step 300/767 | Loss 2.1484


Epoch 2/3 | Step 350/767 | Loss 3.3858


Epoch 2/3 | Step 400/767 | Loss 0.0131


Epoch 2/3 | Step 450/767 | Loss 0.0742


Epoch 2/3 | Step 500/767 | Loss 0.1272


Epoch 2/3 | Step 550/767 | Loss 0.9485


Epoch 2/3 | Step 600/767 | Loss 0.0086


Epoch 2/3 | Step 650/767 | Loss 2.2707


Epoch 2/3 | Step 700/767 | Loss 0.9812


Epoch 2/3 | Step 750/767 | Loss 0.1470


Epoch 2/3 finished | loss=0.6628 | val_f1=0.6699 | val_auc=0.7760 | time=12.26 min


Epoch 3/3 | Step 0/767 | Loss 0.0319


Epoch 3/3 | Step 50/767 | Loss 0.0560


Epoch 3/3 | Step 100/767 | Loss 0.9178


Epoch 3/3 | Step 150/767 | Loss 0.4302


Epoch 3/3 | Step 200/767 | Loss 0.8916


Epoch 3/3 | Step 250/767 | Loss 0.0177


Epoch 3/3 | Step 300/767 | Loss 0.0786


Epoch 3/3 | Step 350/767 | Loss 0.0897


Epoch 3/3 | Step 400/767 | Loss 0.4297


Epoch 3/3 | Step 450/767 | Loss 1.1140


Epoch 3/3 | Step 500/767 | Loss 0.3404


Epoch 3/3 | Step 550/767 | Loss 0.7495


Epoch 3/3 | Step 600/767 | Loss 1.0696


Epoch 3/3 | Step 650/767 | Loss 0.1099


Epoch 3/3 | Step 700/767 | Loss 0.2974


Epoch 3/3 | Step 750/767 | Loss 0.0212


Epoch 3/3 finished | loss=0.6283 | val_f1=0.6827 | val_auc=0.7777 | time=12.31 min


Classifier inference:   0%|          | 0/3 [00:00<?, ?it/s]


Running config: pool=topk_mean__topk=1__spans=10-15-20__stride=4__freeze=True


Epoch 1/3 | Step 0/767 | Loss 0.0254


Epoch 1/3 | Step 50/767 | Loss 0.2690


Epoch 1/3 | Step 100/767 | Loss 0.5067


Epoch 1/3 | Step 150/767 | Loss 0.6152


Epoch 1/3 | Step 200/767 | Loss 1.3723


Epoch 1/3 | Step 250/767 | Loss 0.9318


Epoch 1/3 | Step 300/767 | Loss 0.9092


Epoch 1/3 | Step 350/767 | Loss 0.4245


Epoch 1/3 | Step 400/767 | Loss 0.2115


Epoch 1/3 | Step 450/767 | Loss 1.1875


Epoch 1/3 | Step 500/767 | Loss 0.2923


Epoch 1/3 | Step 550/767 | Loss 0.7927


Epoch 1/3 | Step 600/767 | Loss 0.0886


Epoch 1/3 | Step 650/767 | Loss 0.7328


Epoch 1/3 | Step 700/767 | Loss 0.4081


Epoch 1/3 | Step 750/767 | Loss 0.0822


Epoch 1/3 finished | loss=0.7957 | val_f1=0.7265 | val_auc=0.7712 | time=9.54 min


Epoch 2/3 | Step 0/767 | Loss 1.9021


Epoch 2/3 | Step 50/767 | Loss 0.9048


Epoch 2/3 | Step 100/767 | Loss 0.0336


Epoch 2/3 | Step 150/767 | Loss 1.2097


Epoch 2/3 | Step 200/767 | Loss 0.6460


Epoch 2/3 | Step 250/767 | Loss 1.2693


Epoch 2/3 | Step 300/767 | Loss 0.0063


Epoch 2/3 | Step 350/767 | Loss 1.2747


Epoch 2/3 | Step 400/767 | Loss 1.7043


Epoch 2/3 | Step 450/767 | Loss 0.8492


Epoch 2/3 | Step 500/767 | Loss 0.7546


Epoch 2/3 | Step 550/767 | Loss 0.0579


Epoch 2/3 | Step 600/767 | Loss 0.1174


Epoch 2/3 | Step 650/767 | Loss 0.2034


Epoch 2/3 | Step 700/767 | Loss 2.4274


Epoch 2/3 | Step 750/767 | Loss 0.0515


Epoch 2/3 finished | loss=0.6803 | val_f1=0.7097 | val_auc=0.7787 | time=9.52 min


Epoch 3/3 | Step 0/767 | Loss 4.5993


Epoch 3/3 | Step 50/767 | Loss 0.1194


Epoch 3/3 | Step 100/767 | Loss 0.0017


Epoch 3/3 | Step 150/767 | Loss 0.5952


Epoch 3/3 | Step 200/767 | Loss 0.1249


Epoch 3/3 | Step 250/767 | Loss 0.0940


Epoch 3/3 | Step 300/767 | Loss 0.7054


Epoch 3/3 | Step 350/767 | Loss 1.8935


Epoch 3/3 | Step 400/767 | Loss 0.0301


Epoch 3/3 | Step 450/767 | Loss 0.0953


Epoch 3/3 | Step 500/767 | Loss 0.1351


Epoch 3/3 | Step 550/767 | Loss 2.9070


Epoch 3/3 | Step 600/767 | Loss 0.1212


Epoch 3/3 | Step 650/767 | Loss 1.5845


Epoch 3/3 | Step 700/767 | Loss 1.2516


Epoch 3/3 | Step 750/767 | Loss 1.3717


Epoch 3/3 finished | loss=0.6354 | val_f1=0.6465 | val_auc=0.7723 | time=9.53 min


Classifier inference:   0%|          | 0/3 [00:00<?, ?it/s]


Running config: pool=topk_mean__topk=3__spans=10-15-20__stride=4__freeze=True


Epoch 1/3 | Step 0/767 | Loss 1.7803


Epoch 1/3 | Step 50/767 | Loss 2.0150


Epoch 1/3 | Step 100/767 | Loss 0.2892


Epoch 1/3 | Step 150/767 | Loss 0.5259


Epoch 1/3 | Step 200/767 | Loss 0.4443


Epoch 1/3 | Step 250/767 | Loss 0.0976


Epoch 1/3 | Step 300/767 | Loss 0.6657


Epoch 1/3 | Step 350/767 | Loss 0.0274


Epoch 1/3 | Step 400/767 | Loss 0.0919


Epoch 1/3 | Step 450/767 | Loss 1.4776


Epoch 1/3 | Step 500/767 | Loss 3.4325


Epoch 1/3 | Step 550/767 | Loss 4.2530


Epoch 1/3 | Step 600/767 | Loss 0.0816


Epoch 1/3 | Step 650/767 | Loss 0.1714


Epoch 1/3 | Step 700/767 | Loss 1.1067


Epoch 1/3 | Step 750/767 | Loss 0.5288


Epoch 1/3 finished | loss=0.7203 | val_f1=0.7438 | val_auc=0.7812 | time=9.54 min


Epoch 2/3 | Step 0/767 | Loss 0.2242


Epoch 2/3 | Step 50/767 | Loss 0.1718


Epoch 2/3 | Step 100/767 | Loss 0.0071


Epoch 2/3 | Step 150/767 | Loss 0.1613


Epoch 2/3 | Step 200/767 | Loss 1.0046


Epoch 2/3 | Step 250/767 | Loss 0.4127


Epoch 2/3 | Step 300/767 | Loss 1.0668


Epoch 2/3 | Step 350/767 | Loss 0.2955


Epoch 2/3 | Step 400/767 | Loss 2.7458


Epoch 2/3 | Step 450/767 | Loss 0.4678


Epoch 2/3 | Step 500/767 | Loss 0.0643


Epoch 2/3 | Step 550/767 | Loss 1.1312


Epoch 2/3 | Step 600/767 | Loss 0.0267


Epoch 2/3 | Step 650/767 | Loss 0.1226


Epoch 2/3 | Step 700/767 | Loss 0.3933


Epoch 2/3 | Step 750/767 | Loss 0.4985


Epoch 2/3 finished | loss=0.6412 | val_f1=0.7123 | val_auc=0.7754 | time=9.52 min


Epoch 3/3 | Step 0/767 | Loss 0.0989


Epoch 3/3 | Step 50/767 | Loss 0.0440


Epoch 3/3 | Step 100/767 | Loss 0.0204


Epoch 3/3 | Step 150/767 | Loss 0.0083


Epoch 3/3 | Step 200/767 | Loss 0.8843


Epoch 3/3 | Step 250/767 | Loss 0.1342


Epoch 3/3 | Step 300/767 | Loss 0.4298


Epoch 3/3 | Step 350/767 | Loss 1.6930


Epoch 3/3 | Step 400/767 | Loss 0.2870


Epoch 3/3 | Step 450/767 | Loss 0.2246


Epoch 3/3 | Step 500/767 | Loss 0.6243


Epoch 3/3 | Step 550/767 | Loss 0.0127


Epoch 3/3 | Step 600/767 | Loss 1.2232


Epoch 3/3 | Step 650/767 | Loss 2.7926


Epoch 3/3 | Step 700/767 | Loss 0.1610


Epoch 3/3 | Step 750/767 | Loss 0.0241


Epoch 3/3 finished | loss=0.6431 | val_f1=0.7037 | val_auc=0.7757 | time=9.53 min


Classifier inference:   0%|          | 0/3 [00:00<?, ?it/s]


Running config: pool=topk_mean__topk=5__spans=10-15-20__stride=4__freeze=True


Epoch 1/3 | Step 0/767 | Loss 0.0334


Epoch 1/3 | Step 50/767 | Loss 1.5513


Epoch 1/3 | Step 100/767 | Loss 0.6701


Epoch 1/3 | Step 150/767 | Loss 0.1355


Epoch 1/3 | Step 200/767 | Loss 0.5686


Epoch 1/3 | Step 250/767 | Loss 0.1686


Epoch 1/3 | Step 300/767 | Loss 0.0595


Epoch 1/3 | Step 350/767 | Loss 0.2604


Epoch 1/3 | Step 400/767 | Loss 3.2698


Epoch 1/3 | Step 450/767 | Loss 0.0289


Epoch 1/3 | Step 500/767 | Loss 0.0509


Epoch 1/3 | Step 550/767 | Loss 1.7185


Epoch 1/3 | Step 600/767 | Loss 0.6209


Epoch 1/3 | Step 650/767 | Loss 0.5650


Epoch 1/3 | Step 700/767 | Loss 0.1047


Epoch 1/3 | Step 750/767 | Loss 0.9982


Epoch 1/3 finished | loss=0.7491 | val_f1=0.6977 | val_auc=0.7673 | time=9.55 min


Epoch 2/3 | Step 0/767 | Loss 0.0128


Epoch 2/3 | Step 50/767 | Loss 0.6725


Epoch 2/3 | Step 100/767 | Loss 1.3486


Epoch 2/3 | Step 150/767 | Loss 0.0939


Epoch 2/3 | Step 200/767 | Loss 0.0073


Epoch 2/3 | Step 250/767 | Loss 1.2544


Epoch 2/3 | Step 300/767 | Loss 0.0558


Epoch 2/3 | Step 350/767 | Loss 2.2386


Epoch 2/3 | Step 400/767 | Loss 0.0116


Epoch 2/3 | Step 450/767 | Loss 0.9823


Epoch 2/3 | Step 500/767 | Loss 0.1334


Epoch 2/3 | Step 550/767 | Loss 0.0297


Epoch 2/3 | Step 600/767 | Loss 0.4458


Epoch 2/3 | Step 650/767 | Loss 0.0032


Epoch 2/3 | Step 700/767 | Loss 2.1249


Epoch 2/3 | Step 750/767 | Loss 0.7481


Epoch 2/3 finished | loss=0.6751 | val_f1=0.7511 | val_auc=0.7765 | time=9.54 min


Epoch 3/3 | Step 0/767 | Loss 1.0232


Epoch 3/3 | Step 50/767 | Loss 0.5496


Epoch 3/3 | Step 100/767 | Loss 1.4366


Epoch 3/3 | Step 150/767 | Loss 0.5111


Epoch 3/3 | Step 200/767 | Loss 2.6837


Epoch 3/3 | Step 250/767 | Loss 1.5408


Epoch 3/3 | Step 300/767 | Loss 0.0550


Epoch 3/3 | Step 350/767 | Loss 0.2609


Epoch 3/3 | Step 400/767 | Loss 1.4503


Epoch 3/3 | Step 450/767 | Loss 0.9590


Epoch 3/3 | Step 500/767 | Loss 1.5414


Epoch 3/3 | Step 550/767 | Loss 0.4339


Epoch 3/3 | Step 600/767 | Loss 0.9096


Epoch 3/3 | Step 650/767 | Loss 0.0964


Epoch 3/3 | Step 700/767 | Loss 0.0584


Epoch 3/3 | Step 750/767 | Loss 0.9976


Epoch 3/3 finished | loss=0.6236 | val_f1=0.6952 | val_auc=0.7781 | time=9.54 min


Classifier inference:   0%|          | 0/3 [00:00<?, ?it/s]


Running config: pool=max__topk=1__spans=3-5-8__stride=2__freeze=True


Epoch 1/3 | Step 0/767 | Loss 1.5780


Epoch 1/3 | Step 50/767 | Loss 0.9410


Epoch 1/3 | Step 100/767 | Loss 0.4296


Epoch 1/3 | Step 150/767 | Loss 0.5665


Epoch 1/3 | Step 200/767 | Loss 0.5651


Epoch 1/3 | Step 250/767 | Loss 2.5100


Epoch 1/3 | Step 300/767 | Loss 1.7696


Epoch 1/3 | Step 350/767 | Loss 0.8186


Epoch 1/3 | Step 400/767 | Loss 0.1830


Epoch 1/3 | Step 450/767 | Loss 0.9042


Epoch 1/3 | Step 500/767 | Loss 0.6940


Epoch 1/3 | Step 550/767 | Loss 1.6237


Epoch 1/3 | Step 600/767 | Loss 0.9047


Epoch 1/3 | Step 650/767 | Loss 0.8179


Epoch 1/3 | Step 700/767 | Loss 1.5391


Epoch 1/3 | Step 750/767 | Loss 0.9893


Epoch 1/3 finished | loss=0.7297 | val_f1=0.5319 | val_auc=0.7413 | time=13.18 min


Epoch 2/3 | Step 0/767 | Loss 1.6830


Epoch 2/3 | Step 50/767 | Loss 0.8475


Epoch 2/3 | Step 100/767 | Loss 1.6953


Epoch 2/3 | Step 150/767 | Loss 1.5630


Epoch 2/3 | Step 200/767 | Loss 0.3375


Epoch 2/3 | Step 250/767 | Loss 0.9876


Epoch 2/3 | Step 300/767 | Loss 0.2626


Epoch 2/3 | Step 350/767 | Loss 0.6437


Epoch 2/3 | Step 400/767 | Loss 0.7698


Epoch 2/3 | Step 450/767 | Loss 0.4067


Epoch 2/3 | Step 500/767 | Loss 0.7577


Epoch 2/3 | Step 550/767 | Loss 0.3722


Epoch 2/3 | Step 600/767 | Loss 0.0514


Epoch 2/3 | Step 650/767 | Loss 0.9236


Epoch 2/3 | Step 700/767 | Loss 0.9322


Epoch 2/3 | Step 750/767 | Loss 0.5044


Epoch 2/3 finished | loss=0.6890 | val_f1=0.4972 | val_auc=0.7409 | time=13.17 min


Epoch 3/3 | Step 0/767 | Loss 1.2845


Epoch 3/3 | Step 50/767 | Loss 1.4092


Epoch 3/3 | Step 100/767 | Loss 1.9112


Epoch 3/3 | Step 150/767 | Loss 0.6240


Epoch 3/3 | Step 200/767 | Loss 0.0698


Epoch 3/3 | Step 250/767 | Loss 0.1211


Epoch 3/3 | Step 300/767 | Loss 0.1344


Epoch 3/3 | Step 350/767 | Loss 0.1040


Epoch 3/3 | Step 400/767 | Loss 0.1776


Epoch 3/3 | Step 450/767 | Loss 0.5693


Epoch 3/3 | Step 500/767 | Loss 0.1709


Epoch 3/3 | Step 550/767 | Loss 1.9474


Epoch 3/3 | Step 600/767 | Loss 0.0447


Epoch 3/3 | Step 650/767 | Loss 0.2342


Epoch 3/3 | Step 700/767 | Loss 0.2100


Epoch 3/3 | Step 750/767 | Loss 0.3222


Epoch 3/3 finished | loss=0.6945 | val_f1=0.5056 | val_auc=0.7406 | time=13.17 min


Classifier inference:   0%|          | 0/3 [00:00<?, ?it/s]


Running config: pool=max__topk=1__spans=3-5-8__stride=4__freeze=True


Epoch 1/3 | Step 0/767 | Loss 3.6538


Epoch 1/3 | Step 50/767 | Loss 0.0834


Epoch 1/3 | Step 100/767 | Loss 0.6064


Epoch 1/3 | Step 150/767 | Loss 0.9247


Epoch 1/3 | Step 200/767 | Loss 0.6785


Epoch 1/3 | Step 250/767 | Loss 0.7824


Epoch 1/3 | Step 300/767 | Loss 0.6860


Epoch 1/3 | Step 350/767 | Loss 1.4224


Epoch 1/3 | Step 400/767 | Loss 1.0536


Epoch 1/3 | Step 450/767 | Loss 0.2319


Epoch 1/3 | Step 500/767 | Loss 0.7135


Epoch 1/3 | Step 550/767 | Loss 0.8157


Epoch 1/3 | Step 600/767 | Loss 0.8488


Epoch 1/3 | Step 650/767 | Loss 0.9516


Epoch 1/3 | Step 700/767 | Loss 0.0342


Epoch 1/3 | Step 750/767 | Loss 0.0943


Epoch 1/3 finished | loss=0.7964 | val_f1=0.6442 | val_auc=0.7503 | time=10.34 min


Epoch 2/3 | Step 0/767 | Loss 0.1415


Epoch 2/3 | Step 50/767 | Loss 1.3736


Epoch 2/3 | Step 100/767 | Loss 0.0300


Epoch 2/3 | Step 150/767 | Loss 1.6061


Epoch 2/3 | Step 200/767 | Loss 1.0137


Epoch 2/3 | Step 250/767 | Loss 0.1192


Epoch 2/3 | Step 300/767 | Loss 0.4142


Epoch 2/3 | Step 350/767 | Loss 0.5479


Epoch 2/3 | Step 400/767 | Loss 0.0441


Epoch 2/3 | Step 450/767 | Loss 0.3186


Epoch 2/3 | Step 500/767 | Loss 0.3651


Epoch 2/3 | Step 550/767 | Loss 0.8100


Epoch 2/3 | Step 600/767 | Loss 1.7013


Epoch 2/3 | Step 650/767 | Loss 1.0697


Epoch 2/3 | Step 700/767 | Loss 0.7897


Epoch 2/3 | Step 750/767 | Loss 1.7160


Epoch 2/3 finished | loss=0.7195 | val_f1=0.5699 | val_auc=0.7492 | time=10.35 min


Epoch 3/3 | Step 0/767 | Loss 0.0691


Epoch 3/3 | Step 50/767 | Loss 0.1198


Epoch 3/3 | Step 100/767 | Loss 0.5899


Epoch 3/3 | Step 150/767 | Loss 0.6969


Epoch 3/3 | Step 200/767 | Loss 1.1547


Epoch 3/3 | Step 250/767 | Loss 2.1486


Epoch 3/3 | Step 300/767 | Loss 0.1133


Epoch 3/3 | Step 350/767 | Loss 1.6090


Epoch 3/3 | Step 400/767 | Loss 0.2640


Epoch 3/3 | Step 450/767 | Loss 0.2258


Epoch 3/3 | Step 500/767 | Loss 0.0243


Epoch 3/3 | Step 550/767 | Loss 0.0456


Epoch 3/3 | Step 600/767 | Loss 0.9706


Epoch 3/3 | Step 650/767 | Loss 0.2240


Epoch 3/3 | Step 700/767 | Loss 0.0122


Epoch 3/3 | Step 750/767 | Loss 0.0732


Epoch 3/3 finished | loss=0.6804 | val_f1=0.5816 | val_auc=0.7490 | time=10.35 min


Classifier inference:   0%|          | 0/3 [00:00<?, ?it/s]


Running config: pool=max__topk=1__spans=5-10-15__stride=2__freeze=True


Epoch 1/3 | Step 0/767 | Loss 0.0340


Epoch 1/3 | Step 50/767 | Loss 0.0920


Epoch 1/3 | Step 100/767 | Loss 0.7933


Epoch 1/3 | Step 150/767 | Loss 0.7214


Epoch 1/3 | Step 200/767 | Loss 0.8373


Epoch 1/3 | Step 250/767 | Loss 0.0840


Epoch 1/3 | Step 300/767 | Loss 1.1078


Epoch 1/3 | Step 350/767 | Loss 0.1876


Epoch 1/3 | Step 400/767 | Loss 0.1990


Epoch 1/3 | Step 450/767 | Loss 2.4414


Epoch 1/3 | Step 500/767 | Loss 1.0956


Epoch 1/3 | Step 550/767 | Loss 0.1901


Epoch 1/3 | Step 600/767 | Loss 0.0752


Epoch 1/3 | Step 650/767 | Loss 0.0762


Epoch 1/3 | Step 700/767 | Loss 0.0363


Epoch 1/3 | Step 750/767 | Loss 0.0921


Epoch 1/3 finished | loss=0.7125 | val_f1=0.2721 | val_auc=0.7458 | time=12.76 min


Epoch 2/3 | Step 0/767 | Loss 0.2949


Epoch 2/3 | Step 50/767 | Loss 0.4047


Epoch 2/3 | Step 100/767 | Loss 0.1415


Epoch 2/3 | Step 150/767 | Loss 2.1455


Epoch 2/3 | Step 200/767 | Loss 0.0592


Epoch 2/3 | Step 250/767 | Loss 0.0458


Epoch 2/3 | Step 300/767 | Loss 0.4161


Epoch 2/3 | Step 350/767 | Loss 0.0182


Epoch 2/3 | Step 400/767 | Loss 0.4093


Epoch 2/3 | Step 450/767 | Loss 0.2171


Epoch 2/3 | Step 500/767 | Loss 0.3150


Epoch 2/3 | Step 550/767 | Loss 0.0303


Epoch 2/3 | Step 600/767 | Loss 0.8190


Epoch 2/3 | Step 650/767 | Loss 0.6588


Epoch 2/3 | Step 700/767 | Loss 0.0149


Epoch 2/3 | Step 750/767 | Loss 1.2837


Epoch 2/3 finished | loss=0.6768 | val_f1=0.7583 | val_auc=0.7661 | time=12.74 min


Epoch 3/3 | Step 0/767 | Loss 0.0081


Epoch 3/3 | Step 50/767 | Loss 0.1924


Epoch 3/3 | Step 100/767 | Loss 0.1224


Epoch 3/3 | Step 150/767 | Loss 3.4203


Epoch 3/3 | Step 200/767 | Loss 0.1823


Epoch 3/3 | Step 250/767 | Loss 0.1824


Epoch 3/3 | Step 300/767 | Loss 0.6713


Epoch 3/3 | Step 350/767 | Loss 0.2538


Epoch 3/3 | Step 400/767 | Loss 2.2614


Epoch 3/3 | Step 450/767 | Loss 0.1064


Epoch 3/3 | Step 500/767 | Loss 0.8304


Epoch 3/3 | Step 550/767 | Loss 0.0948


Epoch 3/3 | Step 600/767 | Loss 0.0586


Epoch 3/3 | Step 650/767 | Loss 0.4427


Epoch 3/3 | Step 700/767 | Loss 0.3585


Epoch 3/3 | Step 750/767 | Loss 0.0183


Epoch 3/3 finished | loss=0.6984 | val_f1=0.6186 | val_auc=0.7619 | time=12.73 min


Classifier inference:   0%|          | 0/3 [00:00<?, ?it/s]


Running config: pool=max__topk=1__spans=5-10-15__stride=4__freeze=True


Epoch 1/3 | Step 0/767 | Loss 0.0286


Epoch 1/3 | Step 50/767 | Loss 1.8716


Epoch 1/3 | Step 100/767 | Loss 0.6799


Epoch 1/3 | Step 150/767 | Loss 0.5970


Epoch 1/3 | Step 200/767 | Loss 0.9092


Epoch 1/3 | Step 250/767 | Loss 0.5166


Epoch 1/3 | Step 300/767 | Loss 0.0731


Epoch 1/3 | Step 350/767 | Loss 0.6438


Epoch 1/3 | Step 400/767 | Loss 0.3137


Epoch 1/3 | Step 450/767 | Loss 0.0955


Epoch 1/3 | Step 500/767 | Loss 0.1410


Epoch 1/3 | Step 550/767 | Loss 0.2640


Epoch 1/3 | Step 600/767 | Loss 0.0681


Epoch 1/3 | Step 650/767 | Loss 0.2486


Epoch 1/3 | Step 700/767 | Loss 0.2337


Epoch 1/3 | Step 750/767 | Loss 0.0305


Epoch 1/3 finished | loss=0.7644 | val_f1=0.6761 | val_auc=0.7681 | time=10.11 min


Epoch 2/3 | Step 0/767 | Loss 0.0062


Epoch 2/3 | Step 50/767 | Loss 0.3092


Epoch 2/3 | Step 100/767 | Loss 1.4234


Epoch 2/3 | Step 150/767 | Loss 1.6381


Epoch 2/3 | Step 200/767 | Loss 0.2904


Epoch 2/3 | Step 250/767 | Loss 0.0558


Epoch 2/3 | Step 300/767 | Loss 0.7516


Epoch 2/3 | Step 350/767 | Loss 0.0781


Epoch 2/3 | Step 400/767 | Loss 0.1555


Epoch 2/3 | Step 450/767 | Loss 1.2438


Epoch 2/3 | Step 500/767 | Loss 1.3334


Epoch 2/3 | Step 550/767 | Loss 0.9988


Epoch 2/3 | Step 600/767 | Loss 0.1999


Epoch 2/3 | Step 650/767 | Loss 1.1900


Epoch 2/3 | Step 700/767 | Loss 0.0188


Epoch 2/3 | Step 750/767 | Loss 0.5448


Epoch 2/3 finished | loss=0.6868 | val_f1=0.6091 | val_auc=0.7628 | time=10.06 min


Epoch 3/3 | Step 0/767 | Loss 1.3624


Epoch 3/3 | Step 50/767 | Loss 0.1156


Epoch 3/3 | Step 100/767 | Loss 0.5601


Epoch 3/3 | Step 150/767 | Loss 0.9622


Epoch 3/3 | Step 200/767 | Loss 0.2143


Epoch 3/3 | Step 250/767 | Loss 0.3238


Epoch 3/3 | Step 300/767 | Loss 0.0541


Epoch 3/3 | Step 350/767 | Loss 2.8689


Epoch 3/3 | Step 400/767 | Loss 1.0324


Epoch 3/3 | Step 450/767 | Loss 0.0577


Epoch 3/3 | Step 500/767 | Loss 0.0585


Epoch 3/3 | Step 550/767 | Loss 0.0218


Epoch 3/3 | Step 600/767 | Loss 1.4399


Epoch 3/3 | Step 650/767 | Loss 0.1788


Epoch 3/3 | Step 700/767 | Loss 0.0687


Epoch 3/3 | Step 750/767 | Loss 0.0919


Epoch 3/3 finished | loss=0.6900 | val_f1=0.5775 | val_auc=0.7592 | time=10.06 min


Classifier inference:   0%|          | 0/3 [00:00<?, ?it/s]


Running config: pool=max__topk=1__spans=10-15-20__stride=2__freeze=True


Epoch 1/3 | Step 0/767 | Loss 0.0309


Epoch 1/3 | Step 50/767 | Loss 0.7716


Epoch 1/3 | Step 100/767 | Loss 0.5137


Epoch 1/3 | Step 150/767 | Loss 0.3532


Epoch 1/3 | Step 200/767 | Loss 0.2687


Epoch 1/3 | Step 250/767 | Loss 0.1521


Epoch 1/3 | Step 300/767 | Loss 0.4214


Epoch 1/3 | Step 350/767 | Loss 2.0167


Epoch 1/3 | Step 400/767 | Loss 0.6820


Epoch 1/3 | Step 450/767 | Loss 0.7487


Epoch 1/3 | Step 500/767 | Loss 0.0710


Epoch 1/3 | Step 550/767 | Loss 0.9503


Epoch 1/3 | Step 600/767 | Loss 0.7899


Epoch 1/3 | Step 650/767 | Loss 0.3959


Epoch 1/3 | Step 700/767 | Loss 0.2398


Epoch 1/3 | Step 750/767 | Loss 0.7923


Epoch 1/3 finished | loss=0.7476 | val_f1=0.2953 | val_auc=0.7571 | time=12.37 min


Epoch 2/3 | Step 0/767 | Loss 2.7214


Epoch 2/3 | Step 50/767 | Loss 0.2484


Epoch 2/3 | Step 100/767 | Loss 0.0385


Epoch 2/3 | Step 150/767 | Loss 0.0310


Epoch 2/3 | Step 200/767 | Loss 0.0445


Epoch 2/3 | Step 250/767 | Loss 0.2028


Epoch 2/3 | Step 300/767 | Loss 0.3299


Epoch 2/3 | Step 350/767 | Loss 1.2909


Epoch 2/3 | Step 400/767 | Loss 0.0769


Epoch 2/3 | Step 450/767 | Loss 0.8668


Epoch 2/3 | Step 500/767 | Loss 0.0239


Epoch 2/3 | Step 550/767 | Loss 0.0136


Epoch 2/3 | Step 600/767 | Loss 0.0826


Epoch 2/3 | Step 650/767 | Loss 2.8970


Epoch 2/3 | Step 700/767 | Loss 1.9885


Epoch 2/3 | Step 750/767 | Loss 0.5157


Epoch 2/3 finished | loss=0.6536 | val_f1=0.6032 | val_auc=0.7772 | time=12.54 min


Epoch 3/3 | Step 0/767 | Loss 0.0232


Epoch 3/3 | Step 50/767 | Loss 0.0074


Epoch 3/3 | Step 100/767 | Loss 0.1011


Epoch 3/3 | Step 150/767 | Loss 1.1275


Epoch 3/3 | Step 200/767 | Loss 0.0570


Epoch 3/3 | Step 250/767 | Loss 0.1887


Epoch 3/3 | Step 300/767 | Loss 0.1429


Epoch 3/3 | Step 350/767 | Loss 4.5951


Epoch 3/3 | Step 400/767 | Loss 2.3742


Epoch 3/3 | Step 450/767 | Loss 0.0389


Epoch 3/3 | Step 500/767 | Loss 0.6448


Epoch 3/3 | Step 550/767 | Loss 0.0124


Epoch 3/3 | Step 600/767 | Loss 0.0559


Epoch 3/3 | Step 650/767 | Loss 0.8887


Epoch 3/3 | Step 700/767 | Loss 0.1076


Epoch 3/3 | Step 750/767 | Loss 0.0064


Epoch 3/3 finished | loss=0.6742 | val_f1=0.5957 | val_auc=0.7748 | time=12.33 min


Classifier inference:   0%|          | 0/3 [00:00<?, ?it/s]


Running config: pool=max__topk=1__spans=10-15-20__stride=4__freeze=True


Epoch 1/3 | Step 0/767 | Loss 3.4669


Epoch 1/3 | Step 50/767 | Loss 1.6711


Epoch 1/3 | Step 100/767 | Loss 0.2976


Epoch 1/3 | Step 150/767 | Loss 1.1093


Epoch 1/3 | Step 200/767 | Loss 0.5974


Epoch 1/3 | Step 250/767 | Loss 0.2248


Epoch 1/3 | Step 300/767 | Loss 0.3499


Epoch 1/3 | Step 350/767 | Loss 1.1066


Epoch 1/3 | Step 400/767 | Loss 1.1455


Epoch 1/3 | Step 450/767 | Loss 1.3494


Epoch 1/3 | Step 500/767 | Loss 0.4876


Epoch 1/3 | Step 550/767 | Loss 0.6363


Epoch 1/3 | Step 600/767 | Loss 0.4884


Epoch 1/3 | Step 650/767 | Loss 0.2715


Epoch 1/3 | Step 700/767 | Loss 1.4955


Epoch 1/3 | Step 750/767 | Loss 0.9466


Epoch 1/3 finished | loss=0.7107 | val_f1=0.7531 | val_auc=0.7785 | time=9.52 min


Epoch 2/3 | Step 0/767 | Loss 0.9887


Epoch 2/3 | Step 50/767 | Loss 0.4242


Epoch 2/3 | Step 100/767 | Loss 1.4094


Epoch 2/3 | Step 150/767 | Loss 2.7123


Epoch 2/3 | Step 200/767 | Loss 0.0391


Epoch 2/3 | Step 250/767 | Loss 0.3340


Epoch 2/3 | Step 300/767 | Loss 0.0093


Epoch 2/3 | Step 350/767 | Loss 0.6294


Epoch 2/3 | Step 400/767 | Loss 0.1691


Epoch 2/3 | Step 450/767 | Loss 0.8130


Epoch 2/3 | Step 500/767 | Loss 1.3844


Epoch 2/3 | Step 550/767 | Loss 1.5269


Epoch 2/3 | Step 600/767 | Loss 0.0740


Epoch 2/3 | Step 650/767 | Loss 0.0071


Epoch 2/3 | Step 700/767 | Loss 1.1908


Epoch 2/3 | Step 750/767 | Loss 0.0566


Epoch 2/3 finished | loss=0.6673 | val_f1=0.7103 | val_auc=0.7818 | time=9.51 min


Epoch 3/3 | Step 0/767 | Loss 0.7248


Epoch 3/3 | Step 50/767 | Loss 0.1505


Epoch 3/3 | Step 100/767 | Loss 0.4935


Epoch 3/3 | Step 150/767 | Loss 0.8548


Epoch 3/3 | Step 200/767 | Loss 0.0054


Epoch 3/3 | Step 250/767 | Loss 0.1159


Epoch 3/3 | Step 300/767 | Loss 0.1200


Epoch 3/3 | Step 350/767 | Loss 0.0904


Epoch 3/3 | Step 400/767 | Loss 1.5184


Epoch 3/3 | Step 450/767 | Loss 1.5884


Epoch 3/3 | Step 500/767 | Loss 0.1051


Epoch 3/3 | Step 550/767 | Loss 3.4421


Epoch 3/3 | Step 600/767 | Loss 1.0013


Epoch 3/3 | Step 650/767 | Loss 2.5641


Epoch 3/3 | Step 700/767 | Loss 1.1322


Epoch 3/3 | Step 750/767 | Loss 0.5915


Epoch 3/3 finished | loss=0.6732 | val_f1=0.6700 | val_auc=0.7785 | time=9.53 min


Classifier inference:   0%|          | 0/3 [00:00<?, ?it/s]

,pooling_mode,top_k,span_lengths,span_lengths_label,stride,freeze_encoder,config_id,train_time_minutes,train_accuracy,train_precision,...,val_std_predicted_probability,val_positive_prediction_rate,val_tp_n_arguments,val_tp_mean_prob_drop,val_tp_median_prob_drop,val_tp_positive_drop_rate,val_tp_strong_drop_rate_001,val_tp_strong_drop_rate_005,val_tp_mean_masked_word_ratio,val_tp_mean_total_masked_words
0,topk_noisy_or,1,"(3, 5, 8)",3-5-8,2,True,pool=topk_noisy_or__topk=1__spans=3-5-8__strid...,39.369830,0.705153,0.830156,...,0.299365,0.340909,88,0.031947,0.000112,0.556818,0.147727,0.068182,0.437449,19.784091
1,topk_noisy_or,3,"(3, 5, 8)",3-5-8,2,True,pool=topk_noisy_or__topk=3__spans=3-5-8__strid...,39.617171,0.669928,0.879350,...,0.321084,0.245455,88,0.056294,0.000105,0.590909,0.204545,0.125000,0.412257,18.988636
2,topk_noisy_or,5,"(3, 5, 8)",3-5-8,2,True,pool=topk_noisy_or__topk=5__spans=3-5-8__strid...,39.556878,0.709067,0.860335,...,0.363772,0.336364,88,0.049984,0.000118,0.602273,0.204545,0.125000,0.410166,18.943182
3,topk_noisy_or,1,"(3, 5, 8)",3-5-8,4,True,pool=topk_noisy_or__topk=1__spans=3-5-8__strid...,31.115266,0.713633,0.705637,...,0.321613,0.559091,88,0.057901,0.000021,0.522727,0.193182,0.136364,0.391577,17.920455
4,topk_noisy_or,3,"(3, 5, 8)",3-5-8,4,True,pool=topk_noisy_or__topk=3__spans=3-5-8__strid...,31.118815,0.711024,0.822848,...,0.356458,0.390909,88,0.042025,0.000080,0.545455,0.193182,0.125000,0.396521,18.272727
5,topk_noisy_or,5,"(3, 5, 8)",3-5-8,4,True,pool=topk_noisy_or__topk=5__spans=3-5-8__strid...,31.132370,0.702544,0.821124,...,0.356559,0.381818,88,0.047337,0.000006,0.511364,0.181818,0.125000,0.396439,18.204545
6,topk_noisy_or,1,"(5, 10, 15)",5-10-15,2,True,pool=topk_noisy_or__topk=1__spans=5-10-15__str...,38.325160,0.706458,0.867562,...,0.324253,0.295455,88,0.083566,0.000267,0.625000,0.204545,0.170455,0.667694,32.500000
7,topk_noisy_or,3,"(5, 10, 15)",5-10-15,2,True,pool=topk_noisy_or__topk=3__spans=5-10-15__str...,38.376781,0.742335,0.847619,...,0.354260,0.377273,88,0.101466,0.000150,0.636364,0.204545,0.181818,0.653329,32.022727
8,topk_noisy_or,5,"(5, 10, 15)",5-10-15,2,True,pool=topk_noisy_or__topk=5__spans=5-10-15__str...,38.363592,0.736464,0.865417,...,0.350296,0.331818,88,0.070183,0.000150,0.613636,0.193182,0.147727,0.661820,32.522727
9,topk_noisy_or,1,"(5, 10, 15)",5-10-15,4,True,pool=topk_noisy_or__topk=1__spans=5-10-15__str...,30.460005,0.748858,0.819088,...,0.368203,0.427273,88,0.074936,0.000246,0.590909,0.204545,0.147727,0.639059,31.659091


In [28]:
MIN_VAL_F1 = 0.70
MIN_VAL_AUC = 0.70
MAX_MASKED_WORD_RATIO = 0.70

candidate_configs = val_config_summary[
    (val_config_summary["val_f1"] >= MIN_VAL_F1) &
    (val_config_summary["val_roc_auc"] >= MIN_VAL_AUC) &
    (val_config_summary["val_tp_mean_masked_word_ratio"] <= MAX_MASKED_WORD_RATIO)
].copy()

candidate_configs = candidate_configs.sort_values(
    ["val_tp_mean_prob_drop", "val_roc_auc", "val_f1"],
    ascending=[False, False, False],
)

display(candidate_configs.head(10))

BEST_CONFIG = candidate_configs.iloc[0].to_dict()

print("Selected config:")
for key, value in BEST_CONFIG.items():
    if key in ["config_id", "pooling_mode", "top_k", "span_lengths", "span_lengths_label", "stride", "freeze_encoder"]:
        print(f"{key}: {value}")

,pooling_mode,top_k,span_lengths,span_lengths_label,stride,freeze_encoder,config_id,train_time_minutes,train_accuracy,train_precision,...,val_std_predicted_probability,val_positive_prediction_rate,val_tp_n_arguments,val_tp_mean_prob_drop,val_tp_median_prob_drop,val_tp_positive_drop_rate,val_tp_strong_drop_rate_001,val_tp_strong_drop_rate_005,val_tp_mean_masked_word_ratio,val_tp_mean_total_masked_words
38,max,1,"(5, 10, 15)",5-10-15,2,True,pool=max__topk=1__spans=5-10-15__stride=2__fre...,38.242323,0.759295,0.780193,...,0.384508,0.527273,88,0.091564,0.000408,0.625000,0.204545,0.170455,0.671015,32.534091
9,topk_noisy_or,1,"(5, 10, 15)",5-10-15,4,True,pool=topk_noisy_or__topk=1__spans=5-10-15__str...,30.460005,0.748858,0.819088,...,0.368203,0.427273,88,0.074936,0.000246,0.590909,0.204545,0.147727,0.639059,31.659091
28,topk_mean,3,"(5, 10, 15)",5-10-15,4,True,pool=topk_mean__topk=3__spans=5-10-15__stride=...,30.196815,0.750163,0.765330,...,0.382091,0.527273,88,0.073830,0.000368,0.647727,0.204545,0.147727,0.657801,32.306818
27,topk_mean,1,"(5, 10, 15)",5-10-15,4,True,pool=topk_mean__topk=1__spans=5-10-15__stride=...,30.213827,0.744292,0.770552,...,0.354700,0.504545,88,0.067464,0.000366,0.647727,0.204545,0.147727,0.648988,32.147727
29,topk_mean,5,"(5, 10, 15)",5-10-15,4,True,pool=topk_mean__topk=5__spans=5-10-15__stride=...,30.227746,0.758643,0.766398,...,0.374860,0.540909,88,0.058224,0.000262,0.602273,0.215909,0.136364,0.626959,31.034091
3,topk_noisy_or,1,"(3, 5, 8)",3-5-8,4,True,pool=topk_noisy_or__topk=1__spans=3-5-8__strid...,31.115266,0.713633,0.705637,...,0.321613,0.559091,88,0.057901,0.000021,0.522727,0.193182,0.136364,0.391577,17.920455
18,topk_mean,1,"(3, 5, 8)",3-5-8,2,True,pool=topk_mean__topk=1__spans=3-5-8__stride=2_...,39.519664,0.736464,0.798331,...,0.345895,0.468182,88,0.053784,0.000183,0.636364,0.193182,0.113636,0.416194,19.056818


Selected config:
pooling_mode: max
top_k: 1
span_lengths: (5, 10, 15)
span_lengths_label: 5-10-15
stride: 2
freeze_encoder: True
config_id: pool=max__topk=1__spans=5-10-15__stride=2__freeze=True


## Selection of the final MIL configuration

The final MIL configuration was selected exclusively on the validation split. The test split was not used for hyperparameter selection.

Since MIL is evaluated both as a document-level classifier and as a span localization method, the selection criterion combines two requirements. First, the model must achieve acceptable bag-level classification performance on the validation split. Therefore, configurations were only considered if they reached a validation F1 score of at least **0.70** and a validation ROC-AUC of at least **0.75**. Second, the selected spans should not explain the prediction by masking excessively large parts of the argument. Therefore, configurations were only considered if their mean masked word ratio on validation true positives was at most **0.70**.

Among all configurations satisfying these constraints, the final configuration was selected by maximizing the mean probability drop on validation true positives. ROC-AUC and F1 were used as secondary tie-breakers. This selection strategy prioritizes spans that have a measurable effect on the original document-level classifier while avoiding configurations that obtain high probability drops mainly by masking most of the argument.

The selected configuration is:

- **Pooling mode:** `max`
- **Top-k:** `1`
- **Span lengths:** `5-10-15`
- **Stride:** `2`
- **Frozen encoder:** `True`

This configuration achieved a validation F1 score of **0.758**, a validation ROC-AUC of **0.766**, and a mean probability drop of **0.092** on validation true positives, while masking on average **0.671** of the words. The resulting spans are therefore interpreted as a balanced trade-off between perturbation effectiveness and localization granularity.

## Final selected MIL configuration

The final MIL configuration is selected on the validation split only.  
The test split is not used for hyperparameter selection.

The selected model is then applied to train, validation, and test to export comparable argument-level and span-level files.

In [38]:
DESIRED_CONFIG = {
    "pooling_mode": "max",
    "top_k": 1,
    "span_lengths": (5, 10, 15),
    "span_lengths_label": "5-10-15",
    "stride": 2,
    "freeze_encoder": True,
    "config_id": "pool=max__topk=1__spans=5-10-15__stride=2__freeze=True",
}

DESIRED_CONFIG_ID = DESIRED_CONFIG["config_id"]
DESIRED_CHECKPOINT_PATH = os.path.join(
    "mil_results",
    "mil_span_run_20260724_091019",
    "validation_grid",
    DESIRED_CONFIG_ID,
    "model_checkpoint.pt",
)

print(DESIRED_CONFIG_ID)
print(DESIRED_CHECKPOINT_PATH)

checkpoint = torch.load(
        DESIRED_CHECKPOINT_PATH,
        map_location="cpu"
    )

desired_model = MILPoolingModel(
    model_name=MODEL_NAME,
    pooling_mode=DESIRED_CONFIG["pooling_mode"],
    top_k=DESIRED_CONFIG["top_k"],
    initial_instance_prob=INITIAL_INSTANCE_PROB,
    encoder_chunk_size=ENCODER_CHUNK_SIZE,
    encoder_dtype=ENCODER_DTYPE,
    freeze_encoder=DESIRED_CONFIG["freeze_encoder"],
)

desired_model.load_state_dict(checkpoint["model_state_dict"])
desired_model = desired_model.to(TORCH_DEVICE)
desired_model.eval()

print("Loaded desired model from checkpoint.")

pool=max__topk=1__spans=5-10-15__stride=2__freeze=True
mil_results/mil_span_run_20260724_091019/validation_grid/pool=max__topk=1__spans=5-10-15__stride=2__freeze=True/model_checkpoint.pt


/tmp/ipykernel_1780200/61876068.py:23: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(


Loaded desired model from checkpoint.


In [40]:
def build_dataset_for_desired_config(df):
    """Build a MIL dataset using the final selected configuration."""
    return AppropriatenessMILDataset(
        df,
        span_lengths=DESIRED_CONFIG["span_lengths"],
        stride=DESIRED_CONFIG["stride"],
    )


train_desired_dataset = build_dataset_for_desired_config(train_df)
val_desired_dataset = build_dataset_for_desired_config(val_df)
test_desired_dataset = build_dataset_for_desired_config(test_df)

train_argument_df, train_span_df = collect_mil_outputs(
    model=desired_model,
    dataset=train_desired_dataset,
    config=DESIRED_CONFIG,
)

val_argument_df, val_span_df = collect_mil_outputs(
    model=desired_model,
    dataset=val_desired_dataset,
    config=DESIRED_CONFIG,
)

test_argument_df, test_span_df = collect_mil_outputs(
    model=desired_model,
    dataset=test_desired_dataset,
    config=DESIRED_CONFIG,
)

print("Train:", train_argument_df.shape, train_span_df.shape)
print("Validation:", val_argument_df.shape, val_span_df.shape)
print("Test:", test_argument_df.shape, test_span_df.shape)

Train: (1533, 26) (100474, 27)
Validation: (220, 26) (14571, 27)
Test: (438, 26) (28915, 27)


In [41]:
train_argument_df, train_top_span_df = add_mil_perturbation_scores(
    train_argument_df,
    train_span_df,
    top_n_spans=MASKING_TOP_N_SPANS,
)

val_argument_df, val_top_span_df = add_mil_perturbation_scores(
    val_argument_df,
    val_span_df,
    top_n_spans=MASKING_TOP_N_SPANS,
)

test_argument_df, test_top_span_df = add_mil_perturbation_scores(
    test_argument_df,
    test_span_df,
    top_n_spans=MASKING_TOP_N_SPANS,
)

final_argument_df = pd.concat(
    [train_argument_df, val_argument_df, test_argument_df],
    ignore_index=True,
)

final_span_df = pd.concat(
    [train_span_df, val_span_df, test_span_df],
    ignore_index=True,
)

final_top_span_df = pd.concat(
    [train_top_span_df, val_top_span_df, test_top_span_df],
    ignore_index=True,
)

display(final_argument_df.head())
display(final_span_df.head())
display(final_top_span_df.head())

Classifier inference:   0%|          | 0/48 [00:00<?, ?it/s]

Classifier inference:   0%|          | 0/7 [00:00<?, ?it/s]

Classifier inference:   0%|          | 0/14 [00:00<?, ?it/s]

,global_row_id,post_id,split,issue,text,label,p_inappropriate_original,predicted_label_original,predicted_score_original,confusion_type,...,selected_span_texts,selected_span_char_start_indices,selected_span_char_end_indices,selected_span_word_start_indices,selected_span_word_end_indices,n_selected_spans,total_masked_chars,total_masked_words,n_words,masked_word_ratio
0,0,1,train,Is the school uniform a good or bad idea:,"people cant be forced to wear school uniforms,...",1,0.997032,LABEL_1,0.997032,TP,...,[has theri own wish whether they want to or do...,"[66, 12, 0]","[113, 65, 53]","[12, 2, 0]","[21, 11, 9]",3,153,30,38,0.789474
1,1,2,train,Firefox vs internet explorer:,"That form of argument degrades this forum, and...",1,0.998218,LABEL_1,0.998218,TP,...,"[lowest common denominator. This word, ""indisp...","[87, 58, 80]","[155, 149, 169]","[16, 10, 14]","[25, 24, 28]",3,248,40,63,0.634921
2,2,3,train,If your spouse committed murder and he or she ...,I wouldnt turn her in becuase she is my wife. ...,0,0.030317,LABEL_0,0.969683,TN,...,[trusted me by telling me what she did then I ...,"[97, 90, 0]","[166, 158, 45]","[22, 20, 0]","[36, 34, 9]",3,182,40,37,1.081081
3,3,4,train,If your spouse committed murder and he or she ...,No I wouldn't turn in my spouse. Just because ...,1,0.998705,LABEL_1,0.998705,TP,...,[in my spouse. Just because the girl that i ma...,"[19, 38, 25]","[69, 61, 84]","[4, 8, 6]","[13, 12, 15]",3,132,25,25,1.000000
4,4,5,train,Tv is better than books:,TV is terrible. Except for Spongebob maybe. Th...,1,0.998405,LABEL_1,0.998405,TP,...,"[terrible. Except for Spongebob maybe., for Sp...","[6, 23, 102]","[43, 53, 123]","[2, 4, 16]","[6, 8, 20]",3,88,15,27,0.555556


,global_row_id,post_id,split,issue,label,confusion_type,mil_probability,mil_predicted_label,span_score,span_logit,...,candidate_span_length,text,pooling_mode,top_k,span_lengths,span_lengths_label,stride,freeze_encoder,config_id,span_rank
0,0,1,train,Is the school uniform a good or bad idea:,1,TP,0.061119,0,0.001785,-6.326402,...,5,"people cant be forced to wear school uniforms,...",max,1,"(5, 10, 15)",5-10-15,2,True,pool=max__topk=1__spans=5-10-15__stride=2__fre...,20
1,0,1,train,Is the school uniform a good or bad idea:,1,TP,0.061119,0,0.000734,-7.215740,...,5,"people cant be forced to wear school uniforms,...",max,1,"(5, 10, 15)",5-10-15,2,True,pool=max__topk=1__spans=5-10-15__stride=2__fre...,26
2,0,1,train,Is the school uniform a good or bad idea:,1,TP,0.061119,0,0.000078,-9.461362,...,5,"people cant be forced to wear school uniforms,...",max,1,"(5, 10, 15)",5-10-15,2,True,pool=max__topk=1__spans=5-10-15__stride=2__fre...,43
3,0,1,train,Is the school uniform a good or bad idea:,1,TP,0.061119,0,0.008808,-4.723269,...,5,"people cant be forced to wear school uniforms,...",max,1,"(5, 10, 15)",5-10-15,2,True,pool=max__topk=1__spans=5-10-15__stride=2__fre...,7
4,0,1,train,Is the school uniform a good or bad idea:,1,TP,0.061119,0,0.010050,-4.590069,...,5,"people cant be forced to wear school uniforms,...",max,1,"(5, 10, 15)",5-10-15,2,True,pool=max__topk=1__spans=5-10-15__stride=2__fre...,6


,global_row_id,post_id,split,issue,label,confusion_type,mil_probability,mil_predicted_label,span_score,span_logit,...,candidate_span_length,text,pooling_mode,top_k,span_lengths,span_lengths_label,stride,freeze_encoder,config_id,span_rank
0,0,1,train,Is the school uniform a good or bad idea:,1,TP,0.061119,0,0.061119,-2.731864,...,10,"people cant be forced to wear school uniforms,...",max,1,"(5, 10, 15)",5-10-15,2,True,pool=max__topk=1__spans=5-10-15__stride=2__fre...,1
1,0,1,train,Is the school uniform a good or bad idea:,1,TP,0.061119,0,0.041546,-3.138513,...,10,"people cant be forced to wear school uniforms,...",max,1,"(5, 10, 15)",5-10-15,2,True,pool=max__topk=1__spans=5-10-15__stride=2__fre...,2
2,0,1,train,Is the school uniform a good or bad idea:,1,TP,0.061119,0,0.036896,-3.262045,...,10,"people cant be forced to wear school uniforms,...",max,1,"(5, 10, 15)",5-10-15,2,True,pool=max__topk=1__spans=5-10-15__stride=2__fre...,3
3,1,2,train,Firefox vs internet explorer:,1,TP,0.869586,1,0.869586,1.897302,...,10,"That form of argument degrades this forum, and...",max,1,"(5, 10, 15)",5-10-15,2,True,pool=max__topk=1__spans=5-10-15__stride=2__fre...,1
4,1,2,train,Firefox vs internet explorer:,1,TP,0.869586,1,0.853104,1.759160,...,15,"That form of argument degrades this forum, and...",max,1,"(5, 10, 15)",5-10-15,2,True,pool=max__topk=1__spans=5-10-15__stride=2__fre...,2


In [2]:
overall_summary = (
    final_argument_df
    .groupby([
        "split",
        "attribution_method",
        "pooling_mode",
        "top_k",
        "span_lengths_label",
        "stride",
        "freeze_encoder",
    ])
    .agg(
        n_arguments=("global_row_id", "nunique"),
        mean_prob_drop=("prob_drop", "mean"),
        median_prob_drop=("prob_drop", "median"),
        std_prob_drop=("prob_drop", "std"),
        positive_drop_rate=("prob_drop", lambda x: (x > 0).mean()),
        strong_drop_rate_001=("prob_drop", lambda x: (x > 0.01).mean()),
        strong_drop_rate_005=("prob_drop", lambda x: (x > 0.05).mean()),
        mean_p_original=("p_inappropriate_original", "mean"),
        mean_p_masked=("p_inappropriate_masked", "mean"),
        mean_mil_probability=("mil_probability", "mean"),
        std_mil_probability=("mil_probability", "std"),
        mean_n_selected_spans=("n_selected_spans", "mean"),
        mean_total_masked_words=("total_masked_words", "mean"),
        mean_total_masked_chars=("total_masked_chars", "mean"),
        mean_masked_word_ratio=("masked_word_ratio", "mean"),
    )
    .reset_index()
)

confusion_summary = (
    final_argument_df
    .groupby(["split", "confusion_type"])
    .agg(
        n_arguments=("global_row_id", "nunique"),
        mean_prob_drop=("prob_drop", "mean"),
        median_prob_drop=("prob_drop", "median"),
        std_prob_drop=("prob_drop", "std"),
        positive_drop_rate=("prob_drop", lambda x: (x > 0).mean()),
        mean_p_original=("p_inappropriate_original", "mean"),
        mean_p_masked=("p_inappropriate_masked", "mean"),
        mean_mil_probability=("mil_probability", "mean"),
        mean_total_masked_words=("total_masked_words", "mean"),
        mean_masked_word_ratio=("masked_word_ratio", "mean"),
    )
    .reset_index()
    .sort_values(["split", "confusion_type"])
)

test_summary = overall_summary[
    overall_summary["split"] == "test"
].copy()

display(overall_summary)
display(confusion_summary)
display(test_summary)

,split,attribution_method,pooling_mode,top_k,span_lengths_label,stride,freeze_encoder,n_arguments,mean_prob_drop,median_prob_drop,...,strong_drop_rate_001,strong_drop_rate_005,mean_p_original,mean_p_masked,mean_mil_probability,std_mil_probability,mean_n_selected_spans,mean_total_masked_words,mean_total_masked_chars,mean_masked_word_ratio
0,test,mil,max,1,5-10-15,2,True,438,-0.006984,0.000060,...,0.189498,0.130137,0.590804,0.597789,0.546126,0.385445,3.0,30.381279,164.874429,0.553915
1,train,mil,max,1,5-10-15,2,True,1533,-0.029605,-0.000022,...,0.155251,0.098500,0.552141,0.581746,0.524619,0.394119,3.0,30.585780,166.688845,0.568406
2,validation,mil,max,1,5-10-15,2,True,220,-0.010937,0.000006,...,0.181818,0.122727,0.542075,0.553012,0.502037,0.385373,3.0,29.754545,160.918182,0.531068


,split,confusion_type,n_arguments,mean_prob_drop,median_prob_drop,std_prob_drop,positive_drop_rate,mean_p_original,mean_p_masked,mean_mil_probability,mean_total_masked_words,mean_masked_word_ratio
0,test,FN,39,-0.182820,-0.001893,0.364982,0.435897,0.049638,0.232457,0.486211,28.205128,0.406339
1,test,FP,71,0.130435,0.000513,0.325707,0.605634,0.971585,0.841150,0.533580,31.239437,0.647548
2,test,TN,142,-0.129318,-0.001311,0.315043,0.408451,0.037216,0.166533,0.339491,27.654930,0.353890
3,test,TP,186,0.070823,0.000112,0.229214,0.602151,0.981555,0.910732,0.721231,32.591398,0.701824
4,train,FN,48,-0.210893,-0.003534,0.406408,0.416667,0.115297,0.326190,0.382080,28.645833,0.488078
5,train,FP,48,0.082692,0.000132,0.319487,0.541667,0.915789,0.833097,0.361602,31.645833,0.708483
6,train,TN,652,-0.148090,-0.001845,0.314790,0.337423,0.030158,0.178248,0.277089,27.773006,0.419322
7,train,TP,785,0.073024,0.000144,0.224571,0.620382,0.990161,0.917137,0.748896,32.975796,0.688578
8,validation,FN,36,-0.202391,-0.005998,0.357832,0.305556,0.040581,0.242972,0.468840,28.805556,0.407293
9,validation,FP,30,0.175948,0.000403,0.353247,0.566667,0.968823,0.792874,0.395860,27.366667,0.546571


,split,attribution_method,pooling_mode,top_k,span_lengths_label,stride,freeze_encoder,n_arguments,mean_prob_drop,median_prob_drop,...,strong_drop_rate_001,strong_drop_rate_005,mean_p_original,mean_p_masked,mean_mil_probability,std_mil_probability,mean_n_selected_spans,mean_total_masked_words,mean_total_masked_chars,mean_masked_word_ratio
0,test,mil,max,1,5-10-15,2,True,438,-0.006984,0.00006,...,0.189498,0.130137,0.590804,0.597789,0.546126,0.385445,3.0,30.381279,164.874429,0.553915


In [ ]:
final_output_dir = OUTPUT_DIR / DESIRED_CONFIG_ID
final_output_dir.mkdir(parents=True, exist_ok=True)

argument_csv_path = final_output_dir / (
    f"mil_final_all_splits_{DESIRED_CONFIG_ID}_argument_level.csv"
)

span_csv_path = final_output_dir / (
    f"mil_final_all_splits_{DESIRED_CONFIG_ID}_span_level.csv"
)

top_span_csv_path = final_output_dir / (
    f"mil_final_all_splits_{DESIRED_CONFIG_ID}_top_spans.csv"
)

overall_summary_csv_path = final_output_dir / (
    f"mil_final_all_splits_{DESIRED_CONFIG_ID}_overall_summary.csv"
)

confusion_summary_csv_path = final_output_dir / (
    f"mil_final_all_splits_{DESIRED_CONFIG_ID}_confusion_summary.csv"
)

test_summary_csv_path = final_output_dir / (
    f"mil_final_test_{DESIRED_CONFIG_ID}_summary.csv"
)

final_argument_df.to_csv(argument_csv_path, index=False, encoding="utf-8")
final_span_df.to_csv(span_csv_path, index=False, encoding="utf-8")
final_top_span_df.to_csv(top_span_csv_path, index=False, encoding="utf-8")
overall_summary.to_csv(overall_summary_csv_path, index=False, encoding="utf-8")
confusion_summary.to_csv(confusion_summary_csv_path, index=False, encoding="utf-8")
test_summary.to_csv(test_summary_csv_path, index=False, encoding="utf-8")

with open(final_output_dir / "selected_config.json", "w", encoding="utf-8") as f:
    json.dump(DESIRED_CONFIG, f, indent=2, ensure_ascii=False)

torch.save(
    {
        "model_state_dict": desired_model.state_dict(),
        "config": DESIRED_CONFIG,
    },
    final_output_dir / "selected_mil_model_checkpoint.pt",
)

print("Saved:")
print(argument_csv_path)
print(span_csv_path)
print(top_span_csv_path)
print(overall_summary_csv_path)
print(confusion_summary_csv_path)
print(test_summary_csv_path)

Saved:
results/mil_results/mil_span_run_20260727_114312/pool=max__topk=1__spans=5-10-15__stride=2__freeze=True/mil_final_all_splits_pool=max__topk=1__spans=5-10-15__stride=2__freeze=True_argument_level.csv
results/mil_results/mil_span_run_20260727_114312/pool=max__topk=1__spans=5-10-15__stride=2__freeze=True/mil_final_all_splits_pool=max__topk=1__spans=5-10-15__stride=2__freeze=True_span_level.csv
results/mil_results/mil_span_run_20260727_114312/pool=max__topk=1__spans=5-10-15__stride=2__freeze=True/mil_final_all_splits_pool=max__topk=1__spans=5-10-15__stride=2__freeze=True_top_spans.csv
results/mil_results/mil_span_run_20260727_114312/pool=max__topk=1__spans=5-10-15__stride=2__freeze=True/mil_final_all_splits_pool=max__topk=1__spans=5-10-15__stride=2__freeze=True_overall_summary.csv
results/mil_results/mil_span_run_20260727_114312/pool=max__topk=1__spans=5-10-15__stride=2__freeze=True/mil_final_all_splits_pool=max__topk=1__spans=5-10-15__stride=2__freeze=True_confusion_summary.csv
res

In [44]:
def highlight_spans(text, spans):
    """Highlight multiple character spans in one text."""
    text = str(text)
    
    if not spans:
        return html.escape(text)
    
    spans = sorted(spans, key=lambda x: int(x["char_start"]))
    
    parts = []
    last_end = 0
    
    for span in spans:
        start = int(span["char_start"])
        end = int(span["char_end"])
        
        if start < last_end:
            continue
        
        parts.append(html.escape(text[last_end:start]))
        parts.append(
            "<mark style='background-color:#ffe58a; padding:2px 4px; border-radius:4px;'>"
            + html.escape(text[start:end])
            + "</mark>"
        )
        last_end = end
    
    parts.append(html.escape(text[last_end:]))
    return "".join(parts)


def show_mil_example(result_df, index=0):
    """Display one MIL result with highlighted selected spans."""
    row = result_df.iloc[index]
    
    spans = json.loads(row["selected_spans_json"])
    marked = highlight_spans(row["text"], spans)
    
    display(HTML(f"""
    <div style="
        border:1px solid #ccc;
        border-radius:8px;
        padding:14px;
        margin:12px 0;
        font-family:Arial, sans-serif;
        line-height:1.45;
    ">
        <b>global_row_id:</b> {html.escape(str(row["global_row_id"]))}<br>
        <b>post_id:</b> {html.escape(str(row["post_id"]))}<br>
        <b>split:</b> {html.escape(str(row["split"]))}<br>
        <b>classifier confusion_type:</b> {html.escape(str(row["confusion_type"]))}<br>
        <b>MIL confusion_type:</b> {html.escape(str(row["mil_confusion_type"]))}<br>
        <b>issue:</b> {html.escape(str(row["issue"]))}<br>
        <b>pooling:</b> {html.escape(str(row["pooling_mode"]))} |
        <b>top_k:</b> {html.escape(str(row["top_k"]))} |
        <b>span_lengths:</b> {html.escape(str(row["span_lengths_label"]))} |
        <b>stride:</b> {html.escape(str(row["stride"]))} |
        <b>freeze_encoder:</b> {html.escape(str(row["freeze_encoder"]))}<br>
        <b>selected spans:</b> {html.escape(str(row["selected_span_texts"]))}<br>
        <b>p_original:</b> {float(row["p_inappropriate_original"]):.4f}<br>
        <b>p_masked:</b> {float(row["p_inappropriate_masked"]):.4f}<br>
        <b>prob_drop:</b> {float(row["prob_drop"]):.4f}<br>
        <b>MIL probability:</b> {float(row["mil_probability"]):.4f}<br>
        <b>masked_word_ratio:</b> {float(row["masked_word_ratio"]):.4f}<br>
        <hr>
        <p>{marked}</p>
    </div>
    """))

In [45]:
test_valid = test_argument_df.copy()

best_examples = (
    test_valid
    .sort_values("prob_drop", ascending=False)
    .reset_index(drop=True)
)

print("Best MIL perturbation examples:")
display(
    best_examples[
        [
            "global_row_id",
            "post_id",
            "confusion_type",
            "mil_confusion_type",
            "prob_drop",
            "masked_word_ratio",
            "selected_span_texts",
        ]
    ].head(10)
)

for i in range(min(5, len(best_examples))):
    show_mil_example(best_examples, index=i)

Best MIL perturbation examples:


,global_row_id,post_id,confusion_type,mil_confusion_type,prob_drop,masked_word_ratio,selected_span_texts
0,2111,1769,FP,FP,0.992804,0.441176,[causes obesity. I'm not going to go for a run...
1,1803,250,FP,FP,0.991283,0.579710,[white anglo-saxon protestants were systematic...
2,1835,407,FP,FP,0.991106,0.530303,[weren't going to abide by it? And... the answ...
3,2085,1632,TP,TP,0.982897,0.297030,[add to their family. DO NOT let anyone tell y...
4,1813,291,TP,FN,0.970108,0.294118,[intelligence.....if we were created. If we ha...
5,2009,1249,FP,TN,0.969126,0.400000,"[open too. Very poor people skills, including ..."
6,2022,1289,FP,FP,0.965048,0.368421,[like about 1 hr just to find their pants or s...
7,1935,887,FP,FP,0.961264,0.321101,[I'm sure!!!!!! Most of them couldn't care les...
8,1762,45,FP,FP,0.954114,0.615385,[change. Who says that he will be lousy foreve...
9,1913,762,TP,TP,0.939363,0.432836,[inferior which then justifies locking them up...


In [46]:
worst_examples = (
    test_valid
    .sort_values("prob_drop", ascending=True)
    .reset_index(drop=True)
)

print("Lowest or negative MIL perturbation examples:")
display(
    worst_examples[
        [
            "global_row_id",
            "post_id",
            "confusion_type",
            "mil_confusion_type",
            "prob_drop",
            "masked_word_ratio",
            "selected_span_texts",
        ]
    ].head(10)
)

for i in range(min(5, len(worst_examples))):
    show_mil_example(worst_examples, index=i)

Lowest or negative MIL perturbation examples:


,global_row_id,post_id,confusion_type,mil_confusion_type,prob_drop,masked_word_ratio,selected_span_texts
0,1786,167,TN,TN,-0.995522,0.775862,[felt like killing somone it may be a little d...
1,1766,63,TN,TN,-0.994159,0.694444,"[right, killing someone and getting away with ..."
2,2080,1618,TN,TN,-0.993370,0.593220,[and she tends to make more mistakes even now ...
3,2005,1217,TN,TN,-0.992932,0.241935,"[well aware that there is no such thing as a, ..."
4,1787,168,TN,FP,-0.991526,0.291667,"[spelling skills. Plus it's more, it. Plus you..."
5,2144,1939,FN,FN,-0.990132,0.769231,"[punishing could last up to, I don't think tha..."
6,1947,950,TN,TN,-0.988893,1.176471,[murder and told me about it. I wouldnt turn h...
7,1929,859,TN,TN,-0.988210,0.810811,"[Personal pursuit is better in, better yoursel..."
8,2083,1626,TN,TN,-0.986880,0.540541,[not kill me? Everyone wants to know what happ...
9,2081,1621,TN,TN,-0.982902,0.833333,"[spank the child as long, It's ok for the pare..."
