"""Data-loading utilities for the span-localization experiments.

The functions in this module load the canonical dataset generated by
``utils.prepare_data``. Experiment notebooks should use these functions
instead of downloading and preprocessing the dataset independently.
"""

from __future__ import annotations

from pathlib import Path

import pandas as pd


PROJECT_ROOT = Path(__file__).resolve().parents[1]

DEFAULT_DATA_FILE = (
    PROJECT_ROOT
    / "data"
    / "processed"
    / "appropriateness_prepared.parquet"
)

REQUIRED_COLUMNS = {
    "global_row_id",
    "split",
    "post_id",
    "post_text",
    "text_norm",
    "Inappropriateness",
    "p_inappropriate_original",
    "predicted_label",
    "predicted_score",
    "confusion_type",
    "is_true_positive",
    "is_false_negative",
    "is_false_positive",
    "is_true_negative",
}


def load_prepared_dataset(
    data_file: str | Path = DEFAULT_DATA_FILE,
) -> pd.DataFrame:
    """Load and validate the canonical processed dataset."""
    data_file = Path(data_file)

    if not data_file.exists():
        raise FileNotFoundError(
            f"Prepared dataset not found at: {data_file}\n"
            "Run `python -m scripts.prepare_data` from the "
            "project root first."
        )

    df = pd.read_parquet(data_file)

    missing_columns = REQUIRED_COLUMNS.difference(
        df.columns
    )

    if missing_columns:
        raise ValueError(
            "Prepared dataset is missing required columns: "
            + ", ".join(sorted(missing_columns))
        )

    if df["global_row_id"].duplicated().any():
        raise ValueError(
            "The prepared dataset contains duplicate "
            "global_row_id values."
        )

    return df


def load_prepared_splits(
    data_file: str | Path = DEFAULT_DATA_FILE,
) -> tuple[
    pd.DataFrame,
    pd.DataFrame,
    pd.DataFrame,
    pd.DataFrame,
]:
    """Load the full dataset and return its three original splits."""
    df_all = load_prepared_dataset(data_file)

    expected_splits = {
        "train",
        "validation",
        "test",
    }

    available_splits = set(
        df_all["split"].dropna().unique()
    )

    missing_splits = expected_splits.difference(
        available_splits
    )

    if missing_splits:
        raise ValueError(
            "Prepared dataset is missing splits: "
            + ", ".join(sorted(missing_splits))
        )

    train_df = (
        df_all[df_all["split"] == "train"]
        .copy()
        .reset_index(drop=True)
    )

    val_df = (
        df_all[df_all["split"] == "validation"]
        .copy()
        .reset_index(drop=True)
    )

    test_df = (
        df_all[df_all["split"] == "test"]
        .copy()
        .reset_index(drop=True)
    )

    return (
        df_all,
        train_df,
        val_df,
        test_df,
    )